### ISSUE TITLE
Render babel-handbook on the website?

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#1000]
https://github.com/thejameskyle/babel-handbook

Was thinking we could render https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md and https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md as a page and link to it for editing

**Comment by nitin42** [comment]
One page for the plugins and the other for user ?
