### ISSUE TITLE
Document website flags/data

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#1001]
```
layout: docs
title: babel-register (require hook)
description: How to use babel-register, the require hook.
permalink: /docs/usage/babel-register/
redirect_from:
 - /docs/usage/require/
package: babel-register <--
```

If we add more of these we should explain them somewhere on the readme

**Comment by hzoo** [comment]
cc @xtuc 

If someone is new they might not include what 

```
{% include package_readme.html %}
```

does so I wonder if we should add like an html comment above all of these to point to the readme in the repo to edit it?

**Comment by xtuc** [comment]
I'm not sure if the implementers need to know where the README is expected to be.

We should tell them that if they implement package A, they need to specify `package: A` in the header.

Also if the repo isn't Babel, add the `from` parameter in the `include`.

Do you think this is clear enough ?

**Comment by hzoo** [comment]
Yeah just some way in general to let them know what's going on

**Comment by xtuc** [comment]
Since we documented this in the README, can we close this ?

**Comment by hzoo** [comment]
Yeah
