### ISSUE TITLE
Cleanup code snippets after 

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#1002]
![copy](https://cloud.githubusercontent.com/assets/588473/20567660/9c19adb4-b167-11e6-8b6e-6e295b3c6f28.gif)

cc @fredericmarx 

We merged https://github.com/babel/babel.github.io/pull/998 which adds a "copy" button to copy to clipboard for code snippets. We should look through to make sure everything is rendered correctly and the copied text makes more sense!

- [x] remove `$` for bash/cli commands since it will get copied. If we need to show that it is a command we should do something else.

`$ npm install --save-dev babel-cli`

- [ ] split up larger code snippets so it's more easily copiable
- [ ] make sure snippets are valid json/js/commands

**Comment by hzoo** [comment]
Also it think it for differentiating the snippets maybe we could add some css to the code frame to signify which language it is? (based on the css class `language-js`, etc)

<img width="708" alt="screen shot 2016-11-23 at 10 36 41 am" src="https://cloud.githubusercontent.com/assets/588473/20567974/cefeef40-b168-11e6-878d-dcad90d3d208.png">

@stefanpenner do you know how it's done for ember?

**Comment by xtuc** [comment]
I close this issue because I created an issue #1049 regarding the last comment.
