### ISSUE TITLE
Open in REPL button?

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#1017]
<img width="842" alt="screen shot 2016-12-03 at 11 35 08 pm" src="https://cloud.githubusercontent.com/assets/588473/20906508/6a954b6e-bb16-11e6-8578-d4d1fbd2f519.png">

---

We have the copy button via https://github.com/babel/babel.github.io/pull/998 now

I was wondering if we could label certain code snippets somehow and then also add a button that opens up a link to the repl with the code that was in the snippet?

Could make http://babeljs.io/docs/learn-es2015/ more interesting

**Comment by seedofjoy** [comment]
There are auto-save in REPL.

What behavior should be in this case (when user came from "open in repl" link): 
 - we overwrite previous save with new code
 - autosave disabled for this kind of links?
