### ISSUE TITLE
Create core-packages pages

### ISSUE THREAD

**Issue by xtuc** [babel/babel.github.io#1021]
Babel's core packages:

* [x] babel-core
* [x] babylon
* [ ] babel-traverse
* [ ] babel-generator
* [x] babel-types (#1009)
* [x] babel-register (#1026)
* [x] babel-template (#1026)
* [x] babel-helpers (#1026)
* [x] babel-code-frame (#1026)
* [x] Index page

All packages might not need a page on the website.

Documentations will be prefixed with `/docs/core-packages/`.

See #997 for more detail on implementations.

**Comment by nitin42** [comment]
Babylon is done. Right?
