### ISSUE TITLE
Make sure each plugin has an example

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#1023]
cc @existentialism 

everything in https://github.com/babel/babel.github.io/tree/master/docs/plugins

```
{% include package_readme.html %}
```

links to the readme in https://github.com/babel/babel/tree/master/packages such as https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-arrow-functions

Meaning make sure it has some kind of `in/out` example code + maybe a REPL link if it makes sense. Same with each option if it's helpful

We should also probably make sure the format of each readme is consistent (in/out, install, usage, options)

**Comment by lukyth** [comment]
I'm wondering what should we do if there's another information on a README in babel.github.io other than In/Out, Install, Usage, and Options. For example, there is References on [transform-object-rest-spread](https://github.com/babel/babel.github.io/blob/master/docs/plugins/transform-object-rest-spread.md), should we move that section into the [package's README](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-object-rest-spread) (like babel/babel#4930) or should we just leave it on the website?

**Comment by hzoo** [comment]
References should be included if possible yes! If it's a transform it could link to the spec, or if it's a proposal link to that

**Comment by nitin42** [comment]
babel/babel#5393
