### ISSUE TITLE
Provide a keyboard shortcut to get to the search box?

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#1027]
Not sure what the common shortcut would be (or if others do this). I know tab doesn't seem to move there because it's hidden by default anyway.

<img width="668" alt="screen shot 2016-12-03 at 8 30 54 am" src="https://cloud.githubusercontent.com/assets/588473/20859666/ed524d8a-b932-11e6-9761-c617c6854dc9.png">

**Comment by xtuc** [comment]
I suggest `/` or `?` (Vim bindings) :)

**Comment by hzoo** [comment]
Yeah maybe?`/`?

I know `?` is used to show the keyboard shortcuts UI for many sites

**Comment by xtuc** [comment]
I think we should also support a more common key: `f` or `s` for example.

In many cases `/` or `?` are already used.

**Comment by fleischie** [comment]
I can also add additional keys.

Will this be communicated in some way or another? It's potentially possible to open the search bar on any key and automatically start adding the typed key into the search input.

**Comment by raspo** [comment]
FWIW, Github uses `s` for search, I personally think that's a fine choice.

**Comment by fleischie** [comment]
@raspo Thanks for reminding me of this contribution. :smile: 

Yes, I updated my PR to include the `s` as a search button (extending the list of `/` and `?`).
