### ISSUE TITLE
Link core-packages page

### ISSUE THREAD

**Issue by xtuc** [babel/babel.github.io#1060]
Following #1026. We are missing a link to it.

The page is already online http://babeljs.io/docs/core-packages/.

We could add it in the docs dropdown?

![screenshot from 2016-12-08 09-08-27](https://cloud.githubusercontent.com/assets/1493671/21002397/e881cc80-bd25-11e6-8901-dad39b0d9eb9.png)

Or we could replace this page http://babeljs.io/docs/usage/api/ which has the same in it.

@hzoo @existentialism Any ideas?

**Comment by hzoo** [comment]
Ok do you want to just replace API with "Core Packages"?

**Comment by existentialism** [comment]
Not ideal, but until https://github.com/babel/babel.github.io/issues/1042 gets resolved, menu makes the most sense.

An interim solution, that we might want to consider, is grouping the items in the menu, with something like:

```
Setup
Editors
Caveats

-- Packages --
Core
Plugins
Polyfill

--- Usage --
.babelrc
CLI
babel-register
```

Bonus, we'll likely want to do similar groupings in the eventual side bar nav. Thoughts?

**Comment by hzoo** [comment]
Grouping sounds good
