### ISSUE TITLE
Docs: System.js / jspm usage

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel.github.io#107]
Moving from https://github.com/6to5/6to5/issues/636

ping @guybedford

**Comment by guybedford** [comment]
The setup for jspm is to choose `6to5` as the transpiler during init, or by running `jspm init -p`. It can also be enabled with `jspm dl-loader --6to5`.

For SystemJS the configuration is to set `System.config({ parser: '6to5', to5Options: {...} });`.

**Comment by codylindley** [comment]
This should be added to https://babeljs.io/docs/using-babel/ under "build systems".

**Comment by hzoo** [comment]
Do we still need to update https://github.com/babel/babel.github.io/tree/master/_includes/tools/jspm?

**Comment by guybedford** [comment]
This is in fine I guess. I will post a PR as well when jspm 0.17 is out as these instructions will change.
