### ISSUE TITLE
API docs don't state whether .babelrc configs are respected

### ISSUE THREAD

**Issue by callumlocke** [babel/babel.github.io#1077]
The [API docs page](https://babeljs.io/docs/usage/api/) doesn't answer this question: When using the `babel.transformFile` or `babel.transformFileSync` functions, does Babel respect configuration in `.babelrc`/`package.json`?

**Comment by xtuc** [comment]
Thanks for pointing out this. I made a PR babel/babel#5014 (it will be then published on the website).
