### ISSUE TITLE
[setup cli] Mixed references to presets

### ISSUE THREAD

**Issue by guzart** [babel/babel.github.io#1093]
In the [CLI setup section](https://babeljs.io/docs/setup/#installation) the paragraph says "To start, you can use the the **latest preset**, which enables...", however the code examples reference the "**env preset**".

The code example was changed in [commit cb24a8a1](https://github.com/babel/babel.github.io/commit/cb24a8a144df87e85cc6c55984ff0467eb3a4e03#diff-85ad37f4d4d62ce0f24ea8a26b95ba09L56), and the text in this [commit 618d9ef8](https://github.com/babel/babel.github.io/commit/618d9ef8a0b868aff1dc639db2c06e93879d3930#diff-85ad37f4d4d62ce0f24ea8a26b95ba09R49).

/cc @hzoo 

Thank you

**Comment by xtuc** [comment]
Thanks for pointing out this issue.
