### ISSUE TITLE
Update the homepage

### ISSUE THREAD

**Issue by xtuc** [babel/babel.github.io#1100]
We would like to change the homepage.

![screen shot 2016-12-06 at 4 51 59 pm](https://cloud.githubusercontent.com/assets/1493671/21365035/ba796834-c6f3-11e6-90a3-da6f0fe3ccf5.png)

Any ideas? :smiley:

**Comment by raspo** [comment]
A couple of things that come to mind:
- The white box around *"The State of Babel"* is not indicative of the fact that it is the title (and link) to the latest blog post.
- I am personally not a big fan of sharing buttons (github/slack) they add to the page load and duplicate the same information that can be found in the top-right section of the page.

**Comment by hzoo** [comment]
@raspo totally

I think I mentioned removing the social buttons or putting it in the footer and that the blog post section could just be removed. I wanted to just move the example or just repl as the first thing

**Comment by xtuc** [comment]
Wouldn't cool to have the REPL in the main page? Maybe a smaller version.

**Comment by xtuc** [comment]
[Preact's website](https://preactjs.com) is looking great!

**Comment by hzoo** [comment]
I think we can make a new issue for other stuff (we already fixed most of this if not all). Only thing left is the better repl on the home page that @existentialism made a mock of already
