### ISSUE TITLE
Link to React Getting Started page

### ISSUE THREAD

**Issue by gitanupam** [babel/babel.github.io#1109]
On this page (http://babeljs.io/docs/plugins/preset-react/#basic-setup-with-the-cli-), instead of linking to the React Getting Started page (https://facebook.github.io/react/docs/hello-world.html) which actually takes you to the Hello World example , this one (https://facebook.github.io/react/docs/installation.html) seems to be a better one to link to (as far as Babel is concerned).

**Comment by xtuc** [comment]
It is also the target page on the React homepage.

![react-p](https://cloud.githubusercontent.com/assets/1493671/21530828/c35f5d7c-cd43-11e6-9637-7a20010132a7.png)

**Comment by gitanupam** [comment]
Ok, I thought the intent to link to the React Getting Started page was more within the context of Babel and its installation with React etc. In that sense, I think [this](https://facebook.github.io/react/docs/installation.html) one is better. If the intent is for the user to just learn and know what is React, then the one that the React homepage [points to](https://facebook.github.io/react/docs/hello-world.html) is ok which starts with a Codepen example.

**Comment by xtuc** [comment]
Yes, could I close the issue?

**Comment by gitanupam** [comment]
Sure, just did.
