### ISSUE TITLE
transform-react-display-name documentation inconsistency

### ISSUE THREAD

**Issue by xtuc** [babel/babel.github.io#1111]
Doesn't look right, I think there is an inconsistency with the other README.

![screenshot from 2016-12-29 08-33-46](https://cloud.githubusercontent.com/assets/1493671/21538851/890a1046-cda1-11e6-8ad5-7f84148f735e.png)

[/docs/plugins/transform-react-display-name/](https://babeljs.io/docs/plugins/transform-react-display-name/)

**Comment by nitin42** [comment]
#1188
