### ISSUE TITLE
transform-react-jsx documentation inconsistency

### ISSUE THREAD

**Issue by xtuc** [babel/babel.github.io#1112]
Same as #1111. It isn't consistent with the other README.

![screenshot from 2016-12-29 08-34-48](https://cloud.githubusercontent.com/assets/1493671/21538875/b9dbe35c-cda1-11e6-845a-a45993ae5bf9.png)

[/docs/plugins/transform-react-jsx/](https://babeljs.io/docs/plugins/transform-react-jsx/)

**Comment by nitin42** [comment]
What you are saying is that the example should be more casual ? I mean a simple example like other plugins ?

**Comment by xtuc** [comment]
Sorry for the lack of explainations.

The others plugins have a description set in the header of the page. See https://github.com/babel/babel.github.io/blob/master/docs/plugins/minify-empty-function.md the description key.

In that case the description should be: "Turn JSX into React function calls".

**Comment by nitin42** [comment]
Same is the deal with other React plugins also!

**Comment by nitin42** [comment]
#1188
