### ISSUE TITLE
Open Source Hosting with Netlify

### ISSUE THREAD

**Issue by bdougie** [babel/babel.github.io#1114]
Hi, I am a fan of Babel and along with the rest of internet, been using the project for awhile. I work for [Netlify](https://www.netlify.com) by day, which is a host for front-end sites, including documentation sites like babel.github.io. 

Netlify has a very free plan [for all open source projects](https://www.netlify.com/open-source/) that provides great features, like [deploy previews](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/), and [smart redirects](https://www.netlify.com/docs/redirects/). If you have any interest in trying it doesn't require anything except connecting an open source repo.
 
Feel free to test it out [here](https://app.netlify.com/signup)

Let me know if you have any questions.

Cheers 🎉

**Comment by existentialism** [comment]
@bdougie thanks for reaching out! it's actually one of the items on my list of things to discuss/consider with the team! We'll reach out if/when we have any questions!
