### ISSUE TITLE
"In the browser" installation shows wrong code

### ISSUE THREAD

**Issue by dervondenbergen** [babel/babel.github.io#1127]
Hey,

When you click on **In the browser** on the [installation page](https://babeljs.io/docs/setup/#installation), you can see a code snippet under point 3 (usage).
The js file loaded in this snippet (`<script src="https://unpkg.com/babel-standalone@6/babel.min.js"></script>`) isn't working in Safari 10.0.2.
If I visit [babel/babel-standalone](https://github.com/babel/babel-standalone#usage) directly, there is another js file included in the usage example. This (`<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.18.1/babel.min.js"></script>`) one works.

I assume, the script tag in the browser [usage.md](https://github.com/babel/babel.github.io/blob/8316b402715c9c5a68d6ccdd4431f96ba45e7144/_includes/tools/browser/usage.md) file should be the same as from **[babel/babel-standalone](https://github.com/babel/babel-standalone#usage)**

I hope this makes sense, otherwise I'm happy to explain better 😁

**Comment by xtuc** [comment]
Is the second link working on Safari? Both links are correct.

**Comment by dervondenbergen** [comment]
I can't replicate it anymore 🤔 
Same code as before and just exchanged the script tag, but works now with both scripts.

**Comment by xtuc** [comment]
Ok cool :)

I close this issue.
