### ISSUE TITLE
Make lukehoban credit more obvious for the Learn ES6 page

### ISSUE THREAD

**Issue by kittens** [babel/babel.github.io#113]
@lukehoban isn't getting enough credit for his awesome [es6features](https://github.com/lukehoban/es6features) repo which is what the [Learn ES6](http://6to5.org/docs/learn-es6/) part of the 6to5 website is based on.

/cc @thejameskyle

**Comment by prathamesh-sonpatki** [comment]
Should this be closed based on https://monosnap.com/file/NzPhcDqp9LQLDpkOpBqWrbFWKt4A1g or something more? :smile:

**Comment by thejameskyle** [comment]
I forgot about this one. We should do something more since people link to that document all the time

**Comment by hzoo** [comment]
Added to title although we can probably do more here.
