### ISSUE TITLE
ES2015 transforms missing examples

### ISSUE THREAD

**Issue by xtuc** [babel/babel.github.io#1136]
Some pages are missing an example:
- [x] [ transform-es2015-template-literals ]( https://babeljs.io/docs/plugins/transform-es2015-template-literals/ )
- [x] [ transform-es2015-sticky-regex ]( https://babeljs.io/docs/plugins/transform-es2015-sticky-regex/ )
- [x] [ transform-es2015-spread ]( https://babeljs.io/docs/plugins/transform-es2015-spread/ )
- [x] [ transform-es2015-parameters ]( https://babeljs.io/docs/plugins/transform-es2015-parameters/ )
- [x] [ transform-es2015-object-super ]( https://babeljs.io/docs/plugins/transform-es2015-object-super/ )
- [x] [ transform-es2015-function-name ]( https://babeljs.io/docs/plugins/transform-es2015-function-name/ )
- [x] [ transform-es2015-for-of ]( https://babeljs.io/docs/plugins/transform-es2015-for-of/ )
- [x] [ transform-es2015-duplicate-keys ]( https://babeljs.io/docs/plugins/transform-es2015-duplicate-keys/ )
- [x] [ transform-es2015-destructuring ]( https://babeljs.io/docs/plugins/transform-es2015-destructuring/ )
- [x] [ check-es2015-constants ]( https://babeljs.io/docs/plugins/check-es2015-constants/ )
- [x] [ transform-es2015-computed-properties ]( https://babeljs.io/docs/plugins/transform-es2015-computed-properties/ )
- [x] [ transform-es2015-classes ]( https://babeljs.io/docs/plugins/transform-es2015-classes/ )
- [x] [ transform-es2015-block-scoping ]( https://babeljs.io/docs/plugins/transform-es2015-block-scoping/ )
- [x] [ transform-es2015-block-scoped-functions ]( https://babeljs.io/docs/plugins/transform-es2015-block-scoped-functions/ )

Note that to modify a page, use the "Edit this page" link (pages aren't stored in this repo)

**Comment by nitin42** [comment]
An example for `check-es2015-constants` is already given !

**Comment by nitin42** [comment]
` transform-es2015-duplicate-keys` is also done. Rest I covered. PR?

**Comment by xtuc** [comment]
@nitin42 

> An example for check-es2015-constants is already mentioned !

This page is already checked.

> Rest I covered

Yes in babel/babel#5393 ?

**Comment by nitin42** [comment]
Yes !

**Comment by zsoltime** [comment]
@nitin42 It seems you added examples to all of these. Or is there anything left for me? 😃

**Comment by nitin42** [comment]
I added examples for all of these ! 😄

**Comment by nitin42** [comment]
babel/babel#5393

**Comment by existentialism** [comment]
@nitin42 thanks!

**Comment by nitin42** [comment]
#1023
