### ISSUE TITLE
Homepage: add the REPL to the top

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#1144]
Anyone can help with this but @existentialism made a cool mock of it in photoshop already as well

![pasted image at 2017_01_13 02_11 pm](https://cloud.githubusercontent.com/assets/588473/22174975/91a8673c-dfb9-11e6-8888-da606b52a1e4.png)

(can fix the margins between the repl to be smaller)

**Comment by existentialism** [comment]
I'm lagging a bit, but actually almost done with sort of a working prototype, will post soon, but feedback/thoughts welcome for sure.

Initial idea is that it mimics typing a few examples to show their various transformed output, then will invite the user to experiment more with the full REPL.

**Comment by hzoo** [comment]
Actually we totally need some example dropdowns in the repl of syntax anyway
