### ISSUE TITLE
Try button shouldn't appear at every js code snippet

### ISSUE THREAD

**Issue by jddxf** [babel/babel.github.io#1145]
Currently, there's a try button along with every js code snippet.See http://babeljs.io/docs/plugins/transform-es2015-arrow-functions/#usage.
However, I believe only those we would copy to REPL should have a try button.

**Comment by xtuc** [comment]
We can't evaluate code examples with a `require` function for example.

![repl-error](https://cloud.githubusercontent.com/assets/1493671/22201657/d2385f44-e164-11e6-9024-ffcf9aee4b40.png)

Since we should mark each block of code in the website as 'triable' or not, I think that's not worth. What do you think?

**Comment by montogeek** [comment]
I asked myself the same question yesterday, expecting some output from any `import` example, there are probably thousands of code snippets that would need to be marked as _not runnable_ or _not REPL_, I am not sure if it is not worth update properly all snippets.

Why show a "Try" button if it is not valid?

**Comment by xtuc** [comment]
> Why show a "Try" button if it is not valid?

What do you mean by not valid?

Some code snippets are not runnable but you could still open them in the REPL.

**Comment by montogeek** [comment]
Sorry for the misunderstanding, not valid for the REPL, for example: http://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-0&experimental=true&loose=false&spec=false&playground=false&code=%2F%2F%20without%20options%0A%7B%0A%20%20%22plugins%22%3A%20%5B%22transform-es2015-arrow-functions%22%5D%0A%7D%0A%0A%2F%2F%20with%20options%0A%7B%0A%20%20%22plugins%22%3A%20%5B%0A%20%20%20%20%5B%22transform-es2015-arrow-functions%22%2C%20%7B%20%22spec%22%3A%20true%20%7D%5D%0A%20%20%5D%0A%7D%0A

**Comment by xtuc** [comment]
Yes absolutely. The code snippet has the wrong language. JSON code examples aren't runnable in the REPL.

Will be fixed, babel/babel#5194

**Comment by jddxf** [comment]
Thanks a lot.But that's not what I mean.
If I understand correctly, REPL is mostly for transforming code.If some code isn't intentional for transforming, e.g. https://babeljs.io/docs/plugins/transform-es2015-arrow-functions/#usage-via-node-api, I think a try button there is invalid.
Most 'triable' code snippets come from Learn ES2015 page and the example sections of plugin docs, e.g.https://babeljs.io/docs/plugins/transform-es2015-arrow-functions/#example.

**Comment by jddxf** [comment]
Also, there're some more places where json should be used instead of javascript. For example:
https://babeljs.io/docs/plugins/preset-env/
https://babeljs.io/docs/plugins/preset-env/#usage

**Comment by existentialism** [comment]
@montogeek @jddxf thanks for pointing out some areas we that should have marked as JSON! We fixed the ones mentioned, but please let us know if you run into any more :)

Would either of you be interested in sending a PR that filters out the JS code blocks in the Usage sections from getting a [REPL/Try button](https://github.com/babel/babel.github.io/blob/master/scripts/open-in-repl.js)?

**Comment by xtuc** [comment]
@jddxf Currently many example involving transformation plugins are supported. There is an issue about that #858.

I aggree with you but it would be unmaintenable to mark each code example as runnable or not.

**Comment by jddxf** [comment]
@existentialism Sorry for not having enough time.

@xtuc I have not digged into the codebase. You're probably right.
