### ISSUE TITLE
List contributors for each page

### ISSUE THREAD

**Issue by xtuc** [babel/babel.github.io#1149]
Webpack's website lists contributor at the bottom of each page.

![screenshot from 2017-01-24 17-28-46](https://cloud.githubusercontent.com/assets/1493671/22266413/373a701e-e280-11e6-9378-a0daf5324692.png)

The list of usernames is stored in the header of the page. Since we are publishing files from the babel/babel repo, how/where could we include this information?

**Comment by raspo** [comment]
Is this something we are interested in doing?

The list of contributors could be stored inside the front matter (like webpack.js.org does) of each page. We could run a one-time script that goes through all the `readme.md` for each package and add the users to the contributors front matter on this repo.

After that we should probably mention in the docs that if you want your name to show up in the contributors list, you need to edit the front matter of the doc page that is found on this repo (alternatively we could re-run the script every once in a while).

As to where to put this information, I think just above the **Community Discussion** section.

Thoughts?

**Comment by xtuc** [comment]
> how could we include this information 

I like the idea of a script (I guess Webpack does it manually). We need to fingure out how to run it when a doc PR was merged in babel/babel repo.

> where could we include this information

Sorry if it wasn't clear but I meant where to store the list of contributors. I think we could add this informations in the header of each pages (like the description).

> Is this something we are interested in doing?

It seems that most doc updates are done by the Babel team. I don't know if this is an interresting information. The idea was to invite people to collaborate at the documentation because they will show up in the website. What do you think?
