### ISSUE TITLE
Enforce linting style in js docs snippets

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#1150]
Ref from seeing https://github.com/babel/babel/pull/5214

Not sure how this would work but would be nice for the examples to be consistent with our code style via https://github.com/babel/eslint-config-babel.

I know there's https://github.com/eslint/eslint-plugin-markdown though so maybe that's all we need to do or if we just run it through prettier (not sure there's any integration for that yet).

**Comment by aaronang** [comment]
Isn't this done already in #1171?

**Comment by hzoo** [comment]
Yeah done now I believe, wasn't linked
