### ISSUE TITLE
Add a page for babel-preset-flow

### ISSUE THREAD

**Issue by existentialism** [babel/babel.github.io#1169]
We [recently added](https://github.com/babel/babel/blob/master/CHANGELOG.md#6230-2017-02-13) `babel-preset-flow` and should add a documentation page for it.

- [ ] Comment below you are going to do this (for others to know)
- [ ] Read [README.md](https://github.com/babel/babel.github.io/blob/master/README.md) to setup your local environment
- [ ] Update the submodule hash for babel (to get latest changes)
- [ ] Create `preset-flow.md` under `/docs/plugins` (see other presets an example)
- [ ] Run `jekyll serve` to test!

**Comment by xtuc** [comment]
Sorry, didn't know it was meant for beginners. Done in #1173.
