### ISSUE TITLE
Add new section for contributors

### ISSUE THREAD

**Issue by aaronang** [babel/babel.github.io#1179]
Lately, many people have joined the Slack channel and started to ask how to get started with contributing to Babel. Although we have a [`CONTRIBUTING.md`](https://github.com/babel/babel/blob/7.0/CONTRIBUTING.md) in the root of Babel, I think it would be more useful to have something similar to React's [contribution guide](https://facebook.github.io/react/contributing/how-to-contribute.html). The benefits in my opinion are as follows:

* More options to partition the contribution guide, e.g. have a single page for [codebase overview](https://facebook.github.io/react/contributing/codebase-overview.html).
* Better navigation, e.g. [sidebar navigation](http://babeljs.io/learn-es2015/#ecmascript-2015-features-arrows-and-lexical-this).
* Flexibility in styling by means of CSS.

Although the benefits may seem trivial, I think that navigation and style are an important factor to newcomers. My explanation of the benefits may not be convincing but my instinct just tells me that it will be great :grimacing:

I have thought about a structure and it looks as follows.

1. How to Contribute
   1. Code of Conduct
   1. How to Get in Touch
   1. Contribution Prerequisites
   1. Bugs
   1. Code Contributions 
1. Useful Resources
1. Terminology
1. Codebase Overview

Note that the structure may not be ideal and it is definitely something we should think through carefully. However, I do think that these sections are essential.

Let me know what you guys think.

P.S. For anyone that desires to contribute, documentation contributions are in my opinion a great way to start off contributing. As the creator of Babel mentioned, [documentation is **mega-important**](https://opensource.guide/how-to-contribute/#do-you-like-to-write). In addition, learning to explain concepts is a great way to test your knowledge.

**Comment by aaronang** [comment]
@existentialism Can't we just like React's `CONTRIBUTING.md` forward to the website? I totally agree that we should avoid duplication. Just wondering if importing/parsing the docs is the way to go, I think that it brings unnecessary complexity and limitations to writing/styling the docs. Can't we make the website like the central place of documentation and make everything redirect to the website? This is just a thought, wondering how others think about this.

**Comment by existentialism** [comment]
There's nothing that says we _MUST_ import the markdown from the repo. We can certainly create any number of pages with whatever custom layouts, styles, scripts, etc as needed to build an awesome section for contributors.

We should move the discussion to another issue as I don't think it has much impact on the improvements you've outline above... and I do think that `CONTRIBUTING.md` _should_ contain much, if not all, of that content/structure.

And while I don't necessarily agree with all of your other points, I do think that one larger meta task at hand is thinking about how the content on the site is organized, how that taxonomy scales, and its relationship to other content (GitHub READMEs, npmjs descriptions, etc).

Excited for your help and input on pushing it further, for sure!

**Comment by aaronang** [comment]
Closing this issue since it is somewhat a duplicate of #1099.
