### ISSUE TITLE
Add to Upgrade Guide for Babel 7

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#1209]
- template revision https://github.com/babel/babel/pull/5523
- useBuiltIns and useESModules https://github.com/babel/babel/pull/5481

**Comment by xtuc** [comment]
Since 'useBuiltIns and useESModules' is not a breaking change but a new feature, do you want it into the upgrade guide?

**Comment by xtuc** [comment]
Can we close that @hzoo ?
