### ISSUE TITLE
Custom plugins in REPL.

### ISSUE THREAD

**Issue by DylanPiercey** [babel/babel.github.io#1211]
I was just thinking it'd be pretty cool to extend the preset options to have a text input where you could put in whatever plugin you want (e.g.: babel-plugin-closure-elimination) and it would then try to download it from unpkg and enable it. To keep it simple it could just be a comma separated list of custom plugins.

This would make quickly trying a plugin trivial on the website.

**Comment by existentialism** [comment]
@DylanPiercey we agree! https://github.com/babel/babel.github.io/issues/858

Definitely something we'd love to do, but have been busy with other things. Would love help :P

**Comment by DylanPiercey** [comment]
Ah thanks for the link. I was looking through and I don't think it'd be to bad. Perhaps I'll give a shot if I get some free time next week.

**Comment by existentialism** [comment]
Awesome, looking forward to it!

**Comment by hzoo** [comment]
@DylanPiercey the issue I had with unpkg is that we would need to require plugins to do a umd build type thing unless we also run webpack on the fly

**Comment by DylanPiercey** [comment]
@hzoo what about switching to [wzrd](http://wzrd.in)? You can easily bundle things as a standalone UMD module. [Example](https://wzrd.in/standalone/set-dom@latest).

**Comment by hzoo** [comment]
Yeah we can do that, just can get kinda big, but if it works we can try!

**Comment by hzoo** [comment]
I think it will make a lot more sense with babel 7 since we got rid of babel-runtime for deps, and we have the polyfill to the repl

**Comment by DylanPiercey** [comment]
@hzoo I think the user would more/less expect it to take some time to fetch third party modules so I don't think it'd be too much of an issue.

Also with wzrd they have a '/multi' api which we could use in this case to bundle all of the presets together.

**Comment by hzoo** [comment]
Oh ok cool! I'm not that knowledge about wzrd but that sounds great - I *really* want this feature!

**Comment by DylanPiercey** [comment]
@hzoo could you point me to the place where the current presets are loaded?

**Comment by hzoo** [comment]
Messaged on slack, but https://github.com/babel/babel.github.io/blob/master/scripts/repl.js#L32, via babel-standalone
