### ISSUE TITLE
Change favicon for Babel

### ISSUE THREAD

**Issue by xtuc** [babel/babel.github.io#1230]
Currently `6to5` is still the favicon: 
![screenshot from 2017-04-13 19-02-51](https://cloud.githubusercontent.com/assets/1493671/25015383/d9a5d756-207b-11e7-92ae-23f83a329ad4.png)

Would be good to switch to a more 'Babel' favicon. Logo for Babel is [here](https://github.com/babel/logo).

**Comment by rajzshkr** [comment]
I'll work on this today.

**Comment by xtuc** [comment]
That's great, thanks.

We haven't thought much about what should be the new favicon.
We can maybe use the `B` letter from Babel. What do you think?

You can find the Babel logos [here](https://github.com/babel/logo).

**Comment by rajzshkr** [comment]
Yeah, I think that will be good.
