### ISSUE TITLE
Automate git submodules updating

### ISSUE THREAD

**Issue by xtuc** [babel/babel.github.io#1239]
Following discussion from #1238 and #1234.

The published documentation on the website is stored in babel/babel repo (which simplify maintenance). We are currently updating the git submodules manually each time Babel documentation files were updated.

Possible solutions:

- @babel-bot could push in this repository fresh submodules when documentation was updated in Babel/babel. In which branch should we push?

- Enable the solution above in babel/babel.github.io CI. We need to figure out how to build and publish the website through the CI (not travial when using Jekyll and gh-pages).

**Comment by Daniel15** [comment]
>  We need to figure out how to build and publish the website through the CI

What about moving from GitHub Pages to a more powerful host like Netlify? Then you can have a build script that does whatever you need, without having to hack around GitHub Pages' many limitations 😃

**Comment by Daniel15** [comment]
Is it just for the documentation? Instead of adding the entire Babel repo as a submodule, we could just pull the required Markdown files (eg. through their raw Github URLs). If we move the site to Netlify, we can do that as part of the build script. This is much more maintainable/scalable than hacking random things like auto-updating the Git submodules.

**Comment by Daniel15** [comment]
I'll try to take a look at this tonight and see how difficult it'd be to remove the usage of submodules where possible.

**Comment by hzoo** [comment]
yeah this was just for the readme and we wanted the version on master instead of npm since could be older, but ideally we would have versioned docs

**Comment by Daniel15** [comment]
Submitted a PR (#1293) to download the readmes from GitHub via their `raw.githubusercontent.com` URLs.  This adds around one second to the build time for the site, but we'll easily save several seconds by avoiding the submodule updates so it's still a net win.

**Comment by xtuc** [comment]
Thanks for your work @Daniel15!
