### ISSUE TITLE
Typing % corrupts localStorage cache

### ISSUE THREAD

**Issue by nhunzaker** [babel/babel.github.io#129]
[Previously filed here](https://github.com/6to5/6to5/issues/727#issuecomment-73439067)

After digging deeper into this, it looks like this is just a silly URI encoding issue translating between the URL bar and localStorage.

**Steps to reproduce:**

1. Visit https://6to5.org/repl
2. Clear localStorage (`for (var i in localStorage) localStorage.removeItem(i)`)
3. Set `%` as the code to transpile
4. Refresh the page
5. Notice "URI Malformed" in the developer console

In Chrome:

![bug](https://cloud.githubusercontent.com/assets/590904/6099250/97a4cdbc-afc1-11e4-9a6e-912ec40b2287.gif)

**Comment by nhunzaker** [comment]
Actually, any thing using `%`, such as a mod operation like `4 % 2` also makes it croak.

**Comment by prathamesh-sonpatki** [comment]
Not able to reproduce this issue http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=4%20%25%202

**Comment by nhunzaker** [comment]
Looks to be the case for me too. All good here.
