### ISSUE TITLE
Print dialog pops up in REPL

### ISSUE THREAD

**Issue by iamolivinius** [babel/babel.github.io#143]
Not sure if it's a bug or a feature but when i paste the following code into the REPL page the print dialog pops up several times.

Code taken from: https://github.com/lukehoban/es6features#generators

```
var fibonacci = {
  [Symbol.iterator]: function*() {
    var pre = 0, cur = 1;
    for (;;) {
      var temp = pre;
      pre = cur;
      cur += temp;
      yield cur;
    }
  }
}

for (var n of fibonacci) {
  // truncate the sequence at 1000
  if (n > 1000)
    break;
  print(n);
}
```

This occures in Chrome as well as in Firefox on a Linux PC

**Comment by sebmck** [comment]
The `print(n);` is causing it to open the print dialog, should be `console.log`.

**Comment by iamolivinius** [comment]
Obviously :+1: 

Let's hope there're willing to make their examples more safe for sleep drunken people like me.
https://github.com/lukehoban/es6features/pull/57
