### ISSUE TITLE
https://babeljs.io/ does not work, but http://babeljs.io/ does

### ISSUE THREAD

**Issue by darcyparker** [babel/babel.github.io#144]
The URL https://babeljs.io/ is listed as https on https://github.com/babel/babel and https://github.com/babel/babel.github.io etc... but https version of URL doesn't work.

http://babeljs.io/ loads fine.

I get this message when I use the https URL.
```
Secure Connection Failed

An error occurred during a connection to babeljs.io. The server rejected the handshake because the client downgraded to a lower TLS version than the server supports. (Error code: ssl_error_inappropriate_fallback_alert)

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Comment by thejameskyle** [comment]
What version of firefox are you using?

**Comment by darcyparker** [comment]
Firefox 35.0.1 and Chrome Version 40.0.2214.111 m have the issue for me.

Maybe just update your the URLs in  https://github.com/babel/babel etc... to point to http://babeljs.io/

**Comment by thejameskyle** [comment]
I'm not experiencing this in either browser

**Comment by darcyparker** [comment]
hmm... maybe my IT is aggressively blocking certain https urls.

**Comment by darcyparker-ptc** [comment]
An FYI for others who may have this. My company had a problem with its proxy server (hidden to me) that was causing the issue.
