### ISSUE TITLE
Link to the FAQ from the Transformers page doesn't jump the the anchor

### ISSUE THREAD

**Issue by hawkrives** [babel/babel.github.io#149]
It links to the "What is a transformer?" heading, by way of <https://babeljs.io/docs/faq#what-is-a-transformer->, but the FAQ page performs a redirect from `/docs/faq` to `/docs/faq/`, and appears to drop the anchor in the process.

Could you either link to the redirected page or not drop the anchor while redirecting? I'm not sure how feasible the second is; it might be happening at the browser level.

(Oh, this is Safari 8.0.3 on OS X 10.10.2.)

**Comment by sebmck** [comment]
Not really a way to retain it since all the redirects happen clientside since the babel site is entirely static.

**Comment by hawkrives** [comment]
Fun times. Thanks!
