### ISSUE TITLE
Replace the external helpers page with a babel-runtime page

### ISSUE THREAD

**Issue by thetalecrafter** [babel/babel.github.io#150]
As using `self-contained` and `babel-runtime` is the preferred way to handle deduplicating helpers, and using `external-helpers` is more of a niche case or implementation detail of `self-contained`, it would be good to have an item in the "Docs" navigation for "Runtime" instead of "External helpers".

Currently the `self-contained` and `babel-runtime` information is buried in the "Transformers" page, and "External helpers" has a dedicated page in the main navigation.

**Comment by sebmck** [comment]
I've split it up into a separate page, I'll need to spend some time thickening and cleaning it up though. PRs from anyone appreciated!

**Comment by sebmck** [comment]
I renamed the `selfContained` transformer to `runtime` to align with the `babel-runtime` module that it depends on.

The phrasing could be improved and the language as it isn't super noob-friendly but it gets the job done. I'll try and improve it when I get the time as it's pretty technical.
