### ISSUE TITLE
https://babeljs.io/repl/   ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by allan-simon** [babel/babel.github.io#151]
When I go on  the "try it out" page I got the error  

```
ReferenceError: $ is not defined
```

making the page unusable.

**Comment by sebmck** [comment]
Browser, OS etc?

**Comment by allan-simon** [comment]
sure, 

Linux Ubuntu ,  Firefox 35.0

**Comment by sebmck** [comment]
Possible Cloudflare issue since the only reason `$` would be undefined is if jQuery didn't load. /cc @thejameskyle

**Comment by allan-simon** [comment]
interesting enough,  I don't see the javascript being load in the network panel
and if i try to open directly   

https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js

(which is in the html source) It opens correctly

**Comment by thejameskyle** [comment]
I don't see why this would be a cloudflare issue. These are pointing to cdnjs so you'd be noticing issues with a lot of sites if that were the case. I'll try out my Ubuntu VM

**Comment by sebmck** [comment]
@thejameskyle Just a stab in the dark since that's the only thing I can think of.

**Comment by thejameskyle** [comment]
I'm not seeing any issues 
![screen shot 2015-02-21 at 11 22 53 pm](https://cloud.githubusercontent.com/assets/952783/6317808/abd877ac-ba20-11e4-9ec3-58755b6ee58c.png)

**Comment by allan-simon** [comment]
indeed it's weird, certainly a bug on my side, I've refreshed the cache, shutdown my VPN, and now it works correctly.

**Comment by thejameskyle** [comment]
Out of interest, what VPN do you use?

**Comment by allan-simon** [comment]
Astrill
