### ISSUE TITLE
add documentation about the flow type checker

### ISSUE THREAD

**Issue by allan-simon** [babel/babel.github.io#152]
The documentation should explain how to use  type and the flow type checker  see https://github.com/babel/babel/issues/86

**Comment by chocolateboy** [comment]
Typo fixlet: see babel/babel#862.

**Comment by prathamesh-sonpatki** [comment]
There is some documentation about Flow here http://babeljs.io/docs/advanced/transformers/other/flow/.

**Comment by prathamesh-sonpatki** [comment]
@thejameskyle I think http://babeljs.io/docs/advanced/transformers/other/flow/ is under transformers and hard to find. Should a section be added under `Usage` similar to `JSX`?

**Comment by hzoo** [comment]
Transform is at http://babeljs.io/docs/plugins/transform-flow-strip-types/ now - are you suggesting we link to the flow website? I guess we can give a notice that it only strip flow types (which is clear from the plugin name)
