### ISSUE TITLE
REPL: Run code within iframe

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel.github.io#161]
Creating and destroying an iframe for each code execution will help guard against problems such as async functions that don't complete before the next code execution.

**Comment by kaaaahhhhnnnn** [comment]
+1 for cases like:

```js
Object.defineProperty(Element.prototype, 'foo', {
  enumerable: true,
  get: function(){}
});
```

not throwing an error on every keystroke

**Comment by benjamingr** [comment]
Note the REPL also currently breaks in some other cases, like: https://github.com/babel/babel/issues/2485
