### ISSUE TITLE
Better inspect/format

### ISSUE THREAD

**Issue by kittens** [babel/babel.github.io#172]
Via @getify babel/babel#968

> This code doesn't appear to output correctly in babel's REPL:
> 
> ```js
> var s = Symbol("foo");
> 
> var x = {
>   [s]: 42
> };
> 
> console.log( Object.getOwnPropertySymbols(x) );
> // [ null ]
> ```
> 
> Apparently it's because the output is using `JSON.stringify(..)`, which of course cannot represent symbols.
> 
> Can we get an option (another lovely checkbox) to have `console.log(..)` output shown in the REPL raw without this transformation?

**Comment by thejameskyle** [comment]
Threw this together: http://jsbin.com/xenaqu/1/edit?js,console, need to work on it some more.
