### ISSUE TITLE
New User: BoomTown

### ISSUE THREAD

**Issue by mfunkie** [babel/babel.github.io#186]
- Name: BoomTown
- Homepage url: http://www.boomtownroi.com
- Brand Guidelines/Licensing: N/A
- Logo: https://static.boomtownroi.com/img/logos/logo-boomtown.svg

**Comment by mfunkie** [comment]
It looks like we were removed from this page.  Is there a specific reason?

**Comment by sebmck** [comment]
@mfunkie You're still there in [`_data/users.yml`](https://github.com/babel/babel.github.io/blob/master/_data/users.yml#L97-99). Might be a layout issue. I'll look into it.

**Comment by mfunkie** [comment]
It looks like it was overwritten by the Autoprefixer svg in the commit https://github.com/babel/babel.github.io/commit/8a25082fa4f10acfcca77ca486edfb8a31baeefa

**Comment by sebmck** [comment]
Oh jeez @thejameskyle, you replaced the BoomTown logo with the Autoprefixer one.

**Comment by sebmck** [comment]
Fixed via 770d450049642be10d1a9c6badbb3f73df6dccb3, sorry about that.

**Comment by mfunkie** [comment]
No worries, thank you so much for being so responsive!

**Comment by thejameskyle** [comment]
Sorry, my bad!
