### ISSUE TITLE
Move script files to end of <body>

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel.github.io#19]

**Comment by peterblazejewicz** [comment]
@thejameskyle may I do this (and similar) taks(s)?

**Comment by thejameskyle** [comment]
Sure, go ahead

**Comment by prathamesh-sonpatki** [comment]
@peterblazejewicz Are you still working on this? I would love to take a stab otherwise :)

**Comment by peterblazejewicz** [comment]
@prathamesh-sonpatki 
No, it was at dead-end as we couldn't (then) implement per-page assets.
I'd close this one and can help you with your PR if required.
Thanks!
