### ISSUE TITLE
Broken link on FAQ page

### ISSUE THREAD

**Issue by levithomason** [babel/babel.github.io#191]
> ### Feature-rich
>
>As you can tell by the [comparison page](https://babeljs.io/docs/compare#comparison-to-other-transpilers),  babel featureset is...

The link to the *comparison page* `https://babeljs.io/docs/compare#comparison-to-other-transpilers` goes to a 404 page.  I can't find the comparison page in this repo to suggest the correct link.

I would like to see this chart though :)

**Comment by arthurvr** [comment]
It was removed in https://github.com/babel/babel.github.io/commit/dad12fd4da4c029da9a5749e0ebb389eece5943c.

**Comment by levithomason** [comment]
Just saw this, tx!

**Comment by levithomason** [comment]
Suppose the FAQ page needs updated still.
