### ISSUE TITLE
New User: [Codecademy]

### ISSUE THREAD

**Issue by bonniee** [babel/babel.github.io#196]
- Name: Codecademy
- Homepage url: http://www.codecademy.com
- Brand Guidelines/Licensing: n/a
- Logo: http://www.codecademy.com/files/codecademy-press-kit.zip

**Comment by thejameskyle** [comment]
Resolved by https://github.com/babel/babel.github.io/commit/8c496662e12e33639918f2e05b67566cdb67a72a.
