### ISSUE TITLE
Object destructuring requires using var or let?

### ISSUE THREAD

**Issue by cesarandreu** [babel/babel.github.io#197]
I just found out that although you can use already defined variables with array destructuring, you can't with object destructuring.

**Try it out** ([link](https://babeljs.io/repl/#?experimental=true&playground=false&evaluate=true&loose=false&spec=false&code=%2F%2F%20valid%0Avar%20a%20%3D%201%2C%20b%20%3D%202%3B%0A%5Ba%2C%20b%5D%20%3D%20%5Bb%2C%20a%5D%3B%0A%0A%2F%2F%20invalid%0Avar%20c%2C%20d%20%3D%20%7Bc%3A%201%7D%3B%0A%7Bc%7D%20%3D%20d%3B%0A))
```js
// valid
var a = 1, b = 2;
[a, b] = [b, a];

// invalid
var c, d = {c: 1};
{c} = d;
```

Is this correct behavior or is it a bug?

If it's not a bug, maybe it would make sense to mention it in the destructuring example in the Learn ES6 page. Maybe if there's enough gotchas, have an extra page/section to mentions some of them. Thoughts?

**Comment by sebmck** [comment]
This is expected behaviour. See babel/babel#1023 for an explanation.

**Comment by cesarandreu** [comment]
Thanks!
