### ISSUE TITLE
Users: update Harmonic logo

### ISSUE THREAD

**Issue by UltCombo** [babel/babel.github.io#201]
Harmonic has a new logo:

<img src="https://cdn.rawgit.com/es6rocks/harmonic/e391ae462f3b047848f1783315de9edab019e197/harmonic-logo.svg" width="450">

- Licensing: MIT
- Brand Guidelines: Feel free to resize. Don't change the aspect ratio, don't change colors, don't add/remove/modify visual elements, don't crop.
- Logo: https://cdn.rawgit.com/es6rocks/harmonic/e391ae462f3b047848f1783315de9edab019e197/harmonic-logo.svg

The project name and URL have not changed.

**Comment by UltCombo** [comment]
Should I just send a PR instead?

**Comment by thejameskyle** [comment]
Oh sorry, I'll do that now

**Comment by thejameskyle** [comment]
There we are. Sorry I missed this one.

**Comment by UltCombo** [comment]
No problem, thanks! :smile:
