### ISSUE TITLE
New User: lodash (es branch)

### ISSUE THREAD

**Issue by jdalton** [babel/babel.github.io#203]
- Name: lodash
- Homepage url: https://lodash.com, specifically https://github.com/lodash/lodash/tree/es
- Brand Guidelines/Licensing: MIT
- Logo: https://lodash.com/icon.svg

**Comment by UltCombo** [comment]
Nice!

ping @thejameskyle

**Comment by thejameskyle** [comment]
Yeah, I need to wait until I have an actual application to edit SVG because this gets all kinds of messed up.

**Comment by UltCombo** [comment]
@thejameskyle what gets messed up? Resizing?

**Comment by thejameskyle** [comment]
Never mind, looked at it again and I'm not sure what was wrong before
