### ISSUE TITLE
New User: Front End TV

### ISSUE THREAD

**Issue by trevordmiller** [babel/babel.github.io#212]
- Name: Front End TV
- Homepage url: http://www.frontend.tv
- Brand Guidelines/Licensing: just don't distort or alter it and give it a bit o' padding like you've done with the other logos ;)
- Logo: http://www.frontend.tv/public/dist/images/logo.png. I have SVGs and other layouts as well - if you need them, just let me know.

Thanks!

**Comment by thejameskyle** [comment]
Would you mind getting an SVG if you have one? There's a lot of images on the page and every byte saved counts.

**Comment by trevordmiller** [comment]
@thejameskyle No prob: http://www.frontend.tv/public/dist/images/logo.svg. Thanks man.
