### ISSUE TITLE
New User: reddit

### ISSUE THREAD

**Issue by btholt** [babel/babel.github.io#217]
Please fill the following out:

- Name: reddit
- Homepage url: https://www.reddit.com
- Brand Guidelines/Licensing: https://www.reddit.com/about/alien/
- Logo: https://www.redditstatic.com/about/assets/reddit-logo.svg

**Comment by thejameskyle** [comment]
![](http://www.reactiongifs.com/r/2013/01/fangirling.gif)

**Comment by thejameskyle** [comment]
I'm having issues resizing this image because the "I" is a text stroke, would you mind going in and updating that to normal shapes. I can also just use the png.

**Comment by thejameskyle** [comment]
We size everything to fit within the bounds of a 500x200 image so that everything on the page stays consistent.

**Comment by btholt** [comment]
:smile: Thanks.
