### ISSUE TITLE
es6-features.org, based on Luke Hoban's snippets, plus ES5 equivalents to show contrast

### ISSUE THREAD

**Issue by rse** [babel/babel.github.io#220]
On your page "docs/learn-es6.md" you reference Luke Hoban's great ES6 snippets. I've taken this one step further and extended this snippet collection to show also rough ES5 equivalents (so people even better see the benefits of ES6) and generated a website out of the snippets under http://es6-features.org/ which allows one to easily navigate, switch on/off semicolon style, etc. And, of course, it directs people also to your awesome Babel website (see links at the bottom right corner). In case you find this useful, I would be glad if you would also reference http://es6-features.org/ on your website. Thanks.

**Comment by sebmck** [comment]
Your "_modernized_" examples have their semicolons incorrectly stripped from `for` loops.

**Comment by rse** [comment]
Will be fixed. Thanks for the hint.

**Comment by rse** [comment]
Now fixed.

**Comment by thejameskyle** [comment]
I'm working on a new resources page on the Babel website, I'll keep this one in mind. Thanks!
