### ISSUE TITLE
New User: Video.js

### ISSUE THREAD

**Issue by heff** [babel/babel.github.io#223]
- Name: Video.js
- Homepage url: http://www.videojs.com
- Brand Guidelines/Licensing: nope
- Logo: https://www.dropbox.com/s/ig20v6s2q0wnyaz/videojs-logo-for-babel.png?dl=0

**Comment by thejameskyle** [comment]
Do you have anything higher resolution than that?

**Comment by heff** [comment]
Sorry, yeah. Thought I was being helpful by making it 500x200.
https://www.dropbox.com/s/jx3pylib5op0lpa/videojs-logo-for-babel2.png?dl=0

**Comment by heff** [comment]
Thanks!
