### ISSUE TITLE
New User: Trapit

### ISSUE THREAD

**Issue by thomasloh** [babel/babel.github.io#228]
Please fill the following out:

- Name: Trapit
- Homepage url: http://trap.it/
- Brand Guidelines/Licensing: http://trap.it/press-media
- Logo: http://trap.it/images/media/trapitlogo_color_darkbg.png

**Comment by thejameskyle** [comment]
Do you have a version of the logo with a transparent background that's meant for a light background?

**Comment by thomasloh** [comment]
@thejameskyle Yes, will this work? http://trap.it/images/media/trapitlogo_transparentbg.png

**Comment by thejameskyle** [comment]
Thank you!
