### ISSUE TITLE
New User: Sprout Social

### ISSUE THREAD

**Issue by arlodesign** [babel/babel.github.io#230]
Please fill the following out:

- Name: Sprout Social
- Homepage url: http://sproutsocial.com
- Brand Guidelines/Licensing: None you need to worry about
- Logo: http://f.cl.ly/items/3W081W1w3m3K3X3B3w3N/sproutsocial_500px.svg

**Comment by thejameskyle** [comment]
omg you sized it the right way and everything :heart:

**Comment by thejameskyle** [comment]
Thanks a ton!

**Comment by arlodesign** [comment]
No, thank you!
