### ISSUE TITLE
New User: Evernote

### ISSUE THREAD

**Issue by iafan** [babel/babel.github.io#235]
- Name: Evernote
- Homepage url: https://evernote.com/
- Brand Guidelines/Licensing: https://evernote.com/trademark/ and https://evernote.com/media/pdf/evernote_quick_brand_guidelines.pdf
- Logo: https://www.dropbox.com/s/9b6fcpztl218su1/Evernote_logo_horizontal.svg?dl=1

**Comment by thejameskyle** [comment]
Thanks!
