### ISSUE TITLE
New User: EveryDollar

### ISSUE THREAD

**Issue by elijahmanor** [babel/babel.github.io#237]
- Name: EveryDollar
- Homepage url: https://www.everydollar.com
- Brand Guidelines/Licensing: N/A
- Logo: https://www.everydollar.com/images/logo/horizontal.svg

**Comment by thejameskyle** [comment]
I'm having a lot of trouble with this logo. The svg seems to render weird in every app I open it in:

<img src="https://cloud.githubusercontent.com/assets/952783/7343776/8bf4f7b2-ec7a-11e4-9e86-677185384721.png" height="200">

Could you try re-exporting it differently, or simply resize it into a 500x200 image? e.g. 

<img src="https://cloud.githubusercontent.com/assets/952783/7343900/c99305c2-ec7b-11e4-9982-83d17a691586.png" width="275">

**Comment by thejameskyle** [comment]
ping

**Comment by elijahmanor** [comment]
Yes, I'll get on this tomorrow when I get into the office. Thanks!

**Comment by elijahmanor** [comment]
@thejameskyle how about this one? seems to work better in sketch and in the browser. https://dl.dropboxusercontent.com/u/200135/everydollar/everydollar_horizontal_logo.svg

thanks, and i appreciate your work!

**Comment by thejameskyle** [comment]
Thanks!
