### ISSUE TITLE
cli options have changed, docs need update for source maps

### ISSUE THREAD

**Issue by jeffbski** [babel/babel.github.io#241]
Apparently the CLI options have changed so

https://babeljs.io/docs/usage/cli/

needs to be updated. I don't know of all the recent changes, but I know that -t is no longer the way to get inline source maps which is now -s inline. There may be other changes too?

**Comment by sebmck** [comment]
Fixed via 44108a03dc13182d131661dc7c1f2cbe10d7363a.
