### ISSUE TITLE
New User: PowerReviews

### ISSUE THREAD

**Issue by andyhass-pr** [babel/babel.github.io#243]
- Name: PowerReviews
- Homepage url: http://www.powerreviews.com
- Brand Guidelines/Licensing:  Nothing important!
- Logo: http://www.powerreviews.com/wp-content/uploads/2015/04/PowerReviews_logo_RGB.png

We're now serving Babelified ES6 code in front of 250m users a month.  Thanks, guys!

**Comment by thejameskyle** [comment]
> Brand Guidelines/Licensing: Nothing important!

I need to know even the unimportant things

**Comment by andyhass-pr** [comment]
Hey @thejameskyle,

By nothing important, I actually mean "nothing" - we have no brand licensing policy at the moment.  Should that change sometime in the future, I'll let you know.  

Is there anything else you need?

**Comment by thejameskyle** [comment]
That's fine, just need clarity
