### ISSUE TITLE
Clarify usage of "only" option

### ISSUE THREAD

**Issue by IanVS** [babel/babel.github.io#246]
According to https://github.com/babel/babel/issues/1306#issuecomment-94341372 there are a lot of ways that the "only" option can be used:

> It can take an array of globs, a single regex, a single string glob or an array of regexs.

It would be great it the documentation could be a little more clear on this.  As-is, the documentation tells partial stories in different places.  The [options docs](https://babeljs.io/docs/usage/options/) currently state that the `only` option takes an array of globs:

> An array of glob paths to **only** compile. When attempting to compile a non-matching file it's returned verbatim.

But the [require usage](https://babeljs.io/docs/usage/require/) only mentions regex.  

> // Optional only regex - if any filenames don't match this regex then they
// aren't compiled
only: /my_es6_folder/,

**Comment by greim** [comment]
The docs are indeed confusing; I've taken to using this really ugly hack until the day I finally understand how this thing works:

```js
var patt = /.*/
patt.test = function(path){
  var isMatch = /* do some logic here on "path" */
  return isMatch
}
require('babel').register({
  ignore: patt
})
```
