### ISSUE TITLE
Blog Post: Top 10 reasons to use 6to5 

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel.github.io#25]
I've been asked for something like this by a few people now.

**Comment by xfq** [comment]
Here are my reasons:

1. I can start using ES2015+ code today without waiting for browser support.
2. There is no runtime dependency.
3. Babel is available everywhere: Node.js, Meteor, Rails, Grunt, Gulp...
4. Babel (and JavaScript/ECMAScript) is constantly evolving.
5. The output is readable.
6. Every transformation can be turned off.
7. Babel has a REPL.
8. Babel supports JSX and React.
9. The level of ES2015+ support is ahead of most (if not all) of the alternatives.
10. The documentation is fantastic.

(Moreover, corporations such as Netflix, Yahoo!, PayPal, and SoundCloud are using Babel now.)

**Comment by AngeIII** [comment]
What is a browser support for babeljs? I mean if I compile my code is it will work for example in ie9?
