### ISSUE TITLE
New User: Alianza Inc.

### ISSUE THREAD

**Issue by kentcdodds** [babel/babel.github.io#250]
- Name: Alianza Inc.
- Homepage url: http://www.alianza.com/
- Brand Guidelines/Licensing: I received written permission from the CTO. Let me know if you need anything more than that.
- Logo: https://cloud.githubusercontent.com/assets/1500684/7282463/64916196-e8ed-11e4-98ea-fdfa0cd24236.png

![alianza](https://cloud.githubusercontent.com/assets/1500684/7282463/64916196-e8ed-11e4-98ea-fdfa0cd24236.png)

**Comment by siggysamson** [comment]
@sebmck Is there any policy on which users to add to the users list? I could add a pull request for this issue and also work on similar onces: #249, #243, #237. Or do you want to discuss every user independently from each other?

**Comment by thejameskyle** [comment]
Hi @siggysamson, we'll add any user as long as the licensing is okay. I review every user submission for proper licensing and ensure we follow any brand guidelines. I also make sure they are formatted and optimized properly. It's not too much work for me, but I let them build up a little bit so I can do them all at once.

I want to make sure we don't ever get in trouble for this so I'd prefer staying in charge of it, thanks for the offer though! There's certainly a lot of other issues in this repo that could use attention if you want to grab one.

**Comment by thejameskyle** [comment]
> Brand Guidelines/Licensing: I received written permission from the CTO. Let me know if you need anything more than that.

@kentcdodds If written permission is necessary could you please have them email it to babel@babeljs.io?

**Comment by kentcdodds** [comment]
Written permission is not necessary :-)

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)
