### ISSUE TITLE
Improve build process

### ISSUE THREAD

**Issue by dignifiedquire** [babel/babel.github.io#258]
I was just looking at the source, and thought wouldn't it be nice to use something like webpack + npm dependencies to handle the JavaScript based dependencies, as well as being able to write the scripts for the site in es6 using babel. 
Would you be up for a PR that implements this?

**Comment by thejameskyle** [comment]
I don't know if it's really necessary at this point. I don't want to use webpack either.

**Comment by sebmck** [comment]
Beauty of the build pipeline now is that we can just push to GitHub pages and it automatically builds it with Jekyll.

**Comment by jmm** [comment]
@thejameskyle @sebmck How do you build and preview this site locally?

**Comment by sebmck** [comment]
It's just a basic Jekyll site. Setup commands are something like:

``sh
$ # install ruby
$ gem install bundler # if ruby hasn't been installed
$ bundle install # if you haven't already
$ gem install jekyll-redirect-from
$ jekyll s
```

**Comment by jmm** [comment]
@sebmck Ok, thanks. I've never built a Jekyll site before.

**Comment by jmm** [comment]
@sebmck What does this mean?:
> `# if ruby hasn't been installed`

Isn't the premise that ruby is installed when running?:
```sh
$ gem install bundler
```

When I ran:
```sh
$ bundle install
```

I got:
```
Could not locate Gemfile or .bundle/ directory
```

When I run:
```sh
$ jekyll s
```

I get various crashes that I have no idea how to debug, e.g.:

```
      Generating...
*** glibc detected *** ruby /home/jesse/.rvm/gems/ruby-2.2.1/bin/jekyll s: free(): invalid pointer: 0x00000000028c1690 ***
<...many lines>
Aborted (core dumped)
```

**Comment by thejameskyle** [comment]
You might want to make sure you have all of the same versions of gems that GitHub Pages uses https://pages.github.com/versions/

**Comment by jmm** [comment]
@thejameskyle Thanks, I tried following the instructions there (including installing `github-pages` gem) and no dice. Sometimes it's the message I posted earlier, sometimes it's this:

```
/somedir/.rvm/gems/ruby-2.2.1/gems/liquid-2.6.2/lib/liquid/variable.rb:28: [BUG] Segmentation fault at 0x00000000000000
```
And then hangs at:
```
-- C level backtrace information -------------------------------------------
```

**Comment by hzoo** [comment]
I don't think we will change the build anytime soon right? I think we can update the instructions on how to run it locally though.
