### ISSUE TITLE
Blog Post: Using 6to5 with JSX/Flow 

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel.github.io#26]

**Comment by tbassetto** [comment]
I am using `browserify` and `6to5` (via `6to5ify`) to build a React.js app. I am using the JSX syntax as well as `Class`, `const`, `let`, array destructuring,  etc.

All was running fine until I tried to add [Facebook flow](https://github.com/facebook/flow) to my setup and suddendly it's a nightmare :) Is this blog post almost ready?

`flow` is mainly complaining about the use of `const`:

> Unsupported variable declaration: const

What is the state of flow support in 6to5 exactly? 6to5 reads annotations and interprets them during compilation? Then `flow check` should be run only on the compiled file?

Thanks!

**Comment by thejameskyle** [comment]
@tbassetto It's better to ask questions like this in the [gitter room](https://gitter.im/6to5/6to5)
