### ISSUE TITLE
New User: npm

### ISSUE THREAD

**Issue by zeke** [babel/babel.github.io#266]
Please fill the following out:

- Name: npm
- Homepage url: https://www.npmjs.com
- Brand Guidelines/Licensing: https://www.npmjs.com/policies/trademark#why-npm-inc-has-a-trademark-policy
- Logo: https://www.npmjs.com/static/images/npm-logo.svg

Note: `npm` is always lowercase.

**Comment by thejameskyle** [comment]
Woot! Thanks @zeke @seldo
