### ISSUE TITLE
New User: Keymetrics

### ISSUE THREAD

**Issue by Unitech** [babel/babel.github.io#272]
- Name: Keymetrics
- Homepage url: https://keymetrics.io
- Brand Guidelines/Licensing: N/A
- Logo: http://s10.postimg.org/o2n8kg0s9/keymetrics.png

**Comment by thejameskyle** [comment]
Can you give a version of this logo without the white background?

**Comment by gsvolt** [comment]
@thejameskyle PR 477 fixes this issue. Feedback welcome.

Cheers!
