### ISSUE TITLE
New User: React

### ISSUE THREAD

**Issue by zpao** [babel/babel.github.io#275]
Please fill the following out:

- Name: React
- Homepage url: https://facebook.github.io/react/
- Logo: https://facebook.github.io/react/img/logo.svg

**Comment by thejameskyle** [comment]
Oh. Shit.

**Comment by thejameskyle** [comment]
Do you have anything for a white background?

**Comment by thejameskyle** [comment]
Also, I need any licensing information, even if it's just "N/A".

**Comment by zpao** [comment]
I have a transparent one around here somewhere, or can put it on white. And licensing is N/A (unless things have changed without anybody telling me).

**Comment by zpao** [comment]
Oh right, SVG is just text and I can edit that color :) Here it is on white. https://gist.github.com/zpao/97e8dc4f0f6d7c49c016

**Comment by spicyj** [comment]
Here's a transparent one that doesn't use strokes:

https://gist.github.com/spicyj/56355eebc80137c8e1e2
