### ISSUE TITLE
Docs: Improve Babelrc page

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel.github.io#279]
This is kinda weak right now http://babeljs.io/docs/usage/babelrc/

**Comment by thomasfoster96** [comment]
Has anyone made any progress on this? I'd be happy to flesh the page out a bit and make it a bit easier to understand for people without a great deal of experience in babel or .***rc files.

**Comment by thejameskyle** [comment]
There's a lot more content there now, but feel free to add more that you feel is necessary.

**Comment by atilkan** [comment]
@thejameskyle People don't know the options to add.

**Comment by johan** [comment]
Example of what the `.babelrc` page doesn't describe: is it possible to set config options of a babel plugin from `.babelrc`? If so, how?
