### ISSUE TITLE
Docs: Provide CLI --ignore option examples

### ISSUE THREAD

**Issue by CrabDude** [babel/babel.github.io#286]
I am unable to discern from the existing documentation how to use the CLI `--ignore` option. It would be nice to have a real example for each.

For instance, none of the following worked:

``` bash
babel --ignore html ./*
babel --ignore .*html ./*
babel --ignore ".*html" ./*
babel --ignore *html ./*
babel --ignore **html ./*
babel --ignore **/*html ./*
babel --ignore [html] ./*
babel --ignore [.*html] ./* 
babel --ignore [*html] ./*
babel --ignore [**html] ./* 
babel --ignore [**/*html] ./*
babel --ignore ["html"] ./*
babel --ignore [".*html"] ./* 
babel --ignore ["*html"] ./*
babel --ignore ["**html"] ./* 
babel --ignore ["**/*html"] ./*
```

**Comment by CrabDude** [comment]
It seems the issue is the `./*` at the end. `.` works. OP stands though, since examples would've been equally useful in this case.

**Comment by hzoo** [comment]
If you want to make a PR, would be appreciated  https://github.com/babel/babel.github.io/blob/master/docs/usage/cli.md

**Comment by hzoo** [comment]
merged https://github.com/babel/babel.github.io/issues/860
