### ISSUE TITLE
Docs: transformer spec.functionName

### ISSUE THREAD

**Issue by lukeapage** [babel/babel.github.io#287]
It took me a while to find https://github.com/babel/babel/issues/1087 which talks about spec.functionName - but I can't find any documentation on the website about why the transform happens and what parts of the es6 spec it relates to... Am I missing something somewhere?

**Comment by thejameskyle** [comment]
Yeah it is missing: https://github.com/babel/babel.github.io/tree/master/docs/usage/transformers/spec

**Comment by hzoo** [comment]
Moving to https://github.com/babel/babel.github.io/issues/780
