### ISSUE TITLE
Docs: API, parse

### ISSUE THREAD

**Issue by SevereOverfl0w** [babel/babel.github.io#290]
Seen the .parse api of babel here: https://github.com/facebook/esprima/issues/111#issuecomment-92518745

I thought it might need to be documented? I'd start, but I don't feel like I'd include everything as I don't truly understand it.

**Comment by jmm** [comment]
Yes indeed, it needs to be documented. @sebmck said on slack it's how you're expected to generate nodes in plugins.

**Comment by jmm** [comment]
Correction: I misunderstood @sebmck's comments. `parse()` is how you're expected to generate nodes *from strings* in plugins, but when it's not necessary to use a string you're supposed to use the `babel.types` node generation methods (which also needs better documentation).

**Comment by hzoo** [comment]
We need general api docs so we can move this to #334
