### ISSUE TITLE
recommended way to blacklist/whitelist transformers for babel-node

### ISSUE THREAD

**Issue by naartjie** [babel/babel.github.io#299]
[moved from babel/babel#1592]

I'm using `babel-node` to run my code on iojs (1.8.2 and 2.0.2). I am looking for a recommended way to blacklist/whitelist the transformers of the features which are fully supported/not supported in iojs.

Maybe I missed this in the docs somewhere, but it would be cool if newcomers could find out about running babel-node with only the minimum subset of transformers needed for their node version.

I actually think that babel-node should get a mention on https://babeljs.io/docs/using-babel/, but it would require a bit of a refactor of the page, as it already has a Node section. I know `babel-node` is also on https://babeljs.io/docs/usage/cli/, but not as a first class citizen.

Happy for a PR for this? 1) which section should it be under? and 2) is the recommended way to create .babelrc in the root of the project?

My current minimal first stab at this, is a `.babelrc` like so, but of course the list could be grown quite a bit more still:
```json
{
  "whitelist": [
    "strict",
    "es6.arrowFunctions",
    "es6.modules",
    "es6.destructuring",
    "validation.undeclaredVariableCheck"
  ]
}
```

**Comment by hzoo** [comment]
Closing since in babel 6 since we have plugins/presets now - people will make presets for node versions

**Comment by naartjie** [comment]
Cool makes sense, thanks.
