### ISSUE TITLE
Add a direct download link for the browser version

### ISSUE THREAD

**Issue by ludovicofischer** [babel/babel.github.io#301]
Adding a direct download link to the browser version instead of telling users to get it from npm would help newbies who might not know or want to install npm. Specifically, I am writing a book and it would be nice to be able to tell the reader to download babel from the website instead of guiding them through a node install.

**Comment by thejameskyle** [comment]
Do not tell your users to download babel from the website. The _only_ way 99% of people should be consuming Babel is via `npm`.

**Comment by ludovicofischer** [comment]
Ok, nice to know. I don’t understand the difference between downloading the browser version from npm and getting it from the website directly. Is it for bandwidth reasons? Or because you do not want to encourage a bad workflow?

**Comment by thejameskyle** [comment]
Because the browser version can only compile inside the browser. You should not be doing that unless you are a site like codepen or jsbin (or the babel online repl). Encourage your users to follow best practices.

**Comment by ludovicofischer** [comment]
I understand that you want people to follow best practices; I planned to make them use the browser version just to get started. The problem that I see with no download link is that it discourages people who do not know what npm is or who have difficulties installing node.

**Comment by thejameskyle** [comment]
Sorry but I'd rather actively want to discourage people who are not using npm. Also, please don't tell people to use the browser version in your book, that's not what it is for.

All you have to write:

> Make sure [Node.js](http://nodejs.org/) and [npm](https://www.npmjs.org/) are [installed](http://nodejs.org/download/).
> ```sh
> $ npm install --global babel
> ```
> Then you may compile a file with the Babel CLI:
> ```sh
> $ babel script.js
> ```

**Comment by ludovicofischer** [comment]
I’ll see if my editor agrees that’s the simple enough :-) Thanks for your time.

**Comment by sebmck** [comment]
There are new releases available often enough that you'll need to be updating every second day.
