### ISSUE TITLE
New User: Auth0

### ISSUE THREAD

**Issue by mgonto** [babel/babel.github.io#312]
Please fill the following out:

- Name: Auth0
- Homepage url: https://auth0.com/
- Brand Guidelines/Licensing: No guideline.
- Logo: Choose the one that looks better from https://styleguide.auth0.com/ Logos

**Comment by thejameskyle** [comment]
Geez, I can't add these fast enough today

**Comment by mgonto** [comment]
That's a good sign that Babel usage is increasing ;). Congrats on that :).

**Comment by mgonto** [comment]
Thanks :).

**Comment by thejameskyle** [comment]
You can deep link the actual logo with http://babeljs.io/users/#Auth0 re: https://twitter.com/auth0/status/603683783938826240

**Comment by mgonto** [comment]
Ohh, nice. Thanks :).

**Comment by mgonto** [comment]
Nice effect on deep link BTW
