### ISSUE TITLE
New User: Lazada Group

### ISSUE THREAD

**Issue by mistadikay** [babel/babel.github.io#314]
- Name: Lazada Group
- Homepage url: http://www.lazada.com/
- Brand Guidelines/Licensing: none
- Logo: https://www.dropbox.com/s/ennza0sujsprfph/lazada.svg?dl=0

**Comment by thejameskyle** [comment]
The logo is coming through like this:

![screen shot 2015-05-29 at 1 47 24 pm](https://cloud.githubusercontent.com/assets/952783/7888820/3f0929e8-0609-11e5-89d8-831e388ea737.png)

**Comment by mistadikay** [comment]
How can I reproduce that? svgo 0.5.2 doesn't damage it

**Comment by thejameskyle** [comment]
Wanna open a PR for this? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
