### ISSUE TITLE
New User: Grove Labs

### ISSUE THREAD

**Issue by crenwick** [babel/babel.github.io#316]
- Name: Grove Labs
- Homepage url: https://grovelabs.io/
- Brand Guidelines/Licensing: none
- Logo: https://www.dropbox.com/s/liusnh2cz8n1yda/grove-logo-official.svg?dl=0

:)

**Comment by thejameskyle** [comment]
The SVG is coming through like this in most programs:

![screen shot 2015-05-29 at 1 06 53 pm](https://cloud.githubusercontent.com/assets/952783/7888044/9bc96c0c-0603-11e5-94ac-ae1260555d30.png)

**Comment by crenwick** [comment]
Interesting. I re-uploaded it as a flatter SVG. Can you try it again? https://www.dropbox.com/s/liusnh2cz8n1yda/grove-logo-official.svg?dl=0

**Comment by thejameskyle** [comment]
Thanks
