### ISSUE TITLE
New User: [Vivaldi]

### ISSUE THREAD

**Issue by tatsukit** [babel/babel.github.io#320]
Please fill the following out:

- Name: Vivaldi
- Homepage url: https://vivaldi.com
- Brand Guidelines/Licensing: (or anything we need to know before using your logo)
- Logo: https://vivaldi.com/press/highres/logos/vivaldi_logo_dark.png

**Comment by thejameskyle** [comment]
Thanks

**Comment by tatsukit** [comment]
That was pretty quick! Thanks!
