### ISSUE TITLE
New User: Canopy

### ISSUE THREAD

**Issue by blittle** [babel/babel.github.io#321]
Please fill the following out:

- Name: Canopy
- Homepage url: https://www.canopytax.com
- Brand Guidelines/Licensing: None currently
- Logo: https://drive.google.com/a/canopytax.com/file/d/0B60grZQqYba0TG9KdlNhaDFVRTg/view?usp=sharing

**Comment by thejameskyle** [comment]
I do not have permission to view this logo on Google Drive.

**Comment by blittle** [comment]
Fixed: https://docs.google.com/file/d/0B60grZQqYba0TG9KdlNhaDFVRTg
