### ISSUE TITLE
New User: DockYard

### ISSUE THREAD

**Issue by bcardarella** [babel/babel.github.io#322]
Please fill the following out:

- Name: DockYard
- Homepage url: dockyard.com
- Brand Guidelines/Licensing: (or anything we need to know before using your logo)
- Logo: http://i.imgur.com/BsGWE1Y.png

**Comment by thejameskyle** [comment]
@bcardarella do you have a higher resolution version of the logo?

**Comment by thejameskyle** [comment]
Wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
