### ISSUE TITLE
New User: Segment

### ISSUE THREAD

**Issue by lambtron** [babel/babel.github.io#324]
Please fill the following out:

- Name: Segment
- Homepage url: https://www.segment.com
- Brand Guidelines/Licensing: none
- Logo: https://www.dropbox.com/work/Marketing/Segment_Press_Kit/Logos?preview=segment-avatar-big.png

**Comment by sterlingw** [comment]
I can't access the logo without having a Dropbox for business account - please provide an accessible version.

**Comment by lambtron** [comment]
Oh so sorry about that! Shoot didn't realize.

http://i.imgur.com/aZBqCWX.png

Is this better?

**Comment by thejameskyle** [comment]
You're already up on the site http://babeljs.io/users/#Segment

**Comment by lambtron** [comment]
Oh, great! Thank you!!!
