### ISSUE TITLE
Documentation on creating transformers

### ISSUE THREAD

**Issue by jmm** [babel/babel.github.io#328]
Is there currently any documentation regarding creating transformers? I don't see any at https://babeljs.io/docs/advanced/transformers/.

**Comment by sebmck** [comment]
Custom transformers are [plugins](https://babeljs.io/docs/advanced/plugins/).

**Comment by jmm** [comment]
@sebmck Ok, thanks. Please see #331.

**Comment by hzoo** [comment]
Should be covered by https://github.com/babel/babel.github.io/issues/534
