### ISSUE TITLE
Warn that you can't use the usual approach to cast a Set as an Array in loose mode

### ISSUE THREAD

**Issue by callumlocke** [babel/babel.github.io#329]
I think this point in the [loose mode caveats](https://babeljs.io/docs/advanced/loose/) should made more thoroughly:

> **es6.destructuring**
> All iterable destructuring are assumed to be arrays.

I think it's worth pointing out explicitly that destructuring Sets will _not_ work, so the very common case of `[...mySet]` for casting a Set as an Array will not work.

For example, all of the classic Set operations [recommended by Axel Rauschmayer](http://www.2ality.com/2015/01/es6-set-operations.html) fail in loose mode (and you don't even get an error, you just get weird results).

It would be good to recommend an alternative way to turn a Set into an Array. I've been using `[for (x of mySet) x]`, but that's only available in experimental mode, and produces a lot of code... is there a better way we could recommend?

**Comment by sebmck** [comment]
The note is pretty explicit. Why do you think there needs to be a separate not for `Set`s when it says that it assumes the values are **only** arrays?

**Comment by callumlocke** [comment]
I guess it's subjective, but I don't find it very explicit on first reading.

I don't think destructuring/spreading iterables is really an 'edgecase', it's a widely lauded feature of ES6, so these are arguably the most important loose mode caveats to know about. But they're easy to miss among all the other, more obscure caveats that are given detailed explanations and code samples.
