### ISSUE TITLE
Auto-deploy when new 6to5 releases are made

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel.github.io#33]

**Comment by sebmck** [comment]
@thejameskyle Any ideas on this?

**Comment by thejameskyle** [comment]
Unless we set up a server to use GitHub's webhooks, it's going to have to be part of `make publish` in 6to5.

**Comment by sebmck** [comment]
Yeah I'm fine with that, just wondering how it'd be integrate with it.

**Comment by thejameskyle** [comment]
@sebmck do you have this auto-deploying now?

**Comment by sebmck** [comment]
Yeah
