### ISSUE TITLE
Embed the REPL?

### ISSUE THREAD

**Issue by jussi-kalliokoski** [babel/babel.github.io#337]
On [Trine](https://github.com/jussi-kalliokoski/trine)'s docs, I would like to feature the Babel REPL so people can easily mess around with the library, because it's currently highly dependent on stage 0 features of Babel and asking people to set up a build system just to mess around with the API of the library and see what it can do isn't very nice UX.

Adding a global `require()` that provides Trine's modules is the easy part, but I'm wondering if there's any recommended way of adding the REPL to another website? Obviously it would be great to have the REPL as a standalone npm package so I could just import it with Webpack and embed wherever I want, but I doubt that's a priority for Babel, so I'm wondering if you have any ideas on how to go forward with this? :)

**Comment by thejameskyle** [comment]
You can embed jsbin which has Babel built in

**Comment by piecioshka** [comment]
Or try to use my last tool: http://piecioshka.github.io/executor/demo/ :gift:

**Comment by hzoo** [comment]
I think a jsbin, codepen, or etc embedded would work fine? http://jsbin.com/help/how-can-i-embed-jsbin, https://blog.codepen.io/documentation/features/embedded-pens/
