### ISSUE TITLE
New User: Indivirtual

### ISSUE THREAD

**Issue by pverbeek** [babel/babel.github.io#339]
Please fill the following out:

- Name: Indivirtual
- Homepage url: http://www.indivirtual.com
- Brand Guidelines/Licensing: none
- Logo: https://blog.indivirtual.nl/wp-content/uploads/2015/04/lg-indy.png

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
