### ISSUE TITLE
Disable flow type support in the REPL

### ISSUE THREAD

**Issue by ralt** [babel/babel.github.io#344]
It's really weird to see flow types in the REPL, and no error happens.

At some point, I thought the REPL had typescript features, but the code wasn't correct. (i.e. I had `function foo() : string { return 4; }` and it compiled fine.)

**Comment by hzoo** [comment]
Maybe just better documentation about what babel does with flow types like requested in #152?

**Comment by hzoo** [comment]
I think the general request would be to be able to turn on or off any plugin.

Going to close for now.
