### ISSUE TITLE
REPL causes tab to become unresponsive on infinite loop in compiled code

### ISSUE THREAD

**Issue by porterjamesj** [babel/babel.github.io#352]
Hey y'all—

Opening up the REPL and then typing or pasting the following:

```
var cbs = [];

for (let i=1; i++; i<5) {
  cbs.push(function() { return i; });
}
```

causes the tab to become unresponsive for me on both Chrome and FF. Sorry for lack of better test case and debugging info; the tab dying makes it hard to figure out what happened :/ I just idly wanted to see if `let` fixes for loop scope problems in ES6 and stumbled across this in the process.

Note that various permutations of this input don't trigger the problem, for example:

```
for (let i=1; i++; i<5) {
  cbs.push(function() { return i; });
}

var cbs = [];
```

is fine.

**Comment by Mark-Simulacrum** [comment]
I think that the REPL is hanging due to the first example provided being an infinite loop.
> Opening up the REPL and then typing or pasting the following:
```
var cbs = [];
>
for (let i=1; i++; i<5) {
    cbs.push(function() { return i; });
}
 ```

A possible solution would be to (somehow) include https://github.com/jsbin/loop-protect to try to prevent infinite loops from occuring.

**Comment by porterjamesj** [comment]
oh wow sorry, you're right — i actually hadn't realized that the code actually gets run after being compiled. i suppose thats why its called a repl though 😆

**Comment by porterjamesj** [comment]
i have no idea if its even possible or reasonable to fix this then

**Comment by Mark-Simulacrum** [comment]
You can uncheck the `evaluate` checkbox to disable evaluation. Seeing as CodePen, JSBin, and other similar services seem to do this, I think it is possible for it to be done -- although perhaps out of scope of what the REPL is intended for.

**Comment by porterjamesj** [comment]
yeah i also didn't realize i screwed up the loop since i havn't written js in ages 😅 if you want to close i think that would be totally reasonable

**Comment by brigand** [comment]
Considering code is generally assumed to be pure (not manipulating dom, etc) it could be run in a worker along with the babel syntax transform. Prevent long compilation/execution from freezing the editor, and it doesn't even need to have babel included on the repl page, as nice side effects.

If the worker doesn't respond after N amount of time, you can [worker.terminate()][1]. 

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Worker/terminate

**Comment by hzoo** [comment]
We can use https://github.com/fkling/astexplorer/blob/be1e07ed7d8ebf6453c95211734040f3375e43a8/src/TransformOutput.js#L21-L35 halting-problem/loop protect like mentioned if someone wants to PR

**Comment by STRML** [comment]
That is completely crazy and clever as hell
