### ISSUE TITLE
New User: drchrono

### ISSUE THREAD

**Issue by pirate** [babel/babel.github.io#353]
- Name: drchrono
- Homepage url: https://www.drchrono.com/
- Brand Guidelines/Licensing: acceptable versions: https://www.drchrono.com/logos/ email n+logo@drchrono.com for questions
- Largest Logo: https://www.drchrono.com/site_media/img/public/logos/drchrono_logo_dark_1400x399.png
- Other sizes: https://www.drchrono.com/logos/

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
