### ISSUE TITLE
New User: RisingStack

### ISSUE THREAD

**Issue by hellogabor** [babel/babel.github.io#354]
* Name: RisingStack
* Homepage URL: http://www.risingstack.com
* Logo: http://risingstack.com/assets/images/logo-rising-stack.svg

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
