### ISSUE TITLE
New User: Moneytree

### ISSUE THREAD

**Issue by moneytree-doug** [babel/babel.github.io#355]
Moneytree is a leading personal finance application that supports over 1,300 financial institutions in Japan.

Please fill the following out:

- Name: Moneytree
- Homepage url: https://moneytree.jp
- Brand Guidelines/Licensing: N/A
- Logo: Attached below.
![moneytree-logo 1](https://cloud.githubusercontent.com/assets/7564255/8426669/a2300d28-1f4c-11e5-91e0-89aba5008f8c.png)

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by moneytree-doug** [comment]
@thejameskyle Done: https://github.com/babel/babel.github.io/pull/558
