### ISSUE TITLE
"High compliancy" is not explained

### ISSUE THREAD

**Issue by callumlocke** [babel/babel.github.io#359]
Continuing from babel/babel#1930.

OK I can see why it can be useful to use high compliancy and loose mode together, but it's confusing with the current labeling. Maybe the solution is to add a note under the "High compliancy" checkbox, saying "Enables [optional `spec` transformers](http://babeljs.io/docs/advanced/transformers/#optional)".

**Comment by brigand** [comment]
Even experimental should maybe be changed to a dropdown for stage with a description of each?

Related #92

**Comment by hzoo** [comment]
Closing since this was a babel 5 option
