### ISSUE TITLE
New User: Blendle

### ISSUE THREAD

**Issue by jtangelder** [babel/babel.github.io#364]
Hi, we're using Babel as well! It would be nice if you would mention us on the users page.

- Name: Blendle
- Homepage url: https://www.blendle.com
- Brand Guidelines/Licensing: -
- Logo: https://blendle.com/img/logos/blendle.logo.orange.svg

Cheers

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
