### ISSUE TITLE
es7 do expressions not documented

### ISSUE THREAD

**Issue by Dashed** [babel/babel.github.io#365]
As far as I'm aware, I cannot find this on the main babel site.

I became aware of this via:
https://twitter.com/vslinko/status/619581969903550464
http://wiki.ecmascript.org/doku.php?id=strawman:do_expressions

**Comment by sebmck** [comment]
This is a deliberate decision. It's not on standards track and I'm highly considering removing it at anytime because of the attention it's getting.

**Comment by Dashed** [comment]
Ah I see. Good to know :+1:

**Comment by RReverser** [comment]
Hm, wasn't original intent exactly to get as much attention and feedback as possible in order to move this to real proposal?

**Comment by zenparsing** [comment]
@RReverser I'm not the champion of do-expressions  : )  That would be Andreas Rossberg - I think he's planning on presenting a proposal around September.

**Comment by sebmck** [comment]
@RReverser It was implemented after a brief conversation with @wycats and to see if I could get the correct completion record semantics.

**Comment by zenparsing** [comment]
@sebmck If you want to pursue do-expressions in Babel, I suggest contacting Andreas to see what his thoughts are.

**Comment by sebmck** [comment]
@zenparsing They're actually already fully implemented according to http://wiki.ecmascript.org/doku.php?id=strawman:do_expressions. Just not sure about keeping them in, I guess they're on par with comprehensions at this stage which are still implemented behind stage 0.

**Comment by zenparsing** [comment]
@sebmck That strawman was last updated in 2011, though : )  And I don't think they fully implement what Andreas wants (for instance, try-blocks should have a completion value).

BTW, comprehensions were essentially dropped AFAIK.  There's no current champion.

**Comment by sebmck** [comment]
@zenparsing

> That strawman was last updated in 2011, though

Yeah I know, that's why I'm so uncomfortable having it in there but if it's going to be actively pursued then it's hopefully not too harmful.

**Comment by sebmck** [comment]
I'm not taking responsibility for this features propagation. I've since removed it in 5.6.19.

**Comment by RReverser** [comment]
@sebmck Wait, you removed function bind? Can it be exposed at least via plugin?

**Comment by thejameskyle** [comment]
> Wait, you removed function bind?

Who said anything about function bind?

> Also, re:version - this is a breaking change if so.

Experimental transformers like do expressions are not guaranteed by Babel's versioning, when you turn on `--stage 0` you are opting out of sane semver versioning so Babel can track in-progress specs.

**Comment by RReverser** [comment]
> Who said anything about function bind?

Discussion up to this point was about function bind, so I misunderstood.

**Comment by thejameskyle** [comment]
:confused: You were the first to mention it?

**Comment by RReverser** [comment]
Yeah, but "responsibility for this features propagation" right after few messages about function bind excuses my misunderstanding :P

**Comment by sebmck** [comment]
Do expressions are back :relaxed: Ref babel/babel#1994

**Comment by RReverser** [comment]
Cool! Just one relevant question: does it mean they should be documented now? (which would mean reopening this issue)

**Comment by sebmck** [comment]
Yeah, someone please feel free to create a PR.

**Comment by chicoxyzzy** [comment]
I am here just to remind to update REPL so someone will be able to try it before documenting
tinyurl.com/ecma-do

**Comment by sebmck** [comment]
Updated
