### ISSUE TITLE
Merge usage/options to usage/cli

### ISSUE THREAD

**Issue by dashed** [babel/babel.github.io#37]
I think 
http://6to5.org/docs/usage/options/
should be a sub-section of `#6to5`:
http://6to5.org/docs/usage/cli/#6to5

This makes for better navigation flow in reading the docs.

---

If the `options` is a separate page, it isn't really clear that some options aren't available in `6to5-node` command (e.g. blacklist).

**Comment by Dashed** [comment]
On second thought, http://6to5.org/docs/usage/options/ probably just need improvements.

**Comment by sebmck** [comment]
It's not a CLI-exclusive thing though.

**Comment by Dashed** [comment]
Yeah, you're right. I think there should be some explicit internal references like:

> See available [options](http://6to5.org/docs/usage/options/).

IIRC, before the site redesign, the options and the CLI stuff were on the same page, making it easier for the user to look up references.

I can send a quick PR for this.

**Comment by sebmck** [comment]
@Dashed Sure, that'd be great.

**Comment by hzoo** [comment]
@dashed still cool with sending a PR?

**Comment by dashed** [comment]
@hzoo Probably not. Unsure if this issue is still valid as I'm unaware if the site has drastically changed since I filed this. Feel free to close/modify the issue.

**Comment by hzoo** [comment]
Alright, thanks
