### ISSUE TITLE
New User: Cloud6

### ISSUE THREAD

**Issue by nparsons08** [babel/babel.github.io#370]
Please fill the following out:

- Name: Cloud6
- Homepage url: http://cloud6.io/
- Brand Guidelines/Licensing: N/A
- Logo: http://cl.ly/image/3W1w2W1x3x1C

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
