### ISSUE TITLE
New User: Diigo

### ISSUE THREAD

**Issue by Yixi** [babel/babel.github.io#372]
Please fill the following out:

- Name: Diigo
- Homepage url: https://www.diigo.com/index
- Logo:https://www.diigo.com/images/v6/logo.png

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
