### ISSUE TITLE
New User: PRND Company

### ISSUE THREAD

**Issue by dobestan** [babel/babel.github.io#373]
![default](https://cloud.githubusercontent.com/assets/4688315/8700273/ce1dbd54-2b45-11e5-8526-f8bd02471659.png)

- Name: PRND Company
- Homepage url: http://prnd.co.kr
- Brand Guidelines/Licensing: 
- Logo: https://www.dropbox.com/s/kfj0vifzr0hnuhw/prnd.png

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
