### ISSUE TITLE
New User: wallaby.js

### ISSUE THREAD

**Issue by ArtemGovorov** [babel/babel.github.io#374]
- Name: wallaby.js
- Homepage url: http://wallabyjs.com/
- Logo: http://wallabyjs.com/assets/img/logoWithText.png

We are using babel internally in wallaby.js development and we also support [babel compiler](http://wallabyjs.com/docs/integration/es-next.html) to support ES6/ES7 in wallaby.js.

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by ArtemGovorov** [comment]
@thejameskyle Done - https://github.com/babel/babel.github.io/pull/561
