### ISSUE TITLE
New User: Nukomeet

### ISSUE THREAD

**Issue by zaiste** [babel/babel.github.io#376]
Please fill the following out:

- Name: Nukomeet
- Homepage url: http://nukomeet.com/
- Brand Guidelines/Licensing: http://nukomeet.com/logos/
- Logo: http://nukomeet.s3.amazonaws.com/nukomeet.svg

> Example:
>
> Name: CloudFlare
> Homepage url: https://cloudflare.com
> Brand Guidelines/Licensing: https://www.cloudflare.com/logo
> Logo: https://www.cloudflare.com/media/downloads/cloudflare-logo-kit.zip

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by zaiste** [comment]
Thanks, I've just opened [a PR](https://github.com/babel/babel.github.io/pull/555)
