### ISSUE TITLE
New User: iAdvize

### ISSUE THREAD

**Issue by jsoulet** [babel/babel.github.io#382]
- Name: iAdvize
- Homepage url: http://www.iadvize.com/
- Brand Guidelines/Licensing: http://www.iadvize.com/en/press-room/style-guide/
- Logo: https://www.dropbox.com/s/r135d1hn3iepvfx/iadvize-black.svg?dl=0

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
