### ISSUE TITLE
New User: Kahoot!

### ISSUE THREAD

**Issue by kmoe** [babel/babel.github.io#383]
- Name: Kahoot!
- Homepage url: https://getkahoot.com/
- Brand Guidelines/Licensing: none
- Logo: attached

![kahoot](https://cloud.githubusercontent.com/assets/5575356/8831352/baf301fe-3099-11e5-8598-3ea61590cf2d.png)

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
