### ISSUE TITLE
New User: Lithium Technologies

### ISSUE THREAD

**Issue by dschoon** [babel/babel.github.io#384]
Please fill the following out:

- Name: Lithium Technologies
- Homepage url: http://www.lithium.com
- Brand Guidelines/Licensing: https://www.lithium.com/company/news-room/
- Logo: https://www.lithium.com/media_kit/lithium-logo-registered-black.png

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
