### ISSUE TITLE
New User: Codinum

### ISSUE THREAD

**Issue by janoskk** [babel/babel.github.io#388]
We've been using Babel from the beginning. That time Babel was called 6to5 ;-)

- Name: Codinum
- Homepage url: https://codinum.com
- Brand Guidelines/Licensing: GPL
- Logo: https://codinum.com/images/codinum_rainbow_big.png

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by janoskk** [comment]
Opened #560
