### ISSUE TITLE
Broken link to list of node aliases

### ISSUE THREAD

**Issue by RReverser** [babel/babel.github.io#390]
[Plugins - Visiting](https://babeljs.io/docs/advanced/plugins/visiting/) page links to https://github.com/babel/babel/blob/master/src/babel/types/alias-keys.json in "Visitor aliases" section which was either moved or doesn't exist anymore.

**Comment by hzoo** [comment]
Did a PR for this in #387

**Comment by thejameskyle** [comment]
Yup, merged
