### ISSUE TITLE
New User: SparkPost

### ISSUE THREAD

**Issue by AimeeKnight** [babel/babel.github.io#391]
Please fill the following out:

- Name: SparkPost
- Homepage url: https://www.sparkpost.com/
- Brand Guidelines/Licensing: NA
- Logo: 
![sparkpost](https://cloud.githubusercontent.com/assets/2165184/8986837/13270de4-36ac-11e5-8e9f-d2e9dd70103c.png)

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by AimeeKnight** [comment]
@thejameskyle Yep. I'll follow up with a PR.
