### ISSUE TITLE
New User: Social Tables

### ISSUE THREAD

**Issue by conorhastings** [babel/babel.github.io#393]
Please fill the following out:

- Name: Social Tables
- Homepage url: http://www.socialtables.com
- Brand Guidelines/Licensing: N/A
- Logo: 

![st-logo](https://cloud.githubusercontent.com/assets/8263298/8996256/9856843a-36e4-11e5-9ed6-ba3e6cab8fe2.png)

**Comment by rovolution** [comment]
+1

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
