### ISSUE TITLE
Example replacement proposal

### ISSUE THREAD

**Issue by cbabos** [babel/babel.github.io#394]
Hi there, 

I saw the examples on the site (http://babeljs.io/docs/learn-es2015/) and I think there is a better example for this: 

```Javascript
// Statement bodies
nums.forEach(v => {
  if (v % 5 === 0)
    fives.push(v);
});
```

My proposal is to replace the forEach with filter, like this: 
```Javascript
// Statement bodies
let fives = nums.filter(v => !(v % 5));
```

Of course it's only an example, showing the arrow functions, but maybe it makes sense.

**Comment by goto-bus-stop** [comment]
Arrow functions with expression bodies are showcased just above that bit (`evens.map(v => v + 1)`), the `nums.forEach` example is meant to show that arrow functions can also have statement bodies when surrounded by braces as in `(arg) => { body; }` :smiley:

**Comment by cbabos** [comment]
Okay then :) It was just a proposal, in case if it's fitting better :)
