### ISSUE TITLE
New User: BuildingConnected

### ISSUE THREAD

**Issue by HankMcCoy** [babel/babel.github.io#395]
- Name: BuildingConnected
- Homepage url: http://www.buildingconnected.com/
- Brand Guidelines/Licensing: None
- Logo: https://drive.google.com/file/d/0B1f6bL0nMXSDSzhEM24yU09MbTA/view

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
