### ISSUE TITLE
Handling new users information

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [babel/babel.github.io#402]
There are currently 20-22 issues related to new users on the issue tracker. May be we should provide suggest adding PR to update this page https://babeljs.io/users/ instead of opening issues?

**Comment by prathamesh-sonpatki** [comment]
We can also add a label for such issues :)

**Comment by thejameskyle** [comment]
I have a half-baked script that can automate a good portion of the work I do to add each logo. I resize/optimize each image and review their usage permissions carefully.

**Comment by prathamesh-sonpatki** [comment]
@thejameskyle May be we can add that script in this repo which can help the users to add their logo?

**Comment by thejameskyle** [comment]
I'll try to finish it more

**Comment by sebmck** [comment]
Probably best not to let people specify what position they appear in though.

**Comment by prathamesh-sonpatki** [comment]
@sebmck We can mention that new logos will be added in the end and PR's can always be monitored.

**Comment by hzoo** [comment]
We tell people to open a PR now so gonna close
