### ISSUE TITLE
New User: Schibsted Spain

### ISSUE THREAD

**Issue by nucliweb** [babel/babel.github.io#403]
Please fill the following out:

- Name: Schibsted Spain
- Homepage url: http://www.schibsted.es
- Brand Guidelines/Licensing: None
- Logo: https://drive.google.com/file/d/0BzUYeR0BohTmTnpHdWx4cExxQ0U/view?usp=sharing

Some repos with Babel https://github.com/SUI-Components

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by nucliweb** [comment]
Done, https://github.com/babel/babel.github.io/pull/562

Thanks
