### ISSUE TITLE
New User: Olapic

### ISSUE THREAD

**Issue by loverajoel** [babel/babel.github.io#406]
Please fill the following out:

- Name: Olapic
- Homepage url: http://www.olapic.com/
- Brand Guidelines/Licensing: No
- Logo: https://www.dropbox.com/s/9unztpf9i4scurp/olapic-logo.svg?dl=0

Where we use Babel? 
We release a new product completely built in React and Babel.
https://www.olapic.com/instagram-shopping

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by loverajoel** [comment]
@thejameskyle done https://github.com/babel/babel.github.io/pull/554
