### ISSUE TITLE
Online Babel Repl console and output panel scroll overlap

### ISSUE THREAD

**Issue by bendtherules** [babel/babel.github.io#413]
Open this [Repl with code]( http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=var%20o%20%3D%20%5B1%2C2%2C3%5D%2C%0D%0A%20%20%20%20a%2C%20b%2C%20c%2C%20p%3B%0D%0A%0D%0Ap%20%3D%20%5B%20a%2C%20b%2C%20c%20%5D%20%3D%20o%3B%0D%0A%0D%0Aconsole.log(%20p%20)%3B%20%20%20%20%20%20%20%20%20%2F%2F%201%202%203%0D%0Aconsole.log(p%20%3D%3D%3D%20o)%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20true ) and see the first console.log output overlap with the output js panel scrollbars.

**Comment by thejameskyle** [comment]
Meh, I don't have a better solution other than making a third panel, which I don't want to do

**Comment by bendtherules** [comment]
I dont think you need to do anything other than a few CSS changes.

For `.babel-repl-editor`, use `bottom:60px` instead of  `bottom:30px`
And for `.babel-repl-reporter`, use `height:60px` removing the `min-height` and `max-height` values.

That solved the problem for me

**Comment by thejameskyle** [comment]
That's arguably much worse since it limits how much of the console output that can be seen to only `60px`.

**Comment by bendtherules** [comment]
You're right, that'll be worse.
But I hope that you appreciate the concern, and consider putting the (input and output panels) and (error and log panels) in two different containers or something like that to fix it. You're probably concerned that your markup will get worse or more complicated than needed and thats true, but with current limitations of CSS, that seems like a reasonable solution.

**Comment by jeffijoe** [comment]
I'm having this issue right now.
