### ISSUE TITLE
async and objectrestspread not in stage 2 on website

### ISSUE THREAD

**Issue by songawee** [babel/babel.github.io#414]
Per the babel changelog, I see that they've been moved from stage 1 to stage 2. Is it ok to update the website?

**Comment by thejameskyle** [comment]
Hmm according to https://github.com/tc39/ecma262, Rest/Spread Properties has not moved to stage 2.

@sebmck do you know something that document does not?

**Comment by zloirock** [comment]
@thejameskyle https://github.com/rwaldron/tc39-notes/blob/master/es7/2015-07/july-30.md#613-advance-restspread-properties-to-stage-2

**Comment by hzoo** [comment]
also https://github.com/babel/babel/commit/ee2e8d10cee454449cc9144219e32c5607a89950

**Comment by thejameskyle** [comment]
Done, thanks @zloirock. PR to ecma262 repo is here https://github.com/tc39/ecma262/pull/58
