### ISSUE TITLE
New User: Money Forward

### ISSUE THREAD

**Issue by khirayama** [babel/babel.github.io#415]
Please fill the following out:

- Name: Money Forward
- Homepage url: http://corp.moneyforward.com/
- Brand Guidelines/Licensing: N/A
- Logo: Attached below.

![moneyforward](https://cloud.githubusercontent.com/assets/4658938/9343896/d33b3bf8-463f-11e5-933d-b939c9008936.png)

**Comment by prathamesh-sonpatki** [comment]
Can be closed now as #416 got merged
