### ISSUE TITLE
Bug: Cannot click on 2 links above the "Advanced > Transformers > Usage" heading

### ISSUE THREAD

**Issue by hawkrives** [babel/babel.github.io#417]
Steps to reproduce: 

1. Visit http://babeljs.io/docs/advanced/transformers/#usage
2. Try to click on one of:
    - `validation.undeclaredVariableCheck`
    - `validation.react`
    - the bottom half of `spec.undefinedToVoid`
3. Realize that you can't

I have reproduced this in Safari 8.0.8, Firefox (Nightly) 43, and Chrome (Stable).

-----

It comes down to these lines of [_content.scss#L3-L10](https://github.com/babel/babel.github.io/blob/0f5178c1d4802a458b2ecee2b51d72f13cec1a3d/_sass/components/_content.scss#L3-L10) – um, wait. That's a different file, but a very similar one.

There we go: [_type.scss#L35-L40](https://github.com/babel/babel.github.io/blob/0f5178c1d4802a458b2ecee2b51d72f13cec1a3d/_sass/components/_type.scss#L35-L40).

```scss
h1, .h1,
h2, .h2,
h3, .h3,
h4, .h4,
h5, .h5,
h6, .h6 {
  // …
  &:target::before {
    content: "";
    display: block;
    margin-top: -70px;
    height: 70px;
  }
}
```

The `margin-top` /  `height` rules are blocking about 70px of the area above any `:target`ed heading, which translates to 2 ½ lines of unclickable links. 

I've highlighted the offending area by doing `h3#usage {  background-color: rgba(215, 205, 136, 0.5); }`

<img width="830" alt="screen shot 2015-08-19 at 4 18 01 pm" src="https://cloud.githubusercontent.com/assets/464441/9369331/e7cdf062-468d-11e5-9390-8e0b89c99964.png">

-----

Apologies for the rambling.

I cannot see any negative ramifications from just removing that whole chunk of rules in `_type.scss`.

As for `_content.scss`, I don't know what they're affecting, really, so I cannot shed any light on them.

I would be happy to submit a pull request removing the offending lines, or anything else that you all decide to do :smile: 

As always, thanks to everyone involved for their hard work on Babel! :goat:

**Comment by thejameskyle** [comment]
The reason for it is to allow people to link to sections without the navbar covering up the heading.

I believe #345 fixes this, I'm going to merge it.

**Comment by hawkrives** [comment]
Yep! Looks like that fixed it. Thanks!
