### ISSUE TITLE
Can't click links in <h1...6> tags

### ISSUE THREAD

**Issue by trbrc** [babel/babel.github.io#422]
It's not possible to click links in headlines, e.g. the "Visiting"/"Manipulation"/"Scope" links at the bottom of http://babeljs.io/docs/advanced/plugins/

This seems to be a consequence of #345 which added `z-index: -1;` to headlines.

See also #417, #251.

**Comment by thejameskyle** [comment]
It works!

omg... this has been like a 5 month long issue
