### ISSUE TITLE
grunt-cli-babel

### ISSUE THREAD

**Issue by monolithed** [babel/babel.github.io#423]
Hi, could you add some info about [grunt-cli-babel](https://www.npmjs.com/package/grunt-cli-babel)?

**Comment by thejameskyle** [comment]
What does it do? The README doesn't really explain

**Comment by monolithed** [comment]
It's an alternative to grunt-cli.

##### Gruntfile.js

```js
export default grunt => {
       let clean = {
		test: ['cache']
	};
	grunt.initConfig({ clean });

	grunt.loadTasks('tasks');
	grunt.loadNpmTasks('grunt-contrib-clean');

	grunt.registerTask('test', ['clean']);
	grunt.registerTask('default', ['test']);
};
```

##### package.json

```json
{
	"private": true,

	"scripts": {
		"clean": "grunt clean"
	},

	"dependencies": {
		"grunt-contrib-clean": "^0.6.0",
		"grunt-cli-babel"    : "^0.0.2"
	}
}
```

##### usage

```
npm run clean
```

or (`sudo npm install -g grunt-cli-babel`)

```js
grunt clean
```

**Comment by thejameskyle** [comment]
I made a PR into Grunt itself (https://github.com/gruntjs/grunt/pull/1368) to see if they're willing to add support for this officially. If not I will add this to the site.

**Comment by chenjianfang** [comment]
可以讲中文吗  还有 npm下载不下来babel

**Comment by hzoo** [comment]
I think you can do gruntfile.babel.js now

**Comment by monolithed** [comment]
It seems not so actual for a long time. 
Please let me know if somebody wants to reopen this issue.
