### ISSUE TITLE
Add missing documentation

### ISSUE THREAD

**Issue by gsklee** [babel/babel.github.io#425]
http://babeljs.io/docs/advanced/transformers/es6/spec-block-scoping/
http://babeljs.io/docs/advanced/transformers/es6/spec-modules/

Doc to these 2 transformers seem to be missing.

**Comment by tomByrer** [comment]
Also:
http://babeljs.io/docs/usage/transformers/minification/dead-code-elimination

**Comment by hzoo** [comment]
Closing since the docs changed in babel 6 - and searching the codebase there is no dead-code-elimination plugin at the moment
