### ISSUE TITLE
Blog Post: Authoring in io.js, publishing for npm

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel.github.io#43]
Haven't worked out the contents of this yet, but it's something along the lines of this:

- io.js adds support for a lot of ES6 features and can still publish to npm
- however if you want to remain compatible with Node.js you'll need to distribute a transpiled version of your library
- here's a couple simple ways to do it with 6to5

Ref: @brianleroux https://twitter.com/brianleroux/status/554751754701524992

**Comment by sebmck** [comment]
io.js doesn't really add much ES6 support anyway. See the [wiki](https://github.com/seegno/io.js/wiki/The-state-of-ES6-on-io.js). I think people are going to be very disappointed when they try out io.js and realise that v8 is pretty lacking.

**Comment by thejameskyle** [comment]
It adds enough to create some serious incompatibility issues between the two.

**Comment by sebmck** [comment]
Yeah, definently. Just referring to the io.js ES6 hype.

**Comment by thejameskyle** [comment]
Thats the kind of hype we need to latch onto! :stuck_out_tongue_winking_eye: but I will be sure to reflect that in the post.
