### ISSUE TITLE
myOldWeirdJavaScript → myNewTransformedJavaScript?

### ISSUE THREAD

**Issue by silvenon** [babel/babel.github.io#431]
I'm confused by this description on the home page. I may be missing something incredibly obvious, but isn't it the other way around?

**Comment by thejameskyle** [comment]
Nope, it's correct. But I've improved the language a little bit

**Comment by silvenon** [comment]
Oh. I was confused because you have to input the new ES2015 code to get the "weird old JavaScript" out. But the change makes much more sense now.
