### ISSUE TITLE
Options: add plugins

### ISSUE THREAD

**Issue by gsklee** [babel/babel.github.io#436]
https://babeljs.io/docs/usage/options/

Currently lacks explanation on the `plugins` option.

**Comment by gajus** [comment]
I suppose I am looking for the same documentation, http://stackoverflow.com/questions/32540598/disable-babelrc-inheritance.

**Comment by hzoo** [comment]
Plugins option links to https://babeljs.io/docs/plugins/ now which I think should be sufficient?
