### ISSUE TITLE
New User: True B.V.

### ISSUE THREAD

**Issue by fahad19** [babel/babel.github.io#437]
- Name: True B.V.
- Homepage url: https://true.nl
- Brand Guidelines/Licensing: https://www.true.nl/over-true/#artwork
- Logo: https://www.true.nl/TRUE-Artwork.zip

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
