### ISSUE TITLE
New User: Textalk

### ISSUE THREAD

**Issue by Dervisevic** [babel/babel.github.io#441]
- Name: Textalk
- Homepage url: http://textalk.se
- Brand Guidelines/Licensing: None
- Logo: http://effie.textalk.com/~dervisevic/textalk.svg

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
