### ISSUE TITLE
Document at options page that when using require hook, `ignore` essentially has default value of `**/node_modules/**`

### ISSUE THREAD

**Issue by jmm** [babel/babel.github.io#454]
And that if you want to additionally ignore something else, you have to re-add `node_modules`.

**Comment by thejameskyle** [comment]
It's a bit more than just a default. It only is set to `node_modules` when `ignore` and `only` are not set. 

See https://github.com/babel/babel/blob/91fb64eaf53c67a7ed7605aab71f8dcaa4d39ae2/packages/babel/src/api/register/node.js#L113-L119

**Comment by jmm** [comment]
@thejameskyle yeah, that's what I meant by "essentially". Are you saying that my description is too sloppy considering the `getRelativePath()` part? :smiley: Or something about where it should be documented or how it should be described?
