### ISSUE TITLE
Nail down and document `.babelrc` format

### ISSUE THREAD

**Issue by jmm** [babel/babel.github.io#455]
Currently, in actuality, it's JSON5. From slack:

> @ jmm
> What's the official story on `.babelrc` format -- JSON5?
> 
> @ sebastian
> yes
> 
> @ jmm
> Ok, thanks. And that can be documented, right?
> 
> @ sebastian
> probably
> i wonder if there's an rc file standard
> feels weird for babel to use json5 if all other tools are using normal json

**Comment by thejameskyle** [comment]
Do you just want to add a note to the http://babeljs.io/docs/usage/babelrc/ page?

**Comment by jmm** [comment]
@thejameskyle yes, that's all I mean -- except for the "probably", the uncertainty about committing to JSON5 as the format. Do you want me to file that as a separate issue on babel/babel? Thanks!

**Comment by thejameskyle** [comment]
@sebmck ?

**Comment by sebmck** [comment]
@thejameskyle Whatever Babel 6 has we'll have to commit to. We should stop opening issues in this repo and add a milestone so we can get the docs updated ASAP for launch.

**Comment by jmm** [comment]
@sebmck 
> We should stop opening issues in this repo and add a milestone so we can get the docs updated ASAP for launch.

Do you mean that issues related to updated docs for v6 should be tagged with a milestone, or that there should be one big issue with everything for v6? Just not sure exactly what you mean about stopping opening issues in this repo and don't want to be doing something counterproductive. Thanks!
