### ISSUE TITLE
New User: Squarespace

### ISSUE THREAD

**Issue by jacobangel** [babel/babel.github.io#462]
- Name: Squarespace
- Homepage url: http://www.squarespace.com/
- Brand Guidelines/Licensing: http://www.squarespace.com/brand-guidelines/
- Logo: http://squarespace.com/s/squarespace-logos.zip

**Comment by thejameskyle** [comment]
Want to go ahead and add yourself. Should be just like this https://github.com/babel/babel.github.io/pull/458/files

**Comment by jacobangel** [comment]
Ahh, cool. Will do.

**Comment by jacobangel** [comment]
https://github.com/babel/babel.github.io/pull/463
