### ISSUE TITLE
New User: Codecademy

### ISSUE THREAD

**Issue by artursapek** [babel/babel.github.io#469]
We've been using Babel at Codecademy for almost a year and we love it! Here's our info in case you want to include us on your "users" page.

- Name: Codecademy
- Homepage url: https://www.codecademy.com
- Brand Guidelines/Licensing: nothing really, should look good on white like you have :-)
- Logo: https://www.codecademy.com/assets/logo/logo--dark-blue.svg

**Comment by thejameskyle** [comment]
Cool! Want to open a PR to add it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by artursapek** [comment]
I started to and then I realized we're already in there! Never mind. :)
