### ISSUE TITLE
New User: AutoLotto

### ISSUE THREAD

**Issue by tejasmanohar** [babel/babel.github.io#470]
- Name: AutoLotto
- Homepage url: https://autolotto.com
- Logo: see below

![green logo png](https://cloud.githubusercontent.com/assets/5959235/10652017/b9f540de-7818-11e5-913f-0f0ab79f1edf.png)
![green on white](https://cloud.githubusercontent.com/assets/5959235/10652019/b9fce42e-7818-11e5-9cf7-1fdcf8549a4a.jpg)
![white logo png](https://cloud.githubusercontent.com/assets/5959235/10652020/b9fe7636-7818-11e5-940c-c7585f7e314c.png)
![white on green](https://cloud.githubusercontent.com/assets/5959235/10652018/b9f98856-7818-11e5-876f-a4a19177d70d.jpg)

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by tejasmanohar** [comment]
sorry about this. my bad. shoul've sent PR, forgot to come back to this notif

**Comment by thejameskyle** [comment]
No worries @gsvolt got it

**Comment by tejasmanohar** [comment]
:)
