### ISSUE TITLE
New User: GoDaddy

### ISSUE THREAD

**Issue by acarlos1000** [babel/babel.github.io#472]
Please fill the following out:

- Name: GoDaddy
- Homepage url: http://www.godaddy.com
- Brand Guidelines/Licensing:
- Logo: 
![1280x558xgodaddy svg_ png pagespeed ic_ dxy9i7drkz-624x272-2](https://cloud.githubusercontent.com/assets/125191/10677209/c99af306-78bf-11e5-8066-edf9b791b2b2.png)

**Comment by thejameskyle** [comment]
I'm confused, are you saying that you are a user or GoDaddy is?

**Comment by acarlos1000** [comment]
Hi Eric, sorry for the confusion. GoDaddy is using Babel extensively. GoDaddy is the user in this case.

**Comment by thejameskyle** [comment]
Okay cool, want to open a PR? Here are some examples:

https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Amerged+new+user+

**Comment by gsvolt** [comment]
@thejameskyle just submitted a PR for adding GoDaddy as a user. Hope this helps
Cheers!

**Comment by acarlos1000** [comment]
Thanks @gsvolt .
