### ISSUE TITLE
REPL security

### ISSUE THREAD

**Issue by popc0rn** [babel/babel.github.io#480]
Immediately executing javascript passed as a query string is pretty bad from security perspective. Since this is static website, have you considered first showing the code and asking the user to manually run it with some type of warning?

**Comment by tengbretson** [comment]
In addition to security issues, immediately executing the code can cause the editor to hang and become unresponsive.

Just writing a simple for loop causes the editor to get stuck once you write:
`for (let i = 0; i <100; )`

**Comment by popc0rn** [comment]
^ the code also gets stored to local storage so the next time you visit "https://babeljs.io/repl/" without cleaning it, the same code code is automatically executed. e.g. redirect somewhere with window.location inside editor. Then try to visit "https://babeljs.io/repl/" and it will automatically redirect until you clean up the local storage.
