### ISSUE TITLE
REPL locks up on unexpected token

### ISSUE THREAD

**Issue by TomasHubelbauer** [babel/babel.github.io#483]
```js
var original = {a: 7, b: 8, c: 9};

for (var index = 0; index$)

var {...clone} = original;
console.debug(clone == original);
```

Place the caret instead of the dollar sign and type ` < 999; index++`. At some point, the whole Chrome tab will lock up. Sometimes happens after `<`, sometimes after `;`, sometimes after `+`, I guess it depends on how slow I type causing the REPL environment to reevaluate, whence it locks up.

REPL error log says *Unexpected token (3:28)*. Experimental mode is on. Happens in both Chrome and Firefox, haven't tried it elsewhere. Firefox displays an *Unresponsive script* warning prompts which says *repl...2:32+ 00:00 line 265 > Function 3*.

**Comment by thejameskyle** [comment]
You're running into an infinite loop because it is executing as you type.

**Comment by TomasHubelbauer** [comment]
Dang, I never stop to think what the code is doing and just assumed the environment was broken. Thanks.
