### ISSUE TITLE
Lots of Dead Links

### ISSUE THREAD

**Issue by JKillian** [babel/babel.github.io#485]
For example [the learn es2015 modules section](https://babeljs.io/docs/learn-es2015/#modules) contains a link to https://babeljs.io/docs/usage/modules which no longer exists. Other external sites link to this page as well ([example](http://www.jbrantly.com/es6-modules-with-typescript-and-webpack/)).

I've stumbled across other links that also 404 now.

**Comment by thejameskyle** [comment]
Sorry, the site just had a lot of changes for the 6.0 release. We're just going to redirect stuff though

**Comment by JKillian** [comment]
:+1:  No worries! A redirect sounds good to me

**Comment by hzoo** [comment]
Should this redirect to the https://babeljs.io/docs/plugins/ page or a page for all modules?

**Comment by thejameskyle** [comment]
We might want to add subcategories to https://babeljs.io/docs/plugins/#transform @sebmck ?

**Comment by sebmck** [comment]
@thejameskyle Sure.

**Comment by hzoo** [comment]
Fixed the other 404 links - let us know if there are any more

**Comment by jsprow** [comment]
I think I found one: [https://babeljs.io/docs/en/babelrc/api.md](url)
