### ISSUE TITLE
How do you use Babel 6.0 with JSX?

### ISSUE THREAD

**Issue by brimworks** [babel/babel.github.io#488]
When I search for Babel and JSX in Google, one of the first results is this page which is giving a 404:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0CCIQFjABahUKEwj3-7yfx-jIAhUUUmMKHQw6Cvc&url=https%3A%2F%2Fbabeljs.io%2Fdocs%2Fusage%2Fjsx%2F&usg=AFQjCNFJoQag_BAp4Wt1zqju6cLH70EA7w

...and if I `npm install babel-cli`, and try to compile JSX code as as such: ./node_modules/.bin/babel file.jsx -o file.jsx.js

...then it complains about the embedded XML in the JSX.

Thanks,
-Brian

**Comment by hzoo** [comment]
Babel doesn't transform anything by default in 6.0 - `npm install babel-cli babel-preset-es2015 babel-preset-react` http://babeljs.io/docs/plugins/preset-react/

> For questions and support please visit the [Slack community](https://babel-slack.herokuapp.com/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs). The Babel issue tracker is exclusively for bug reports and feature requests.

**Comment by brimworks** [comment]
Thanks! The transition to 6.0 was unexpected and I didn't think to search for "react" (instead I searched for "jsx").

Thanks,
-Brian
