### ISSUE TITLE
/docs/usage/options wrong descriptions of presets and plugins

### ISSUE THREAD

**Issue by zowers** [babel/babel.github.io#493]
`plugins` and `presets` descriptions should be switched from one to another
```
presets 	[] 	List of plugins to load and use.
plugins 	[] 	List of presets to load and use.
```

```
presets 	[] 	List of presets 	to load and use.
plugins 	[] 	List of plugins to load and use.
```

**Comment by zowers** [comment]
also - it's not clear from the description how they are different

**Comment by thejameskyle** [comment]
Flipped them in #492.

How would you describe them better?

**Comment by zowers** [comment]
oh, thanks!
I'd describe that presets are a set of plugins, possibly giving link to http://babeljs.io/docs/plugins/

**Comment by hzoo** [comment]
@zowers made a PR https://github.com/babel/babel.github.io/issues/521 - good for you?

**Comment by zowers** [comment]
great, thanks!

**Comment by tomByrer** [comment]
Is more clear, thanks to all.
