### ISSUE TITLE
Footer needs version bump to 6.0.0

### ISSUE THREAD

**Issue by msegado** [babel/babel.github.io#506]
(...unless I'm misunderstanding what that version number is)

See https://github.com/babel/babel.github.io/blob/00c0eb248071352c97407229491474f1651f911c/_includes/version.html#L1

**Comment by thejameskyle** [comment]
@sebmck didn't you have a script that did this?

**Comment by sebmck** [comment]
@thejameskyle Yes. But we don't update the REPL so there's no point pushing that to the site. You can manually change it if you want.

**Comment by callumlocke** [comment]
at the moment it's confusing as it says v5.8.33 just above "Looking for 5.x docs?", so I think it's worth fixing manually in the meantime
