### ISSUE TITLE
Where should .babelrc reside?

### ISSUE THREAD

**Issue by rauschma** [babel/babel.github.io#507]
With presets, `.babelrc` is important. Is it possible to put a local `.babelrc` inside the directory of a repository (resulting in multiple instances of `.babelrc`, one per repository)? Or can there be only one `.babelrc`? If yes then where? In the home directory? how about Windows?

Thanks!

**Comment by thejameskyle** [comment]
One per repository, feel free to open a PR explaining this

**Comment by rauschma** [comment]
Thanks! What is the algorithm for looking it up? Relative to first file that is evaluated? Relative to working directory? Going up the directory tree until a `.babelrc` is found?

**Comment by thejameskyle** [comment]
Oh must've missed this somehow, it looks up from the currently compiling file until it reaches a `.babelrc` file

**Comment by rauschma** [comment]
Yes, that’s what I figured after taking a look at the source code. I’ve blogged about my findings: http://www.2ality.com/2015/11/configuring-babel6.html

Feel free to copy anything you want, I can give you access to the Markdown source of the post.
