### ISSUE TITLE
Link each plugin's doc page to its source code

### ISSUE THREAD

**Issue by callumlocke** [babel/babel.github.io#508]
It would be helpful if each doc page linked to its source code within the babel repo.

For example http://babeljs.io/docs/plugins/preset-es2015/ should include a link to https://github.com/babel/babel/tree/master/packages/babel-preset-es2015

**Comment by thejameskyle** [comment]
Sure, wanna make a PR?

**Comment by callumlocke** [comment]
done. also with npm links, mainly because it looks better.

**Comment by tomByrer** [comment]
@callumlocke close?
