### ISSUE TITLE
Create git tag to last v5.x.x commit (before v6)

### ISSUE THREAD

**Issue by zertosh** [babel/babel.github.io#522]
To easily reference the docs for the old version

**Comment by vtambourine** [comment]
Yes, please, it is big pain to search docs for older versions of Babel now.

**Comment by hzoo** [comment]
At the bottom of the site there is a "Looking for Babel 5.x docs?" link to https://github.com/babel/babel.github.io/tree/862b43db93e48762671267034a50c30c00e433e2 if that's suitable

**Comment by vtambourine** [comment]
@hzoo have somebody setup an additional url to that docs? Probably, it will be more useful than running in local.

**Comment by zertosh** [comment]
Didn't notice the link. Good enough for me. Thanks @hzoo!
