### ISSUE TITLE
New User: hackerYou

### ISSUE THREAD

**Issue by Rchristiani** [babel/babel.github.io#525]
Please fill the following out:

- Name: hackerYou
- Homepage url: http://hackeryou.com/
- Logo: http://hackeryou.com/images/logos/logo-hackeryou.svg

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by Rchristiani** [comment]
Added https://github.com/babel/babel.github.io/pull/526
