### ISSUE TITLE
Pull README.md from babel/babel repo packages

### ISSUE THREAD

**Issue by tomByrer** [babel/babel.github.io#528]
eg
http://babeljs.io/docs/plugins/transform-es2015-modules-systemjs/
vs
https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-modules-systemjs
The "via CLI" & "via Node API" are missing.  IMHO README should be the source for the webpage  automated builder.
Added preferred bonus: the web page links to README ("Edit doc contents in README").

**Comment by hzoo** [comment]
Yeah it would be cool to pull in the info from the readme so we wouldn't have to maintain it on both.

**Comment by thejameskyle** [comment]
@hzoo I worked on that a bit this weekend, didn't get very far if you want to give it a shot.

The one requirement is that we need to add `Edit this page` buttons which link to the repo directly.

**Comment by hzoo** [comment]
This is done via https://github.com/babel/babel.github.io/issues/990 but we need to actually move the pages as another issue.
