### ISSUE TITLE
New User: KongGe

### ISSUE THREAD

**Issue by taberh** [babel/babel.github.io#529]
- Name: KongGe
- Homepage url: http://kongge.com
- Brand Guidelines/Licensing: N/A
- Logo: http://img.shenghuozhe.net/shz/2015/11/02/500w_200h_CD9351446450920.png

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by taberh** [comment]
Sure, i created a pull request #531 , and run logo file through ImageOptim
