### ISSUE TITLE
JSX transformation pragma : Inconsistent documentation

### ISSUE THREAD

**Issue by the8tre** [babel/babel.github.io#530]
The doc (http://babeljs.io/docs/plugins/transform-react-jsx/) states :
```json
{
    "plugins": [
        ["transform-react-jsx", { "jsxPragma": "dom" }]
    ]
}
```
But the transformer code does :
`var id = state.opts.pragma || "React.createElement";`

One of the them should be renamed to pragma or jsxPragma.

**Comment by hzoo** [comment]
Thanks! - renamed to `pragma` in https://github.com/babel/babel.github.io/commit/e3c936d1b7bd2d489ebc55b042bead097e31dae4
