### ISSUE TITLE
Add loose mode docs

### ISSUE THREAD

**Issue by ai** [babel/babel.github.io#532]
Babel 5 has awesome loose mode. It is very important, because it can make your code faster.

But there is no docs how to set loose mode in Babel 6. I know that I need to set this option to plugins. But what plugins support it? For example, `transform-es2015-for-of` supports loose, but has no docs about it.

**Comment by tevko** [comment]
+1

**Comment by hbrysiewicz** [comment]
+1

**Comment by hzoo** [comment]
https://gist.github.com/rstacruz/52d2dc4addbfe4681eb8

Yeah we can add a section for it in /plugins and then for each plugin that supports it.

**Comment by balupton** [comment]
Some more follow on resources:

- https://phabricator.babeljs.io/T6987
- http://www.2ality.com/2015/12/babel6-loose-mode.html
- https://github.com/bkonkle/babel-preset-es2015-loose
- https://github.com/bkonkle/babel-preset-es2015-loose/blob/master/index.js

**Comment by hzoo** [comment]
I added plugin options for each one now (if you click on the actual plugin link though, like http://localhost:4000/docs/plugins/transform-es2015-classes/)

**Comment by hzoo** [comment]
Ok each plugin has an explanation from the previous docs now.

ex: http://babeljs.io/docs/plugins/transform-es2015-for-of/

Will close unless anyone thinks we need a special page for it or something else?
