### ISSUE TITLE
v6 Plugin documentation is missing

### ISSUE THREAD

**Issue by isiahmeadows** [babel/babel.github.io#534]
That's pretty critical for us plugin developers. And given the major version change with a lot of breakage, I would at least like to have an idea what all actually changed with the Plugin API.

(BTW it completely disappeared from the website)

**Comment by thejameskyle** [comment]
I'm working on a massive handbook for Babel plugin development right now. I'm writing it as fast as I can so bear with me.

Important changes include:

```js
export function({ Plugin, types: t }) {
  return new Plugin("name", {
    visitor: {
      // ...
    }
  });
}
```

Is now:

```js
export function({ types: t }) {
  return {
    visitor: {
      // ...
    }
  };
}
```

Visitor methods have a new signature:

```js
const Visitor = {
  Type(path) {
    this === visitor state
  }
};
```

Replacing nodes should use `path.replaceWith` and `path.replaceWithMultiple` (among others)

```js
const Visitor = {
  Type(path) {
    return newNode; // no more
  },

  Type(path) {
    path.replaceWith(newNode); // yes
  }
};
```

**Comment by hzoo** [comment]
https://github.com/thejameskyle/babel-plugin-handbook is out now
