### ISSUE TITLE
Plugin "transform-async-to-module-method" has incorrect instructions

### ISSUE THREAD

**Issue by callumlocke** [babel/babel.github.io#536]
The website says [this](http://babeljs.io/docs/plugins/transform-async-to-module-method/):

> ## Usage
> 
> Add the following line to your .babelrc file:
> 
> ```json
> {
>   "plugins": ["transform-async-to-module-method"]
> }
> ```

But as far as I can tell, that never works. You have to do something like this instead:

```json
{
  "plugins": [
    ["transform-async-to-module-method", {
      "module": "bluebird",
      "method": "coroutine"  
    }]
  ]
}
```

**Comment by hzoo** [comment]
Thanks - fixed in https://github.com/babel/babel.github.io/commit/60ded5f76681596ce661ba6d8d1766781e02530a and the next commit
