### ISSUE TITLE
Include corresponding transformer names in the Tour?

### ISSUE THREAD

**Issue by cvrebert** [babel/babel.github.io#54]
The "Standard" entries on https://6to5.org/docs/usage/transformers/ link directly to sections of http://6to5.org/docs/tour/
It might be useful to have the sections of the Tour page mention the names of the corresponding transformers somehow, e.g. have http://6to5.org/docs/tour/#arrows mention `arrowFunctions`

**Comment by sebmck** [comment]
The tour page is currently a fork of [es6features](https://github.com/lukehoban/es6features). I'm a bit hesitant to deviate from it too much and that page is meant to be a general tour of ES6, not 6to5.

**Comment by thejameskyle** [comment]
@sebmck I think it's okay for us to add to that page, but this in particular could likely be better documented on the transformers page.

**Comment by sebmck** [comment]
@thejameskyle Some of the features on the tour page spread over multiple transformers. It'll be difficult to reflect.

**Comment by thejameskyle** [comment]
Yup agreed, I think this one belongs on the transformers page.

**Comment by thejameskyle** [comment]
I was just saying we shouldn't avoid changing that page for the sake of keeping it as similar as possible to the original.

**Comment by sebmck** [comment]
I was more heading towards cluttering it with unnecessary stuff that the page shouldn't be worried about.

**Comment by cvrebert** [comment]
My more general criticism here is how the Transformers page currently hyperlinks directly to a subsection of another page that's not about exactly the same thing, with no further context.

**Comment by hzoo** [comment]
Don't know if we still want to do this
