### ISSUE TITLE
New User: Cuvva

### ISSUE THREAD

**Issue by billinghamj** [babel/babel.github.io#542]
Please fill the following out:

- Name: Cuvva
- Homepage url: https://cuvva.co
- Brand Guidelines/Licensing: none
- Logo: https://imgh.us/full_1.svg

> Example:
>
> Name: CloudFlare
> Homepage url: https://cloudflare.com
> Brand Guidelines/Licensing: https://www.cloudflare.com/logo
> Logo: https://www.cloudflare.com/media/downloads/cloudflare-logo-kit.zip

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by billinghamj** [comment]
Resolved in #606
