### ISSUE TITLE
browser.js now in separate module - no docs on how to get it?

### ISSUE THREAD

**Issue by jamesschauer** [babel/babel.github.io#543]
I understand that that browser.js was pulled out into a separate module (issue 2635, closed a couple of days ago) - but there is no npm install for babel-browser and I'm not sure how to actually get that file (browser.js), the documentation does not seem to be updated? Apologies if I missed something or if it's only a matter of your not having updated the docs yet. Thanks.

**Comment by thejameskyle** [comment]
`babel-browser` is on npm https://www.npmjs.com/package/babel-browser
