### ISSUE TITLE
'use strict' in AMD modules is in wrong place w/ babel 6

### ISSUE THREAD

**Issue by tkissing** [babel/babel.github.io#546]
With babel 5, a "use strict" directive is moved inside the AMD module factory like this:

    define(['exports'], function (exports) {
      'use strict';

With babel 6 it is put before the define call like this:

    'use strict'
    define(['exports'], function (exports) {

This is problematic because chances are that the generated file will be further processed by the rjs optimizer and concatenated with other files, either causing the 'use strict' from this module to bleed into other modules or becoming ineffective, depending on where in the concatenated file the 'use strict' statement ends up.

**Comment by loganfsmyth** [comment]
@tkissing This repo is for documentation issues, could you file this over in https://github.com/babel/babel ?

**Comment by thejameskyle** [comment]
> could you file this over in https://github.com/babel/babel ?

Did this happen? (catching up on issues)

**Comment by hzoo** [comment]
No I don't think so

**Comment by thejameskyle** [comment]
Other repos problem now :clap:
