### ISSUE TITLE
New User: Urban Airship

### ISSUE THREAD

**Issue by jarofghosts** [babel/babel.github.io#552]
- Name: Urban Airship
- Homepage url: https://www.urbanairship.com/
- Brand Guidelines/Licensing: https://urbanairship.box.com/s/as15xdiw8ydl1f5jk8gf8v36kykpq4uv
- Logo: https://urbanairship.box.com/s/8rvnzyvd3vo9bht5hpgoz8xmljlxfo5j

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by jarofghosts** [comment]
https://github.com/babel/babel.github.io/pull/553
