### ISSUE TITLE
Document v6 API

### ISSUE THREAD

**Issue by jmm** [babel/babel.github.io#564]
This issue is to track items that need more documentation and will be updated as time goes on. Items can be split off into their own issues as necessary. 

**NOTE**: To anyone reading this: There is some degree of speculation here about what is public API. This is not the documentation. None of this is confirmed public API until and unless it's documented.
- [ ] Plugins
  - [ ] `inherits` (confirmed public by **sebmck** on slack). [Example](https://github.com/babel/babel/blob/65dc981ce994d6ace57faf83e6db0c3b029cdc76/packages/babel-plugin-transform-react-jsx/src/index.js#L41-L42):
    
    ``` js
    module.exports = function SomePlugin () {
      return {inherits: require("some-syntax-plugin")};
    }
    ```

**Comment by thejameskyle** [comment]
@jmm There's already a list of methods to be documented that @sebmck and I when through. It's everything on this page: https://gist.github.com/thejameskyle/ccc0811f6c8ab4f73ee4

I want to setup [documentation.js](http://documentation.js.org) in the normal codebase to generate API documentation for these methods.

**Comment by jmm** [comment]
@thejameskyle Oh cool, thanks for the link. Would it be better for me to add stuff that's not on that list here, or comment on the gist? For example, `inherits|manipulateOptions|pre|post` keys on the object returned by a plugin?

> I want to setup documentation.js in the normal codebase to generate API documentation for these methods.

I haven't tried it yet, but it sounds interesting.

**Comment by thejameskyle** [comment]
Ah, that will be covered by the handbook I'm writing right now on writing babel plugins. It's just taking a while because writing is hard.

**Comment by jmm** [comment]
@thejameskyle That's awesome! Can't wait to see it.

I need to keep a running list of undocumented parts of the API because it tends to just come out in bits and pieces looking through the source, looking at existing plugins, on slack, etc. If it's not going to bother you I'll do it here (and then when your handbook or whatever documentation comes out boxes can get ticked). If it's somehow unhelpful to you to do it here I'll just create my own repo or something, although if it's here other people can find some of the stuff too.

**Comment by thejameskyle** [comment]
I think the most helpful thing would be documenting the APIs in https://gist.github.com/thejameskyle/ccc0811f6c8ab4f73ee4. That's going to take the bulk of the time. 

I'll open a PR tonight or tomorrow to setup documentation.js in the Babel codebase. (You can also take a crack at it if you want).

I'm also going to try powering through the handbook this weekend, at least enough for an initial version.

**Comment by hzoo** [comment]
https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md is out and I added info on inherits specifically so going to close this one.

Yes we still need some actual docs though
