### ISSUE TITLE
Keep Babel documentation available for different versions of the Babel available on a website.

### ISSUE THREAD

**Issue by jashatton** [babel/babel.github.io#567]
When Babel 6 released the Babel 5 documentation could only be accessed by downloading the commit for latest 5.x version of the Babel site and building it locally.  Having an easy way to get to different versions of Babel's documentation will be very nice.

**Comment by thejameskyle** [comment]
For the most part you can just use this repo for that purpose:

https://github.com/babel/babel.github.io/tree/5.0.0/docs

**Comment by jashatton** [comment]
This is a good interim solution, can the issue be reopened for a better long term solution? 

I was thinking something more browser friendly.  Like a set of links of the http://babeljs.io/ page for various versions of Babel that I can just use from browser without waiting for Github to convert it from markdown to html.  An example I am familiar with is [Gradle](https://docs.gradle.org/current/userguide/userguide.html).  The version is even part of the url, "current" always is aliased, so if I have one project on an older version I can just change the url for that version and I am there.

**Comment by hzoo** [comment]
You can also render it yourself on gh-pages like done here http://developit.github.io/babel-legacy-docs/ (should work)

**Comment by jashatton** [comment]
@hzoo If this results in one location to get to all the "supported" versions of the project's documentation that is cool.  Especially if it is connected in some way that is easy to find with in a couple minutes, preferably from a single official source.

**Comment by thejameskyle** [comment]
People should be completely off of Babel 5 in a matter of a month or two. There's very little reason to stay behind (other than today when there are some bugs). So we're not going to encourage people to stay on Babel 5 forever by keeping the docs up infinitely.

**Comment by jashatton** [comment]
Thanks for the reply and thank you for your contributions to software development community as a whole.  Babel is working out well for us.  To your point, I wouldn't expect to keep them infinitely either.  A couple major version back at most.   

Overall, I agree that keeping up to date is important and any projects that can't, should languish.  However, a successful, long living, OSS project will need to be able to support a wider window of versions.  

I can say, with a reasonable amount certainty, that a majority of the developers. other OSS groups, and companies that could use Babel will not be able to move as quickly as you are suggesting.   A reasonable range probably looks more like a couple months to a year or more depending on the project and it's nature.

**Comment by thejameskyle** [comment]
> I can say, with a reasonable amount certainty, that a majority of the developers. other OSS groups, and companies that could use Babel will not be able to move as quickly as you are suggesting.

Yeah I understand. But it's pretty unlikely that the compiler transform options are going to change any time soon after 6.0.

The breaking changes to be seen in the future are in two places:
- Individual plugins (options, behavior changes to track specs, deprecations as specs die)
- Plugin APIs (ie. babel-traverse/babel-types/etc., not a concern for most users, and also not yet documented)

5.0 would already be completely dead if it weren't for some problems with 6.0 and documentation issues. That's the only reason this issue is even being opened. We've made breaking changes before and the upgrade path has gone much smoother and no one has been left behind.

**Comment by jashatton** [comment]
I understand on the API stability going forward.  I opened it because I
have need to tweak options on 5 and thought I saw a need long term.  The JS
community seems to operate differently than I am use to as a Java
developer.  Part of this is learning and understanding those differences.
I can try other means until our upgrade to maintain what we have until
then.  Thanks again for hearing it out.
