### ISSUE TITLE
New User: FINN.no

### ISSUE THREAD

**Issue by gregersrygg** [babel/babel.github.io#569]
- Name: FINN.no AS
- Homepage url: https://finn.no/
- Brand Guidelines/Licensing: no
- Logo: https://www.dropbox.com/s/lk6nsy46cwz49i3/finn.svg?dl=0

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
