### ISSUE TITLE
Add more info regarding breaking changes introduced in 6.x

### ISSUE THREAD

**Issue by nmai** [babel/babel.github.io#571]
The web is full of tutorials explaining how to use Babel to transpile ES6 to backwards-compatible code. However, they all operate under the assumption that Babel ships with ES6 transformations enabled by default. This makes it [extremely confusing](http://stackoverflow.com/questions/33440405/babel-file-is-copied-without-being-transformed) for users who are new to Babel 6.x.

I'd like for the docs to include a few warnings to help guide users new to 6.x.

**Comment by hzoo** [comment]
I guess this can be closed?

**Comment by nmai** [comment]
I mean, I suppose? I wasn't planning on adding anything else, but I think there's still room for improvement.

**Comment by thejameskyle** [comment]
> I think there's still room for improvement.

If you can open up individual actionable issues that would be more helpful.

**Comment by nmai** [comment]
I totally agree. Having this issue open indefinitely would not be helpful.
