### ISSUE TITLE
New User: TES Global

### ISSUE THREAD

**Issue by aamirafridi** [babel/babel.github.io#576]
- Name: TES Global
- Homepage url: https://www.tes.com
- Brand Guidelines/Licensing: no
- Logo: https://duqxiy1o2cbw6.cloudfront.net/tes/site-assets/888/img/tes-logo.svg

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
