### ISSUE TITLE
Compare: Move React / JSX to new section

### ISSUE THREAD

**Issue by jakecraige** [babel/babel.github.io#58]
Having React and JSX in the "Language Support" section seems weird. Mainly since everything else is new JS features it seems like a cheap shot at the other transpilers because supporting react/jsx is unique to 6to5. 

Perhaps a new section could be added where this could go. I'm don't really have a name in mind.

**Comment by thejameskyle** [comment]
Would moving it to "Features" be okay?

**Comment by Dashed** [comment]
+1 on moving to features. Also, why can't JSX be on its own column? It seems to support some subset of ES6 features; and may support more in the future.

**Comment by thejameskyle** [comment]
@Dashed We're talking about JSX being supported by transpilers, not the Facebook JSX transpiler.

**Comment by Dashed** [comment]
@thejameskyle I know. It was an off-topic suggestion.

**Comment by jakecraige** [comment]
Features seems like a good place for JSX to me.

What exactly does "React" mean in the context of 6to5? I'm guessing that would also belong to Features but I don't really know what it is.

**Comment by sebmck** [comment]
@jakecraige It automatically adds `displayName` to `React.createClass` based on surrounding code, which is exactly what the official JSX/React transformer does.

**Comment by hzoo** [comment]
Going to close since the docs are different now and at least on the plugins page, react has it's own section
