### ISSUE TITLE
Where are babel 5.0 docs?

### ISSUE THREAD

**Issue by chetstone** [babel/babel.github.io#586]
Hi, I'm in the middle of a project and not able to upgrade to babel 6.0 at the moment. I have a question and can't seem to find the old docs anywhere on the web. The pointer on babel.io to the 5.0 docs points to this repo but this does not seem to be a user-friendly place to find information.

**Comment by thejameskyle** [comment]
Just browse the `docs/` folder in the 5.0 branch: https://github.com/babel/babel.github.io/tree/5.0.0

We're not going to host the 5.0 docs on the site. See https://github.com/babel/babel.github.io/issues/567

**Comment by hzoo** [comment]
If you want something nicer you can use developit.github.io/babel-legacy-docs/ otherwise the repo like ^
