### ISSUE TITLE
how to disable "use strict" when use gulp-babel?

### ISSUE THREAD

**Issue by liangzai-cool** [babel/babel.github.io#590]
my js file original content:
![qq 20151120152507](https://cloud.githubusercontent.com/assets/6807169/11294022/e8268ac8-8f9a-11e5-898f-75defc6c2785.png)
but after i use gulp-babel, i got bellow:
![qq 20151120152555](https://cloud.githubusercontent.com/assets/6807169/11294037/05b2d4d4-8f9b-11e5-92d2-fee2c81ad1a2.png)

can i disable 'use strict' the gulp-babel add ? 

i have read some questions look like mine, but i cant not understand.
why babel add 'use strict'?

**Comment by thejameskyle** [comment]
Not the right place for questions on babel
