### ISSUE TITLE
Re-export all causes "To get a node path the parent needs to exist while parsing file"

### ISSUE THREAD

**Issue by hon2a** [babel/babel.github.io#591]
I have the following code:

`file0.js`

    import * from 'file1.js';

`file1.js`

    export * from 'file2.js';

`file2.js`

    export { default as someName } from 'file3.js';
    export { default as someOtherName } from 'file4.js';
    // ...

and I'm trying to compile it with `file0.js` as the root using:

    "babel-core": "6.2.1",
    "babel-preset-es2015": "6.1.18",
    "babel-preset-stage-0": "6.1.18",
    "babel-preset-react": "6.1.18",
    "babel-plugin-transform-object-assign": "6.1.18",
    "babelify": "7.2.0",
    "browserify": "11.2.0",
    ...

The build crashes with the following error:

    /../path/to/file0.js: To get a node path the parent needs to exist while parsing file: /../path/to/file0.js

_I found only a single result on Google and it points to issue that doesn't exist anymore, neither do any other issues linked from there ([here](http://webcache.googleusercontent.com/search?q=cache:XZK3NIuxhj4J:https://github.com/babel/babel/issues/2762+&cd=1&hl=en&ct=clnk&gl=us)'s a cached version), and it's connected just by a comment anyway._

If I `import * from 'file2.js';` in `file0.js` directly, everything's fine, so the issue seems to be the `export * from ...`, which should be valid ES6, at least according to [this article](http://www.2ality.com/2014/09/es6-modules-final.html#re-exporting).

**Is there an issue with `export *`? Is there any work-around or ETA of a fix?**

**Comment by hzoo** [comment]
This is the babel website repo for docs issues - if you have a bug then report it to phabricator.babeljs.io otherwise try stackoverflow/slack

**Comment by hon2a** [comment]
Thanks and sorry for the bother. For anyone coming through here, the issue is tracked [here](https://phabricator.babeljs.io/T2763).
