### ISSUE TITLE
Inconsistent package exports, obsolete docs

### ISSUE THREAD

**Issue by hon2a** [babel/babel.github.io#593]
[Babel core API documentation](https://babeljs.io/docs/usage/api/) shows how to import & use it using Node modules API. Until the recent removal of default exports auto-magic, usage in ES6 environment looked pretty much the same. That isn't true anymore - `babel-core` uses ES6 named exports, so instead of

```
import babel from 'babel-core';
```

I now need to use

```
import { transform } from 'babel-core';
// or
import * as babel from 'babel-core';
```

This doesn't extend to plugin preset packages, however. It'd be helpful if all packages would use either named or default exports (or both). Additionally, if only named exports are used, it might be useful to mention it in the docs.

_I'm using the latest `babel-core` (6.2.0) and packages (6.1.18) and bundling through `browserify` + `babelify`._

**Comment by thejameskyle** [comment]
@sebmck Did you mean for this to be the case?

**Comment by hzoo** [comment]
The docs use require now (also added your examples)

**Comment by hon2a** [comment]
Ok, thanks.
