### ISSUE TITLE
New User: Kogan.com

### ISSUE THREAD

**Issue by choonkending** [babel/babel.github.io#597]
- Name: Kogan.com
- Homepage url: https://www.kogan.com
- Logo: https://assets.kogan.com/files/brand-logos/Kogan-com-600.png

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
