### ISSUE TITLE
Is babel-polyfill more than just a polyfill?

### ISSUE THREAD

**Issue by mikemaccana** [babel/babel.github.io#599]
The docs for https://babeljs.io/docs/usage/polyfill/ are confusing:

> Babel includes a polyfill that includes a custom regenerator runtime and core.js.

Since core.js is a polyfill for the missing methods (String.prototype.includes() etc), what does the 'custom regenerator' add? 

If the 'custom regenerator' does code transformation like babel, wouldn't everybody already be shipping ES5 code that's been transformed by babel? 

In short: if I just need a polyfill, and nothing else (since I'm already using babel during my build process), should I be using `babel-polyfill` or `core.js`?  The current docs do nit make it clear.

**Comment by zloirock** [comment]
If you need just a polyfill - you can use `core-js` instead of `babel-polyfill`. `regenerator/runtime` requires for `regenerator` transform - generators and async functions without native generators. Yes, I think need make docs clearer. I'll try do it when I'll have some time.

**Comment by thejameskyle** [comment]
@mikemaccana What would make the docs more clear?

**Comment by mikemaccana** [comment]
@thejameskyle assuming what @zloirock said is correct:

# Polyfills

## Syntax polyfil

For additional methods provided by ES6 and ES7, use `core-js`. (Add details here)

    require("core-js"); 


## Syntax transforms

If you are not using babel to transform your system as part of your build steps, you can use get *both* the systax transformations and the additional methods with:

    require("babel-polyfill");

**Comment by thejameskyle** [comment]
That's not accurate. You're confusing regenerator runtime with regenerator.

Regenerator compiles code so that it requires a runtime to execute. Which is why we include it in babel-polyfill. The runtime itself does not do anything to transform code.

**Comment by mikemaccana** [comment]
@thejameskyle Acknowledged, re: inaccurate. I'm probably the wrong person for you to ask for replacement suggestions, since the only info I have on babel is the docs.

> You're confusing regenerator runtime with regenerator.

Wow that's confusing. I normally think of 'X runtime' as being synonymous with 'X'

> The runtime itself does not do anything to transform code.

So what does it do?

**Comment by thejameskyle** [comment]
When you compile this code in Babel:

```js
function*foo() {}
```

You get this back out:

```js
"use strict";

var marked0$0 = [foo].map(regeneratorRuntime.mark);
function foo() {
  return regeneratorRuntime.wrap(function foo$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
      case "end":
        return context$1$0.stop();
    }
  }, marked0$0[0], this);
}
```

Now you have a `regeneratorRuntime.wrap()` function that needs to be included for this code to work.

There's plenty of examples of calling this a runtime:
- https://github.com/google/traceur-compiler/wiki/Building-custom-Traceur-runtimes
- http://www.mathworks.com/products/compiler/mcr/
- http://compiler-rt.llvm.org

**Comment by mikemaccana** [comment]
Thanks @thejameskyle . My previous impression was that the ES5 code was plain, I now get what the babel runtime does.

Since most people who use Babel haven't written a compiler before (and since 'runtime' is sometimes used as a synonym for VM) it could also be worth making 'babel runtime' a link explaining the same thing your comment does.
