### ISSUE TITLE
New User: The Ticket Fairy

### ISSUE THREAD

**Issue by purplelight** [babel/babel.github.io#600]
Please fill the following out:

- Name: The Ticket Fairy
- Homepage url: https://www.theticketfairy.com/
- Brand Guidelines/Licensing: N/A
- Logo: https://www.theticketfairy.com/resources/theticketfairy_logos.zip

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
