### ISSUE TITLE
require(false) breaks babel (react validation)

### ISSUE THREAD

**Issue by tolmasky** [babel/babel.github.io#607]
https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=require(false)

repl: r.toLowerCase is not a function. (In 'r.toLowerCase()', 'r.toLowerCase' is undefined)

it seems React validation expects the literal to be a string.

**Comment by thejameskyle** [comment]
Not the appropriate place for bugs in Babel, this is the website repo.

This is also not a problem in Babel 6 as there isn't a react validation plugin anymore
