### ISSUE TITLE
Circular 'typeof' generation on `typeof-symbol`, `spread` and `modules-amd` plugins combination

### ISSUE THREAD

**Issue by jevgenig** [babel/babel.github.io#612]
Combination of three plugins, generates circular "_typeof" call

Files used:

.babelrc
```javascript
{
  "presets": [],
  "plugins": ["transform-es2015-typeof-symbol","transform-es2015-spread","transform-es2015-modules-amd"]
}
````

test.js
```javascript
[].push(...1);
typeof 1 === "object";
```
Executing 
```bash
babel test.js
```

Results in generation of JS which contains (Note ```_typeof(obj)``` self-call in the end of return):
```javascript
  function _typeof(obj) {
    return obj && typeof Symbol !== "undefined" && obj.constructor === Symbol 
           ? "symbol" : typeof obj === "undefined" ? "undefined" : _typeof(obj);
  }
```

Should generate:
```javascript
  function _typeof(obj) {
    return obj && typeof Symbol !== "undefined" && obj.constructor === Symbol 
           ? "symbol" : typeof obj === "undefined" ? "undefined" : typeof obj;
  }
```

Versions
```text
babel 6.2.0
babel-core 6.2.1
plugins 6.1.18
```

If "modules-amd" plugin is excluded, output is as expected

**Comment by loganfsmyth** [comment]
This is not the right place to report bugs, see our README:

> 
> ## Want to report a bug or request a feature?
>
> <p align="center">Bugs and feature requests should be posted at <a href="https://phabricator.babeljs.io/">phabricator.babeljs.io</a>.</p>

This bug is tracked here: https://phabricator.babeljs.io/T6644

**Comment by jevgenig** [comment]
My bad, many thanks!
