### ISSUE TITLE
Setting up mocha

### ISSUE THREAD

**Issue by rauschma** [babel/babel.github.io#614]
This is currently in the docs:

```js
"test": "mocha --compilers js:babel-core/register"
```

IINM, this is better:

```js
"test": "mocha --compilers js:babel-register"
```

**Comment by hzoo** [comment]
Thanks @rauschma - will update the docs accordingly (there's a few other places as well) https://github.com/babel/babel.github.io/blob/master/_includes/tools/mocha/usage.md
