### ISSUE TITLE
"import" instructions moved at top of module may cause runtime error

### ISSUE THREAD

**Issue by happypoulp** [babel/babel.github.io#616]
Hi,

The present issue was reproduced with **babel 5.8.34** and **babel 6.2.0**.

I don't know if this is the intended behavior but using the following code:

```javascript
// File: issue-global-import.js
global.FOO = 'foo'
import anything from './use-foo-global.js'
```

with `use-foo-globals.js` being:
```javascript
// File: use-foo-globals.js
console.log(FOO)
```

... babel transforms `issue-global-import.js` to:

```javascript
'use strict';

var _useFooGlobal = require('./use-foo-global.js');
var _useFooGlobal2 = _interopRequireDefault(_useFooGlobal);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

global.FOO = 'foo';
```

The issue here is that the instruction to require `./use-foo-global.js` was moved **before** the instruction to declare the global variable FOO. This produce a runtime error when executing `issue-global-import.js`.

Is this the expected behavior and if yes, what is the rationale behind it?

Thanks!

PS: I found a workaround by moving the global instruction to its own module `global.js` and then by requiring `global.js` before `./use-foo-global.js` (because babel respect the order between imports) but it feels more like a hack than a real solution.

**Comment by hzoo** [comment]
This is the babel website repo - If you are reporting a bug then use https://phabricator.babeljs.io/ - otherwise I would check out stackoverflow/slack channel for support questions.

Also yes I think this is intentional since imports are hoisted (so it doesn't have to be `global.Foo = 'foo'` could just be like `var a = 1`

**Comment by happypoulp** [comment]
My bad, thanks for the explanation!
