### ISSUE TITLE
New User: LaunchKey

### ISSUE THREAD

**Issue by aenglander** [babel/babel.github.io#617]
Please fill the following out:

- Name: LaunchKey
- Homepage url: https://launchkey.com
- Brand Guidelines/Licensing: (or anything we need to know before using your logo)
- Logo: https://s3.amazonaws.com/launchkey-resources/logo/logo/launchkey-logos_launchkey-horiz-blue.svg

> Example:
>
> Name: CloudFlare
> Homepage url: https://cloudflare.com
> Brand Guidelines/Licensing: https://www.cloudflare.com/logo
> Logo: https://www.cloudflare.com/media/downloads/cloudflare-logo-kit.zip

**Comment by thejameskyle** [comment]
Nice, wanna open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
