### ISSUE TITLE
Decorators in Babel6

### ISSUE THREAD

**Issue by LestaD** [babel/babel.github.io#619]
How can I enable decorators in Babel >= 6?

This code works in babel5 repl

```js
function Hack(classTarget) {
  classTarget.prototype.method = function() {
    console.log("Echo:", this.echo);
  }
}


@Hack
class Random {
  constructor() {
    this.echo = "Entropy";
  }
}


let obj = new Random();
obj.method();
```

But in version 6 i have:

![image](https://cloud.githubusercontent.com/assets/5620073/11607957/df3c550e-9b6c-11e5-941b-558f13a6b874.png)

Babel version: `6.3.13 (babel-core 6.3.13)`
Installed: `babel`, `babel-cli`
Node version: `4.2.1`
OS: OS X 10.11

**Comment by hzoo** [comment]
This is the babel website repo - actually babel issues would be reported in phabracator (https://phabricator.babeljs.io/T2645).  There is also https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy now.
