### ISSUE TITLE
Outdated TCO information

### ISSUE THREAD

**Issue by fkling** [babel/babel.github.io#624]
The documentation says that tail call optimization has partial support:

>  Partial support
> Only explicit self referencing tail recursion is supported due to the complexity and performance impact of supporting tail calls globally.

However, the transform was removed in Babelv6. I would update the docs myself, but I'm not up to date with the reasons why it was removed (which should probably be part of the explanation, like for the other unsupported features).

**Comment by hzoo** [comment]
https://phabricator.babeljs.io/T2614 - yeah I can't find the other places it was mentioned

**Comment by jmm** [comment]
Thanks @fkling! I've been meaning to deal with that (at least create an issue). @hzoo it's on the [Learn ES2015](http://babeljs.io/docs/learn-es2015/#tail-calls) page.

> I'm not up to date with the reasons why it was removed

I'm not totally sure...I think maybe it was too buggy? Anyway, the removal is temporary, as @hzoo indicated with the issue tracking its reimplementation. But the documentation should reflect the current status.

**Comment by hzoo** [comment]
Made a PR https://github.com/babel/babel.github.io/issues/717
