### ISSUE TITLE
New User: Avant

### ISSUE THREAD

**Issue by brettjurgens** [babel/babel.github.io#625]
Name: Avant
Homepage url: https://www.avant.com
Brand Guidelines/Licensing: [BrandGuide_Oct2015.pdf](https://github.com/babel/babel.github.io/files/55907/BrandGuide_Oct2015.pdf)

Logo: [avant.svg.zip](https://github.com/babel/babel.github.io/files/55902/avant.svg.zip)

**Comment by brycedorn** [comment]
:water_buffalo:
