### ISSUE TITLE
for...of cannot be supported by browser

### ISSUE THREAD

**Issue by Rabbit0306** [babel/babel.github.io#627]
The code is just like this:
```javascript
for (const rule of this.props.rules) { // IE cannot support for...of
  const isInvalid = !rule.test.test(this.getValue())
  if (isInvalid === true || isChecked === false) {
    this.setState({ isInvalid: isInvalid, remind: rule.error })
    isChecked = true
  }
}
```

But I run the babel and use the js into IE, it have the expection of **"Symbol is undefined".**

![alt](https://raw.githubusercontent.com/Rabbit0306/123/master/img/issue.png)

**Comment by loganfsmyth** [comment]
Please see our [README](https://github.com/babel/babel/blob/master/README.md):

## Looking for support?

<p align="center">For questions and support please visit the <a href="https://discuss.babeljs.io/">discussion forum</a>, <a href="https://babel-slack.herokuapp.com">Slack community</a>, or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.</p>

This repo is for our website. You just need to load `babel-polyfill`.
