### ISSUE TITLE
Doc about the babel require usage is not clear about the polyfill usage

### ISSUE THREAD

**Issue by maxcnunes** [babel/babel.github.io#640]
Using babel 6 I had to include manually the require for babel-polyfill. That is ok. 
But in the [babel require usage](https://github.com/babel/babel.github.io/blob/master/docs/usage/require.md#usage) says:

> All subsequent files required by node with the extensions .es6, .es, .jsx and .js will be transformed by Babel. The polyfill is also automatically required.

So, reading the docs I understood that I din't need to require the polyfill since it already was automatically required.

**Comment by thejameskyle** [comment]
Docs have been updated
