### ISSUE TITLE
"babel: command not found". Babel is not available when installed locally

### ISSUE THREAD

**Issue by wzup** [babel/babel.github.io#642]
`babel` is not available when installed locally. Error thrown:

```
$ babel react-server.js --out-file react-server-c.js
sh.exe": babel: command not found
```

I want to compile React components. I follow this setup https://babeljs.io/docs/setup/#babel_cli. It says:
> While you can install Babel CLI globally on your machine, it's much better to install it locally project by project.

Ok. I uninstall global `babel`:

```npm uninstall --global babel-cli```

And install `babel` locally in my app:

```npm install --save-dev babel-cli```

Now I have it in my app's `package.json` file:

```
  "devDependencies": {
    "gulp": "^3.9.0",
    "babel-cli": "^6.3.17"
  }
```

And now I do as tutorial says, I run `babel` to compile my file and get an error that `babel` is not found:

```
$ babel react-server.js --out-file react-server-c.js
sh.exe": babel: command not found
```

My system:
"babel-cli": "^6.3.17",
window 8.1
npm 2.5.1
node v0.12.0

**Comment by thejameskyle** [comment]
As explained in http://babeljs.io/docs/setup/#babel_cli under "Usage" you can use npm scripts to solve this problem. Alternatively you can directly reference `./node_modules/.bin/babel`.

**Comment by wzup** [comment]
What if I don't want to use `npm scripts` and want to use plain vanilla cli? Should be covered in docs.

**Comment by thejameskyle** [comment]
See https://github.com/babel/babel.github.io/commit/7706769ba655bab5e36a624bdd4b32d9011ed617

**Comment by nicohvi** [comment]
Hi, love the library! :+1: 

I also ran into this problem recently, and in the [docs](http://babeljs.io/docs/usage/cli/) you still use the `babel` notation which was sort of confusing. The docs literally say "Since it's generally a bad idea to run Babel globally you may want to uninstall the global copy" and then continue to use the global copy, which I think might contribute to the confusion.

**Comment by hzoo** [comment]
Feel free to make a PR. Either overlooked it or we are just using `babel` as a shorthand. If you want we can add a notice above that section saying `babel` is a shorthand for `./node_modules/.bin/babel` or we just replace all of those references to that

**Comment by nicohvi** [comment]
Sure thing @hzoo! :+1:

**Comment by natotthomer** [comment]
Still having this exact issue; uninstalled it globally, then installed it to dev dependencies. Only works when I don't use the shortcut and instead point at the actual node_modules location.

**Comment by hzoo** [comment]
Yeah if you uninstall it globally then there won't be a direct alias to `babel` without using `./node_modules/.bin/babel` or using `babel` as a npm script.
