### ISSUE TITLE
babel cli doesn't write a compiled file into two destinations.

### ISSUE THREAD

**Issue by wzup** [babel/babel.github.io#646]
The goal is to compile a file with a preset (in particularly a React components file) and write it in two destinations:

```
$ babel react-server.js --presets react -o react-server-c.js -o public/js/react/react-server-c.js
```

Of these two destinations only the last `-o public/js/react/react-server-c.js` is written. The first `-o react-server-c.js` is not written.

I tried to use only one option `-o` before both files, no good. Even an error is thrown:
```
$ babel react-server.js --presets react -o react-server-c.js public/js/react/react-server-c.js
public/js/react/react-server-c.js doesn't exist
```

The `-h` says:
`-o, --out-file [out]                 Compile all input files into a single file`

So as I understand, one `-o` means one file. So my first attempt should work, but it didn't. What did I miss? Or is it indeed impossible to write in multiple destinations?

**Comment by loganfsmyth** [comment]
Please see the [README](https://github.com/babel/babel/blob/master/README.md):

> ## Looking for support?
>
> <p align="center">For questions and support please visit the <a href="https://discuss.babeljs.io/">discussion forum</a>, <a href="https://babel-slack.herokuapp.com">Slack community</a>, or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.</p>

Only a single value of `-o` is respected, sorry. If you want a more complex build flow, you could certainly build it with `gulp` though.
