### ISSUE TITLE
docs for writing a plugin, and loading it (possibly in combination with presets)?

### ISSUE THREAD

**Issue by Pomax** [babel/babel.github.io#652]
I tried looking for documentation on how to write a custom babel plugin (I need to preprocess some source so that LaTeX statements with `\` --which will get typeset by MathJax/KaTeX once pages are loaded client side-- get that slash doubled before passing it on to the normal babel processing chain) but I cannot seem to find anything on babel.io for this, nor any documentation on how to combine plugins and presets in an order-preserving way. Do these docs exist and did I just miss them, or do these docs not exist, in which case: could I request them written and added to the site?

**Comment by sparty02** [comment]
https://github.com/thejameskyle/babel-plugin-handbook

**Comment by Pomax** [comment]
Awseome! Can that link be added as big text link, with a side-nav entry, on https://babeljs.io/docs/plugins ? That's the most obvious place I came to on the site in order to discover how to write plugins.

**Comment by sparty02** [comment]
I'm sure PRs are welcome :wink cc @thejameskyle

**Comment by hzoo** [comment]
Sure we could add a link to it somewhere in https://babeljs.io/docs/plugins

**Comment by Pomax** [comment]
I have nowhere near enough free time as it is, so I'm going to have to pass on writing the PR itself =P

(but many things to @thejameskyle for the detailed writeup)
