### ISSUE TITLE
es2015 compilation error for array rest arguments

### ISSUE THREAD

**Issue by yangchenyun** [babel/babel.github.io#655]
```sh
$ cat .babelrc
{
  "presets": ["es2015"]
}

$ cat > script.js
function f2(x, ...y) {
  // y is an Array
  return x * y.length;
}

$ babel script.js --out-file script-compiled.js && cat script-compiled.js
"use strict";

function f2(x) {
  // y is an Array
  return x * arguments.length + 1;
}
```
The compiled code seems to be a optimization when the value of `y` is not needed; but the optimization should be 
```
 return x * (arguments.length - 1);
```

**Comment by jmm** [comment]
Hello @yangchenyun! Thanks for reporting an issue. However, this repo is for website and documentation issues. Please see the `babel/babel` README for where to report issues with Babel. Thanks!

**Comment by yangchenyun** [comment]
Reposted, thanks.
