### ISSUE TITLE
REPL: Improve REPL State Management

### ISSUE THREAD

**Issue by sparty02** [babel/babel.github.io#66]
Currently, the REPL saves its state as an encoded URI in the address bar URL.  This has several drawbacks including things like tricky escaping (i.e. #44) and unfriendly URLs (i.e. #162).

The goal of this enhancement is to leverage an external store for saving REPL state, if desired.  Some requirements:
- URLs for saved REPL sessions should be friendly/short, for easy sharing.
- Persistence should be opt-in (i.e. every REPL session doesn't need to be saved somewhere)
- The persistence of state should be throttled, either by debouncing input or by explicitly asking the user to click a button to 'Save' the REPL state, useful for sharing or returning to at a later time.
- Consider how this ties into local storage persistence (implemented via #77).

_Non requirements/goals_:
- Private persistence (i.e. only certain users can access REPL sessions).  That is way overboard right now.

Some ideas:
- Use the GitHub Gists API to persist REPL input.
- Use the JS Bin API to persist REPL input.

**Comment by hemanth** [comment]
Related [issue](https://github.com/6to5/6to5/issues/423)

**Comment by sparty02** [comment]
relates to #44

**Comment by sparty02** [comment]
@remy I found http://jsbin.com/help/api and http://jsbin.com/help/ajax-requests.  Just want to make sure that JS Bin encourages/tolerates use of it's API for JS persistence.  Or is it more of a 'Pro' option?

**Comment by sparty02** [comment]
Lets stay away from using JS Bin as a storage solution (at least for free).  I think it would be an unnecessary/unfair burden to them.

**Comment by thejameskyle** [comment]
@sparty02 this is currently being worked on: https://github.com/babel/babel.github.io/pull/195
