### ISSUE TITLE
Slight change to documentation

### ISSUE THREAD

**Issue by lee-40square** [babel/babel.github.io#660]
Probably just because I'm new to ES but it wasn't clear to me that I had to put the require() statement at the top, before all other modules. Of course it makes sense in hindsight.

It would be helpful that at http://babeljs.io/docs/setup/#babel_register at Step 3 the wording is changes slightly to make that more clear.

Hopefully I'm not being pedantic.

**Comment by thejameskyle** [comment]
How would you word it?

**Comment by hzoo** [comment]
I think we can include the same change in the polyfill docs - http://babeljs.io/docs/usage/polyfill/

https://github.com/babel/babel.github.io/pull/641

**Comment by lee-40square** [comment]
suggested change:

Add the statement prior to any other `require` statements that will use Babel.

```
require("babel-register");
```

All subsequent files required by node with the extensions `.es6`, `.es`, `.jsx` and `.js` will be transformed by Babel. The polyfill specified in polyfill is also automatically required.
