### ISSUE TITLE
Evaluation should appear as a tabbed new window or a split frame. 

### ISSUE THREAD

**Issue by sheshpai** [babel/babel.github.io#663]
Evaluation appears in the console and overwrites existing window unless we reload it. Going back to 'Try it now' window is a pain.

**Comment by thejameskyle** [comment]
I don't understand what you mean?

**Comment by sheshpai** [comment]
Ok. Let me explain properly.
In "Try it out" when I type small amount of proper javascript and then check on "Evaluate", if my code is proper and there is some output, the output is written in a console that hides my code window and I have to reload babeljs.io and click on 'Try it out' again, and only then I see the console at the bottom in the code window. 
Why not make it seam less like other IDEs and make the console available for output in the same window (as a splitter panel or as a console tab), such that output window (console) is visible to the developer all the time, but executed only if developer has checked the evaluate checkbox. 
I tried with copying and pasting large amount (2-3 page length) of working code, but the behavior is not developer friendly. Execute should not bring up the output that hides my code. Even going back is difficult unless I go back to main url.

**Comment by thejameskyle** [comment]
You just have to uncheck "evaluate" and it goes away...

**Comment by sheshpai** [comment]
I agree. But to uncheck "evaluate" I had to click back arrow on the browser and then click on "Try it out'. Why should I do that! I should have access to 'uncheck' or 'check' evaluate all the time I am on the "Try it out" tab.

**Comment by thejameskyle** [comment]
If you check/uncheck it, it updates automatically. It's on by default because most people want it to be. This is a non-issue.

**Comment by sheshpai** [comment]
I think you did not understand. Of course it gets updated automatically if you check/uncheck it. I am not contesting it. I am not even saying anything about what most people want, because I want that behavior myself.
The problem is "evaluate" label and checkbox itself is not seen because console output covers all tabs including "Try it out", when evaluate checkbox is checked. If you cannot even see the checkbox, then forget about check/uncheck!!  
![screen shot 2015-12-30 at 6 17 20 pm](https://cloud.githubusercontent.com/assets/6180212/12060317/b4d77e74-af21-11e5-817c-846f2be37deb.png)
![screen shot 2015-12-30 at 6 17 35 pm](https://cloud.githubusercontent.com/assets/6180212/12060319/b7167df2-af21-11e5-920a-2b5e4c76a75c.png)

The second screen is visible as soon as I check on evaluate, after which I cannot go back button by clicking on the back button on the browser!!! 
So is it not a non-issue if one cannot even get to the 'Try it out' tab, and get to the evaluate button without retyping http://babeljs.io in the address bar. Of course, I see my code and everything else fine. But, I am surprised everyone else is able to work with this!!!. Strange! Maybe, I am wrong somewhere!

**Comment by thejameskyle** [comment]
Putting this code in an iframe would keep this from being an issue, which is already an issue: https://github.com/babel/babel.github.io/issues/161
