### ISSUE TITLE
Mention that babel-plugin-external-helpers-2 is now babel-plugin-external-helpers

### ISSUE THREAD

**Issue by rauschma** [babel/babel.github.io#664]
https://babeljs.io/docs/plugins/external-helpers/

**Comment by rauschma** [comment]
Or was the package only renamed in the repo? Why choose a directory name that’s not the same as the npm package name?

**Comment by hzoo** [comment]
Same as https://github.com/babel/babel.github.io/issues/658 - didn't publish a new version yet - only merged in master

**Comment by rauschma** [comment]
Got it, thanks!
