### ISSUE TITLE
What's with babel-node in Babel 6?

### ISSUE THREAD

**Issue by ivan-kleshnin** [babel/babel.github.io#665]
I'm trying to update to Babel 6 from Babel 5. ES6 seems to not work at all with this newer `babel-node`. 
I'm completely missing the point of it.

https://babeljs.io/docs/usage/cli/
> $ babel-node -e "class Test { }"

**Block-scoped declarations (let, const, function, class) not yet supported outside strict mode**

> $ echo "let x = 0" > test.js ; babel-node test.js

**Block-scoped declarations (let, const, function, class) not yet supported outside strict mode**

What's wrong? I've tried different combinations like `babel-node test.js --presets stage-1` without any luck.

**Comment by thejameskyle** [comment]
This is not the correct place for support queries, please visit the slack channel. https://slack.babeljs.io
