### ISSUE TITLE
New User: Version One

### ISSUE THREAD

**Issue by walkerrandolphsmith** [babel/babel.github.io#666]
Name: Version One
Homepage: https://versionone.com
Brand Guidlines: http://designv1.com/logo/
Logo: http://designv1.com/wp-content/uploads/2014/12/versionone-logo-horizontal-color.png

**Comment by thejameskyle** [comment]
Awesome, want to open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by walkerrandolphsmith** [comment]
Done, thank you! https://github.com/babel/babel.github.io/pull/677
