### ISSUE TITLE
Babel Blog: Function Bind Syntax <- Wrong link

### ISSUE THREAD

**Issue by muhammadfaizan** [babel/babel.github.io#670]
The blog is redirecting to a page that doesnt exist. 404 error..
Please correct it
Link from where 
https://github.com/babel/babel.github.io/blob/master/docs/plugins/transform-function-bind.md

**Comment by hzoo** [comment]
Thanks for the report - if you use the actual website link (http://babeljs.io/docs/plugins/transform-function-bind/) - it links to http://babeljs.io/blog/2015/05/14/function-bind/
