### ISSUE TITLE
New User: WIX

### ISSUE THREAD

**Issue by LeonFedotov** [babel/babel.github.io#671]
- Name: WIX
- Homepage url: wix.com
- Brand Guidelines/Licensing: http://www.wix.com/about/design-assets
- Logo: http://static.wix.com/server/misc/brand_assets/01.Wix_Horizontal%20Logo%20with%20character.zip

**Comment by thejameskyle** [comment]
Awesome, want to open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by LeonFedotov** [comment]
Sure! what are we basing the order of the logos on?
I mean, can WIX be first, or is it alphabetical?

**Comment by thejameskyle** [comment]
We just add them to the end of the list. You can't be first :stuck_out_tongue_winking_eye:

**Comment by LeonFedotov** [comment]
@thejameskyle :+1: ;)
