### ISSUE TITLE
Add documentation for plugins

### ISSUE THREAD

**Issue by mietek** [babel/babel.github.io#674]
The documentation for the following plugins does not include references to proposals or specifications, or usage examples.

### Misc

- [ ] [external-helpers](http://babeljs.io/docs/plugins/external-helpers/)

#### ES2015

- [ ] [es2015-arrow-functions](http://babeljs.io/docs/plugins/transform-es2015-arrow-functions/)
- [ ] [es2015-block-scoped-functions](http://babeljs.io/docs/plugins/transform-es2015-block-scoped-functions/)
- [ ] [es2015-block-scoping](http://babeljs.io/docs/plugins/transform-es2015-block-scoping/)
- [ ] [es2015-classes](http://babeljs.io/docs/plugins/transform-es2015-classes/)
- [ ] [es2015-computed-properties](http://babeljs.io/docs/plugins/transform-es2015-computed-properties/)
- [ ] [es2015-constants](http://babeljs.io/docs/plugins/check-es2015-constants/)
- [ ] [es2015-destructuring](http://babeljs.io/docs/plugins/transform-es2015-destructuring/)
- [ ] [es2015-for-of](http://babeljs.io/docs/plugins/transform-es2015-for-of/)
- [ ] [es2015-function-name](http://babeljs.io/docs/plugins/transform-es2015-function-name/)
- [ ] [es2015-literals](http://babeljs.io/docs/plugins/transform-es2015-literals/)
- [ ] [es2015-object-super](http://babeljs.io/docs/plugins/transform-es2015-object-super/)
- [ ] [es2015-parameters](http://babeljs.io/docs/plugins/transform-es2015-parameters/)
- [ ] [es2015-shorthand-properties](http://babeljs.io/docs/plugins/transform-es2015-shorthand-properties/)
- [ ] [es2015-spread](http://babeljs.io/docs/plugins/transform-es2015-spread/)
- [ ] [es2015-sticky-regex](http://babeljs.io/docs/plugins/transform-es2015-sticky-regex/)
- [ ] [es2015-template-literals](http://babeljs.io/docs/plugins/transform-es2015-template-literals/)
- [ ] [es2015-typeof-symbol](http://babeljs.io/docs/plugins/transform-es2015-typeof-symbol/)
- [ ] [es2015-unicode-regex](http://babeljs.io/docs/plugins/transform-es2015-unicode-regex/)

#### Experimental

- [ ] [async-to-module-method](http://babeljs.io/docs/plugins/transform-async-to-module-method/)
- [x] [do-expressions](http://babeljs.io/docs/plugins/transform-do-expressions/)

#### Other

- [x] [eval](http://babeljs.io/docs/plugins/transform-eval/)
- [x] [node-env-inline](http://babeljs.io/docs/plugins/transform-node-env-inline/)
- [x] [object-assign](http://babeljs.io/docs/plugins/transform-object-assign/)
- [x] [object-set-prototype-of-to-assign](http://babeljs.io/docs/plugins/transform-object-set-prototype-of-to-assign/)
- [x] [runtime](http://babeljs.io/docs/plugins/transform-runtime/)

**Comment by hzoo** [comment]
Moving to https://github.com/babel/babel.github.io/issues/780
