### ISSUE TITLE
New User: HolidayCheck

### ISSUE THREAD

**Issue by Arturszott** [babel/babel.github.io#675]
- Name: HolidayCheck
- Homepage url: http://www.holidaycheck.com/
- Brand Guidelines/Licensing: -
- Logo: http://www.holidaycheck.com/file/press/1538x288_en.zip

**Comment by thejameskyle** [comment]
Awesome, want to open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by Arturszott** [comment]
Added :)
