### ISSUE TITLE
`const` is read-only

### ISSUE THREAD

**Issue by kristianroebuck** [babel/babel.github.io#679]
This morning I switched branches (from a branch with babel@5, to a branch with babel@6) and performed an `npm install && npm prune`. I then went to run my test suite / development environment and it's completely broken, giving me the following error:

`Module build failed: SyntaxError: file.js: "endpoints" is read-only (This is an error on an internal node. Probably an internal error. Location has been estimated.)`

```
export function myfunction() {
  return async (dispatch, getState) => {
    const endpoints = getState().api.get('endpoints');
    ... // more code here
    const response = await fetch(`${endpoints.get('uploadedMedia')}${id}/`, {
    ... // more code
  }
}
```

This only became an issue this morning, everything was working yesterday without any other changes to my code. If I blanket replace the `const`s to `let`s everything appears to work as normal.

My babel dependencies are:

```
"babel": "^6.3.26",
"babel-core": "^6.4.0",
"babel-eslint": "^5.0.0-beta6",
"babel-loader": "^6.2.1",
"babel-plugin-react-transform": "^2.0.0",
"babel-polyfill": "^6.3.14",
"babel-preset-es2015": "^6.3.13",
"babel-preset-react": "^6.3.13",
"babel-preset-stage-3": "^6.3.13",
```
Any ideas what could have caused this?

**Comment by andrewjbaker** [comment]
Issue is also being discussed at https://phabricator.babeljs.io/T2892

**Comment by jmm** [comment]
Hello @kristianroebuck. This repo is only for website / documentation issues, not support. Please see the [Babel README](https://github.com/babel/babel#looking-for-support) for support resources. Thanks!

**Comment by kristianroebuck** [comment]
@jmm Thanks for pointing me in the right direction.

If anyone finds this page and wants to follow along, the reported issue is @ https://phabricator.babeljs.io/T6970

**Comment by jmm** [comment]
@kristianroebuck You're welcome, but the issue tracker *also* isn't for support :( Did you update your configuration for Babel v6? You show a dependency on several presets, but you don't show that you configure any of them.

**Comment by kristianroebuck** [comment]
I'm not after support, I'm here to report a potential bug. Babel v6 was working until a recent re-install, during this re-install things broke. It's likely that it may have been introduced by Babel, especially judging from feedback from people who are experiencing the same issue. 

https://phabricator.babeljs.io/T6969
https://github.com/cloudfoundry-incubator/cf-abacus/issues/200
https://phabricator.babeljs.io/T2892

**Comment by jmm** [comment]
@kristianroebuck 
> Babel v6 was working until a recent re-install, during this re-install things broke.

That's not what you describe in [T6970](https://phabricator.babeljs.io/T6970). There you say that you switched from Babel v5 to v6 and show a configuration that appears to be for Babel v5. That suggests a strong possibility of misconfiguration.

**Comment by kristianroebuck** [comment]
I say that *switched* from a with babel@5 to a branch with babel@6, which is the reason for re-installing babel@6. I also mention that everything was previously working.

**Comment by jmm** [comment]
> I say that **switched** from a with babel@5 to a branch with babel@6, which is the reason for re-installing babel@6. I also mention that everything was previously working.

Your description is confusing. I interpreted it to mean that it was previously working with v5 and stopped working when you tried running it with v6, which is reinforced by the fact that you show a dependency on a package that doesn't do anything in v6...

```js
"babel": "^6.3.26",
```

...and show configuration for Babel v5:

```json
{
  "stage": 3,
  "env": {
    "development": {
      "plugins": ["react-transform"],
      "extra": {
        "react-transform": {
          "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
          }]
        }
      }
    }
  }
}
```

Babel v6 doesn't even have options such as `stage`, so if you were actually running Babel v6 with that config you'd get errors about unknown options.

You also don't provide a minimal reproduction or even mention how you're invoking Babel.

**Comment by kristianroebuck** [comment]
Apologies for throwing my old babel 5 `.babelrc` file in my mistake. I was rushing as this issue was blocking the whole team.
