### ISSUE TITLE
Babel 6 exporting modules weirdly

### ISSUE THREAD

**Issue by k4zuk0** [babel/babel.github.io#683]
Hi,
First of all, sorry about the issue title, I know it's unclear, but I didn't know how to explain it better...

Anyway. I'm currently working on an express REST API, using Babel to write ES6 code. I've been using it without any trouble until I wanted to start unit testing some stuff.
I was using babel 5, and the only docs I found to use babel with karma required babel 6 (and it seemed like a good idea to get the update).

I've managed to setup babel for the tests (using karma, webpack, jasmine and Phantom). But now, I can't run the actual app...

I run it through a `start.js` file, doing basically what it used to with babel 5, only changed the first require statement

```
require('babel-register');
require('./app.js');
```

But now, the way `export default` statements seem to behave differently.

The 3 first lines of the app.js file are
```
let express = require('express');
let config  = require('./config');

console.log(config);
```
(the console.log here is only here because of the bug, explanation is on its way)

The config.js file only contains
```
let config = {
    app: {
        port: 9120,
        ip: "0.0.0.0",
        env: 'dev'
    },
    elastic: {
        host: 'localhost',
        port: 9200
    }
};

export default config;
```

And the console.log outputs
```
{ default: 
   { app: { port: 9120, ip: '0.0.0.0', env: 'dev' },
     elastic: { host: 'localhost', port: 9200 } } }
```
It's all nested in a `default` field, and it really shouldn't..

Note that if I export it with `module.exports = config;`, it works fine, the output is
```
{ app: { port: 9120, ip: '0.0.0.0', env: 'dev' },
  elastic: { host: 'localhost', port: 9200 } }
```
(but other things break after that, things that didn't break either)

My dependencies (from the `package.json`) are
```
    "babel": "^6.3.26",
    "babel-polyfill": "^6.3.14",
    "babel-register": "^6.4.3",
    "elasticsearch": "^10.0.1",
```

I have the following `.babelrc`
```
{
  "presets": ["es2015"]
}
```

I really can't find out what is happening. I've tried just about everything I found (requiring `babel-core/register`, `babel/register` (that didn't even seem to exist)), and I can't seem to solve this...

**Comment by jmm** [comment]
Hello @k4zuk0 This repo is only for reporting website / documentation issues. Please see the Babel README for support resources. Thanks!
