### ISSUE TITLE
New User: BestPrice.gr

### ISSUE THREAD

**Issue by phaistonian** [babel/babel.github.io#686]
Please fill the following out:

- Name: BestPrice.gr
- Homepage url: http://www.bestprice.gr
- Brand Guidelines/Licensing: (or anything we need to know before using your logo)
- Logo: http://d.pr/i/1g3E2+

**Comment by thejameskyle** [comment]
Awesome, want to open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by phaistonian** [comment]
Thanks James.


Should be done.

—
George Papadakis
@phaistonian
