### ISSUE TITLE
Issues importing a Gulpfile from a node_module.

### ISSUE THREAD

**Issue by benderTheCrime** [babel/babel.github.io#693]
I would not be surprised if Gulp was the culprit or co-culprit in this case, nevertheless, let me fully explain my situation:

I have two projects. One is `npm installed` into the other. These are private packages.

In the dependent repository, I have the following configuration in my package.json:

```
  "babel": {
    "presets": [ "es2015" ],
    "only": [
      "gulpfile.babel.js",
      "**/node_modules/PACKAGE_1/gulpfile.babel.js"
   ],
   "ignore": false
  }
```
Where PACKAGE_1 is the `npm install`ed related repository. The installed package gulpfile is then required into the `gulpfile.babel.js` like so:

```
import gulp from 'gulp';
import registerTasks from 'PACKAGE_1/test';
registerTasks(gulp);
```

When invoked with a task that exists in the installed pakage's gulpfile, the following error is thrown:

```
(function (exports, require, module, __filename, __dirname) { import { argv }
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Module._extensions..js (module.js:478:10)
```

I believe this implies that the installed Gulpfile is not properly registered. There is no Babel configuration in the `npm install`ed package.

Am I missing some key requirement here? When I use `npm link` the process works just fine and independently of one another all of the gulp tasks in either project work. It also (very obviously) works when the gulpfile.babel.js in the installed repository is transpiled.

If this explanation is in any way unclear or confusing (many references to packages, I know) please let me know and I will do my best to sort it out.

**Comment by benderTheCrime** [comment]
I've tried renaming the files so that they do not include "babel" or "gulpfile" with no success.

**Comment by benderTheCrime** [comment]
I've tried adding "use strict" statements to the top of the imported files.

**Comment by benderTheCrime** [comment]
I've tried adding the same Babel configuration to both packages in `package.json`

**Comment by jmm** [comment]
Hello @benderTheCrime. This repo is only for documentation / website issues. Please see the [Babel `README`](https://github.com/babel/babel/blob/master/README.md#looking-for-support) for support resources. Thanks!

**Comment by benderTheCrime** [comment]
Aha...I misread "issues with the website", thanks.
