### ISSUE TITLE
New User: Deezer

### ISSUE THREAD

**Issue by yannickcr** [babel/babel.github.io#695]
- Name: Deezer
- Homepage url: https://www.deezer.com
- Brand Guidelines/Licensing: https://developers.deezer.com/guidelines/logo
- Logo: https://cdns-files.dzcdn.net/developers/WEB_RVB-72dpi.zip

**Comment by thejameskyle** [comment]
Awesome, want to open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
