### ISSUE TITLE
New User: Transloadit

### ISSUE THREAD

**Issue by kvz** [babel/babel.github.io#707]
- Name: Transloadit
- Homepage url: https://transloadit.com
- Brand Guidelines/Licensing: 
- Logo: http://static.transloadit.com/artwork/2015-transloadit-logotext-transblack-light-1639x417.png

**Comment by thejameskyle** [comment]
Awesome, want to open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
