### ISSUE TITLE
New User: BitMEX

### ISSUE THREAD

**Issue by STRML** [babel/babel.github.io#719]
- Name: BitMEX
- Homepage url: https://www.bitmex.com
- Brand Guidelines/Licensing: :shipit: Logo is fair game
- Logo: https://www.bitmex.com/img/bitmex-logo-alt.png

:100: :+1:

**Comment by thejameskyle** [comment]
Awesome, want to open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
