### ISSUE TITLE
New User: Grammarly

### ISSUE THREAD

**Issue by tuxslayer** [babel/babel.github.io#720]
Please fill the following out:

- Name: Grammarly
- Homepage url: https://www.grammarly.com
- Logo: https://d1zw7v9lpbbx9f.cloudfront.net/static/files/997ea3a3690bda688b2a6d7407bb5eb9/logo.svg

**Comment by thejameskyle** [comment]
Awesome, want to open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)
