### ISSUE TITLE
New User: Discord

### ISSUE THREAD

**Issue by jhgg** [babel/babel.github.io#726]
Hey! We use babel too :heart: 

- Name: Discord
- Homepage url: https://discordapp.com/
- Brand Guidelines/Licensing: https://discordapp.com/branding
- Logo: https://discordapp.com/assets/e4923594e694a21542a489471ecffa50.svg

**Comment by thejameskyle** [comment]
Awesome, want to open a PR for it? [Here's some examples](https://github.com/babel/babel.github.io/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+%22New+User%3A%22)

**Comment by hzoo** [comment]
Cool!

**Comment by jhgg** [comment]
Ahha.  Sure.
