### ISSUE TITLE
Recommend babel-polyfill for ES6 compatibility

### ISSUE THREAD

**Issue by eddieburns55** [babel/babel.github.io#733]
Being new to this project, I found it difficult to understand which plugins were needed to set up an environment for ES6. In particular, I didn't realize for a long time that `babel-polyfill` was required for some ES6 features. 

Since `babel-preset-es2015` is already recommended in the setup page, can we also add a recommendation for `babel-polyfill`? I think this paragraph would be a nice place for it: 

> Note: 
> Pre-6.x, Babel enabled certain transformations by default. However, Babel 6.x does not ship with any transformations enabled. You need to explicitly tell it what transformations to run. The simplest way to do this is by using a preset, such as the ES2015 Preset. **(The ES2015 Preset along with babel-polyfill will emulate a full ES6 environment.)** You can install the ES2015 preset with

Thoughts?

**Comment by hzoo** [comment]
Something like that sounds good!

Similar question from slack: https://babeljs.slack.com/archives/discussion/p1457536246003426

> Is there any support for Object.values / Object.entries stage 3 proposal? I've been looking at the plug-ins and can't see anything or any questions about it in the discussion forum.

> allanj: `babel` is only the syntax, for standard library features you need a polyfill. `babel-polyfill` /  `babel-runtime` -> `core-js` contains it https://github.com/zloirock/core-js#ecmascript-7-proposals

> I had thought that everything would be transformed rather than needing a polyfill

**Comment by eddieburns55** [comment]
+1 @hzoo -- that sounds perfect, and would have saved me a lot of confusion

**Comment by hzoo** [comment]
Ok added a note like mentioned in the OP. Will find another way to say in on the other pages. https://github.com/babel/babel.github.io/commit/b45b312d0d2b06756a339bf4eabef01c4ac7e229
