### ISSUE TITLE
Explain how babel looks for .babelrc

### ISSUE THREAD

**Issue by Eein** [babel/babel.github.io#740]
The elusive babelrc has left a few people confused in various projects. 

I'd like to write a pull request to the babelrc guide regarding how babel finds the .babelrc in [this part of the code](https://github.com/babel/babel/blob/93e5c0e64b1a14f3b138a01c55082225084f47b4/packages/babel-core/src/transformation/file/options/option-manager.js#L358):

Many people are creating a babelrc in their home directories for default functionality akin to eslintrc and other rc defaults.

I believe babel is looking for node modules/defaults in the folder that it finds its babelrc in, rather than the project root.

_Just looking for a bit of guidance on whether this should be a bug or a documentation edit._

Searching google for `Couldn't find preset "es2015" relative to directory` finds everything you probably need to see.

Thanks!

**Comment by nitin42** [comment]
I think this answers your question. 

Babel looks for the `.babelrc` file in the current directory of the file that is being transpiled by it. If no such file is found in the cwd, then it traverse the directory tree until it finds the file. At the same time it also looks for the `"babel": {}` in your `package.json` file. This process can be terminated by setting `babelrc: false`.
