### ISSUE TITLE
Babel cut my brackets

### ISSUE THREAD

**Issue by dslpp056193** [babel/babel.github.io#742]
What i use:
``` JSON
"babel-preset-es2015": "^6.6.0",
"gulp-babel": "^6.1.2",
```
What i compile:
``` JS
var path = ( x=> x)();
var someF = (function(x){
    return x + path;
})();
```
**What i get:**
``` JS
var path = function (x) {
    return x;
}();
var someF = function (x) {
    return x + path;
}();
```
**What i need:**
``` JS
var path = (function (x) {
    return x;
})();
var someF = (function (x) {
    return x + path;
})();
```

Where is my brackets?
I searched error half at hour. And very surprised.
Maybe something i do wrong?

Init babel:
``` JS
.pipe(babel({
    presets: ['es2015']
}))
```

**P.S.:** if try this on babel website (inside "try it out") this error not observed

**Comment by loganfsmyth** [comment]
Those brackets are meaningless in the output code so Babel leaves them out.

**Comment by dslpp056193** [comment]
What?
Why meaningless?
(x=>x)() -> Function with auto init.
But
x=>x() -> Is WRONG.

**Comment by hzoo** [comment]
It's removed when generated, so like @loganfsmyth mentioned, it's "meaningless" in the *output* (compiled code). It doesn't do anything to the input code.

**Comment by dslpp056193** [comment]
So, what i should to do?
And, why this work on [babel.com](https://babeljs.io/repl/)?

May be i can use "!function(){}()", but this method is not good as first.

**Comment by loganfsmyth** [comment]
> function(){}() -> Is WRONG.

No it isn't, what about it is incorrect? That is still a self-invoking function, with or without the parens.

Please show a complete snippet that does not execute as expected in Babel 6 if you have one, but that is as expected.

**Comment by dslpp056193** [comment]
I am sorry.
I found the error.
I just not seen "use strict", and in my code i used ``for ( i in paths)``, where ``paths`` is NodeList.
Thanks all for quick answers for my issue, in the future i will meticulously checking my code in order to find true error.

**Comment by dslpp056193** [comment]
I check my error.
# But:
`(function (){})()` — is function expression, but `function (){}()` — is function declaration.
**It is not the same.**

**Comment by loganfsmyth** [comment]
@dslpp056193 It is the same in an expression context, which is the context you are using it in. Babel does include the parens in the declaration case.

This issue queue is for Website documentation issues. If you have further questions, feel free to use our documented support channels: https://github.com/babel/babel#looking-for-support
