### ISSUE TITLE
Can't install babel-core

### ISSUE THREAD

**Issue by datpham23** [babel/babel.github.io#744]
mac 10.11.3

npm i babel-core

npm ERR! node v4.3.2
npm ERR! npm  v2.14.12

npm ERR! notarget No compatible version found: babel-template@'>=6.6.4 <7.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["6.5.0-1","6.2.4","6.6.0","6.3.13","6.5.0","6.0.2","6.2.0","6.0.12","6.3.0","6.1.18","6.0.14","6.0.15","6.0.16","6.1.17"]
npm ERR! notarget

**Comment by hzoo** [comment]
Are you using a a proxy/mirror for npm?

```js
npm view babylon dist-tags
{ latest: '6.6.4', old: '5.8.35', stable: '6.6.0' }
```

Also, this is the babel website repo - check phabricator for issues with babel (https://phabricator.babeljs.io/T7181)

**Comment by datpham23** [comment]
I am using an internal registry. But the issue just started happening today. It wasn't working even installing when installing via the package.json and the version of babel-core hasn't been change in months.

**Comment by hzoo** [comment]
Well its definetely updated on the public registry so not sure what we can do there for that specific case. We're talking about on just pinning dependencies if we can modify all the packages dependencies

     '6.5.0': '2016-02-07T00:06:46.070Z',
     '6.5.1': '2016-02-08T02:18:16.980Z',
     '6.5.2': '2016-02-12T16:30:05.366Z',
     '6.6.0': '2016-02-29T21:12:20.206Z',
     '6.6.4': '2016-03-02T21:29:24.740Z'
