### ISSUE TITLE
[repl] regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/babel.github.io#748]
You can't use generators in the repl because regeneratorRuntime isn't included: http://babeljs.io/repl/#?evaluate=true&presets=es2015&experimental=false&loose=false&spec=false&code=function*%20a()%20%7B%7D&playground=true

**Comment by hzoo** [comment]
@Daniel15 Sounds like we will babel-runtime/polyfill

Sounds like we can also use https://npmcdn.com/babel-standalone@6.x.x as posted in
https://github.com/Daniel15/babel-standalone/issues/14#issuecomment-174976370 Since right now it's at 6.4.4? (Although it's currently showing Babel 6.3.13?)

**Comment by Daniel15** [comment]
Ah, I didn't fully test the "evaluate" option as I never use it myself. I can fix this :)

**Comment by hzoo** [comment]
@Daniel15 What do you think about the npmcdn option? It seems like doing https://npmcdn.com/babel-standalone will get the latest tag, so we wouldn't need to add it to a seperate cdn and update manually. And https://npmcdn.com/babel-standalone@6 or https://npmcdn.com/babel-standalone@6.x.x works too

**Comment by Daniel15** [comment]
That looks interesting, I think I'll switch to npmcdn. Will submit a PR soon :smile:

**Comment by hzoo** [comment]
I haven't used it yet either, but it looks really nice and @mjackson made it :smile:

**Comment by Daniel15** [comment]
Confirmed that @nicolo-ribaudo's URL works fine now. Thanks for reporting this bug! :)
