### ISSUE TITLE
Better error messages when note using async features correctly

### ISSUE THREAD

**Issue by andresn** [babel/babel.github.io#756]
Can we have something more user friendly other than syntax error, unexpected token under these kinds of scenarios:

function main() {
  var quote = await this.getQuote(); // only produces "Syntax error... unexpected token"
  console.log(quote);
}

/\

the correct way (if you didn't catch it):

async function main() {
  var quote = await this.getQuote(); // something like: "use of await method without parent method marked async"
  console.log(quote);
}

**Comment by jmm** [comment]
Hello @andresn. Please mark up code when posting. If you don't know how, please see: https://github.com/substack/node-browserify/wiki/How-to-report-issues-with-browserify#formatting. Also, this repo is for documentation issues. If there's a problem with Babel it needs to be reported on the Babel issue tracker (see the `babel/babel` `README`). If it's an issue with Babylon it now needs to be reported on `babel/babylon`'s GitHub issue tracker.

**Comment by thejameskyle** [comment]
This repo is for Babel website issues only. Please take this to http://phabricator.babeljs.io/

**Comment by andresn** [comment]
Done! And thanks:
https://phabricator.babeljs.io/T7214
