### ISSUE TITLE
rollup-babel needs a different babel preset

### ISSUE THREAD

**Issue by iamale** [babel/babel.github.io#757]
If you select Rollup on [the Setup page](https://babeljs.io/docs/setup/), it still suggests installing the `babel-preset-es2015` preset. Instead, as noted in the `rollup-plugin-babel` [readme](https://github.com/rollup/rollup-plugin-babel#configuring-babel), users should install the `babel-preset-es2015-rollup`. I think this piece of info needs to be included on babeljs.io as well.

**Comment by hzoo** [comment]
Thanks!

Added an entry https://github.com/babel/babel.github.io/blob/master/_includes/tools/rollup/install.md

The other one is a warning so there isn't an easy way to do to it for some
