### ISSUE TITLE
how can i write a plugin in async mode?

### ISSUE THREAD

**Issue by tommyZZM** [babel/babel.github.io#762]
```javascript
export default myplugin = ({ type:t }) => {
       let visitor = {
            stringLiteral ( path ) {
                  asyncfn(path, result =>{
                      // do something async
                      // how can i get these async result into ast tree?
                  })
            }
       }
       return {
            visitor
       }
}
```

**Comment by callumlocke** [comment]
This issue tracker is for issues with the [babeljs.io](http://babeljs.io/) website.

For questions and support please visit the <a href="https://discuss.babeljs.io/">discussion forum</a>, <a href="https://slack.babeljs.io/">Slack community</a>, or <a href="http://stackoverflow.com/questions/tagged/babeljs">StackOverflow</a>.

**Comment by loganfsmyth** [comment]
Babel only supports synchronous transformations, sorry, and as mentioned, this repo is not for support requests.
