### ISSUE TITLE
typo es2015 page presentation

### ISSUE THREAD

**Issue by imatmati** [babel/babel.github.io#763]
Hi, just a typo in your presentation page of es2015 plugin (http://babeljs.io/docs/plugins/preset-es2015/).
You wrote 'All you need to compile ES2015 to ES5', I guess you mean the opposite.
That's all folks and thanks for your work.

**Comment by hzoo** [comment]
Not sure what you mean here, but it should be correct? ES2015 (ES6) is the code you can write in your source and using the es2015 preset will compile it down to ES5
