### ISSUE TITLE
homepage says decorators are supported

### ISSUE THREAD

**Issue by DanLipsitt** [babel/babel.github.io#769]
The "ES2015 and Beyond" checklist on the homepage says "✓ Decorators" but they are [not supported](http://babeljs.io/docs/plugins/transform-decorators/) in the [ES2015 preset](http://babeljs.io/docs/plugins/preset-es2015/) or elsewhere in Babel 6.

**Comment by thejameskyle** [comment]
Parsing them is supported by the Babel parser and transforming them is supported via a plugin https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy
