### ISSUE TITLE
transform-eval Documentation doesn't document what the plugin actually does

### ISSUE THREAD

**Issue by bcowgill** [babel/babel.github.io#770]
I was looking at the various plugins to configure my babel config and this one doesn't tell you what it actually does.

babel.github.io/docs/plugins/transform-eval.md

**Comment by hzoo** [comment]
Thanks for the report (although you probably don't want this plugin anyway :smile:).

It was in the github repo but it's no automatic sync between that and the site so I just updated it https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-eval
