### ISSUE TITLE
Add option to disable ACE editor

### ISSUE THREAD

**Issue by yckart** [babel/babel.github.io#773]
Since ACE is not compatible with all browsers, it would nice if we could switch to plain textareas on the REPL page.

**Comment by thejameskyle** [comment]
What browsers doesn't it support?

**Comment by yckart** [comment]
There are some known problems with text selection, copy & paste and scrolling on desktop and mobile browsers.

- https://github.com/ajaxorg/ace/issues/37
- https://github.com/ajaxorg/ace/issues/2794
- https://github.com/ajaxorg/ace/issues/2662
- https://github.com/ajaxorg/ace/issues/2223
- https://github.com/ajaxorg/ace/issues/1671
- https://github.com/ajaxorg/ace/issues/2872
