### ISSUE TITLE
Add instructions on local setup

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#782]
Add some instructions on local setup if stuff isn't installed

https://github.com/babel/babel.github.io/issues/258#issuecomment-111142413
> $ # install ruby
$ gem install bundler # if ruby hasn't been installed
$ bundle install # if you haven't already
$ gem install jekyll-redirect-from
$ jekyll s

**Comment by sarbbottam** [comment]
I guess instruction to `install ruby` is sufficient followed by existing setup instruction
> [To start the web server on your machine, check out this repo and run make serve.](https://github.com/babel/babel.github.io#setup)

`make serve` will inform the user to install `bundler` and `bundler` takes care of the required dependencies and the below mentioned.

>```
$ gem install bundler # if ruby hasn't been installed
$ bundle install # if you haven't already
$ gem install jekyll-redirect-from
$ jekyll s
```

**Comment by hzoo** [comment]
Ah ok cool @sarbbottam. Would you like to make a PR to the readme for this?

**Comment by sarbbottam** [comment]
Sure.

---

One concern though! *updating the comment ...*

**Comment by sarbbottam** [comment]
@hzoo thoughts?

**Comment by hzoo** [comment]
Well we just need to specify that they install ruby and then `make serve` right? I haven't used jeykll much so I didn't know. We can add a warning if you want
