### ISSUE TITLE
question: issues/request related to docs

### ISSUE THREAD

**Issue by sarbbottam** [babel/babel.github.io#784]
There are couple of [issues/request related to docs](https://github.com/babel/babel.github.io/issues?q=is%3Aopen+is%3Aissue+label%3Adocs), isn't [thejameskyle/babel-handbook](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md#toc-documentation) the answer to those?

Should [those issues](https://github.com/babel/babel.github.io/issues?q=is%3Aopen+is%3Aissue+label%3Adocs) be closed with reference to [thejameskyle/babel-handbook](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/user-handbook.md)

cc/ @thejameskyle

**Comment by hzoo** [comment]
They could be - it's fine to leave here
