### ISSUE TITLE
export default class being misinterpreted

### ISSUE THREAD

**Issue by zwhitchcox** [babel/babel.github.io#794]
According to the ES6 spec

```
ExportDeclaration: export default ClassDeclaration
    Let names be BoundNames of ClassDeclaration.
    Let localName be the sole element of names.
    Return a new List containing the Record {[[ModuleRequest]]: null, [[ImportName]]: null, [[LocalName]]: localName, [[ExportName]]: "default"}.
where [[ExportName]] (in this case default) - name used to export this binding by this module.
```

```js
export default class MyClass () { }
```

should not export `MyClass` by name. In other words I should not be able to do this with the above code:

```js
import { MyClass } from './myclass'
```

However, as it currently stands, this works. You should have to do this:

```js
export class MyClass () { }
export default MyClass 
```

if you want to be able to import a class as both a default and named class. I personally like how it stands now, but I just wanted to bring this to attention and ask why we chose to do it this way. Typescript actually does it the way specified in the ES6 spec, and I was wondering what the reasoning was of going off course of the spec.

**Comment by hzoo** [comment]
Thanks for reporting! However repo is for reporting issues/suggestions on our website, http://babeljs.io/, not for bugs in babel or support.

If you have an an actual bug/suggestion for babel itself - free feel to make an issue on our [phabricator](https://phabricator.babeljs.io/). If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
