### ISSUE TITLE
ES2015 preset doesn't consist 'babel-plugin-transform-flow-strip-types'

### ISSUE THREAD

**Issue by Beingbook** [babel/babel.github.io#799]
Babel introduction page briefs like `es2015-preset` has `babel-plugin-transform-flow-strip-types`.

<img width="498" alt="2016-04-13 2 07 51" src="https://cloud.githubusercontent.com/assets/2682865/14483358/28d25cfc-0181-11e6-9dc0-27ef65f3e0cb.png">

The link connected to `babel-plugin-transform-flow-strip-types` but it doesn't. I had to install the plugin to parse it.

exponent operator is also.

**Comment by hzoo** [comment]
Thanks for the report! The list of plugins on the left are supposed to correspond to all the available es201x plugins and the heading "ES2015 and beyond". Yes it's not intended to be included. (not just flow types, but anything else in the stage-x presets)

I can see how it can be confusing though. Do you have a suggestion?

**Comment by Beingbook** [comment]
There's need 5 columns to separate es2015, stage-1, stage-2, stage-3, syntax-parser.
As plugin page introduces about each preset's meaning, it needs minimized descriptions of proposal/draft/candidate for the columns.

**Comment by hzoo** [comment]
And all of this on the homepage? Not sure if that will fit correctly/succinctly

**Comment by Beingbook** [comment]
You are true. We can't know how standard spec will go. Then how about just adding other preset install scripts? It will make people think installing `es2015-preset` is not enough to bring all features.

**Comment by hzoo** [comment]
I think can't of a good way to do this atm. The heading does say "ES2015 and beyond" and since its the homepage I don't think we wanted to put everything there - the plugins page does have more information

**Comment by hzoo** [comment]
Going to close for now
