### ISSUE TITLE
babel-preset-es2015 anonymous function

### ISSUE THREAD

**Issue by kollors** [babel/babel.github.io#800]
this code in ES6
~~~~~
{
    constructor() {
        console.log('Banana');
    }
}
~~~~~
converts to incorrect code in ES5
~~~~~
{
    constructor: function constructor() {
        console.log('Banana');
    }
}
~~~~~
but anonymous function should be anonymous and this causes recursion in Angular2.0.0-beta.14 on ES5

**Comment by jmm** [comment]
Hello @kollors. This issue tracker is for issues with the website / documentation. If there's a problem with Babel please report it on its issue tracker. That's part of the ES2015 function name inference behavior. I believe the method definition transform is supposed to do something special to account for that if the same identifier used for the function is used inside the function. If it's not doing that, it might be a bug, but this example doesn't show one way or the other.
