### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by marcobiedermann** [babel/babel.github.io#804]
Currently `http` does not redirect to `https`on babeljs.io
This causes duplicated content and is not good for SEO.

Also `https://www.babeljs.io/` gets redirected to `http://babeljs.io/`

**Comment by hzoo** [comment]
Is this someone we can change on github? probably not right?

**Comment by thejameskyle** [comment]
I could force it through CloudFlare but there was some issue with a couple people in china that couldn't access the site.
