### ISSUE TITLE
link to slack is https://slack.babeljs.io/ and should be https://babeljs.slack.com

### ISSUE THREAD

**Issue by jeromeetienne** [babel/babel.github.io#805]
- im no expert into slack, but https://slack.babeljs.io got some issue
  - always asks me for an invite, even if im already invited
  - it doesnt allow me to login with my account

- https://babeljs.slack.com seems to fix all those issues

**Comment by loganfsmyth** [comment]
https://babeljs.slack.com doesn't provide a way to register though, only log in, from what I can see.

**Comment by thejameskyle** [comment]
Yeah, no it should be slack.babeljs.io

**Comment by jeromeetienne** [comment]
even if https://slack.bablejs.io doesnt allow to login ?

if you guys controls this page, maybe simply add a button 'login' which would allow to login ?
