### ISSUE TITLE
"isCompatTag" possibly incorrectly trapping non strings in "plugin-transform-react-jsx"

### ISSUE THREAD

**Issue by cjke** [babel/babel.github.io#806]
Given the very simple example below:

```
const Foo = () => <div>Hello World</div>;

// Doesn't work
const item = Foo;
<item />

// Does work
const item2 = { type: Foo };
<item2.type />
```

This is babelified into:

```
var Foo = function Foo() {
  return React.createElement(
    "div",
    null,
    "Hello World"
  );
};
var item = Foo;
React.createElement("item", null);

var item2 = { type: Foo };
React.createElement(item2.type, null);
```

The problem above being that `item` is "seen" as a string literal, and transpiled as such. Whereas if I wrap it in an object, it correctly resolves.

Digging through the source, it seems to be (maybe) at the point in `plugin-transform-react-jsx` where the stringLiteral is pushed into the args array, because `isCompatTag` is returning true. 

Is this due to fact that it's (maybe) impossible to tell if `item` is actually just a string, or if it's indeed pointing through to something else? If so, is the recommended way to object wrap stuff?

The above is a super simplified example to narrow down the issue (if it is one) - in the above case I could obviously just put `<Foo />`. 

Cheers

**Comment by loganfsmyth** [comment]
JSX tags that are components need to be capitalized, if they are lower cased, they are treated as HTML tag names, which is the behavior you are seeing. Just do

```
const Item = Foo;
<Item />
```

Also in the future, this is the repo for Babel's website, see our README: https://github.com/babel/babel#want-to-report-a-bug-or-request-a-feature Bugs in Babel should be reported on https://phabricator.babeljs.io/

**Comment by cjke** [comment]
Gotcha, I misread the README. And thanks for clarifying the issue I was seeing
