### ISSUE TITLE
Are in-browser transforms supported?

### ISSUE THREAD

**Issue by zodiac** [babel/babel.github.io#807]
I'm currently using `browser.js` from https://cdnjs.com/libraries/babel-core, which seems to do in-browser JSX transform. So I can load a document like https://gist.github.com/zodiac/e6af239430f4652d849d63ecf47eb628 in the browser directly without an intermediate build step: 

Is this the "babel-browser" that https://babeljs.io/docs/usage/browser/ refers to? If so, since it has been removed, is it possible to use current babel to achieve the same effect?

**Comment by zloirock** [comment]
You can use https://github.com/Daniel15/babel-standalone

**Comment by zodiac** [comment]
@zloirock 

> Upd: Stop, it's mentioned in the documentation, so that's the problem?

The documentation is not clear. It says "babel-browser has been removed", and I don't know what babel-browser is unless I had used in in babel 5 before. If the babel project does not support this use case your documentation should reflect that

**Comment by zloirock** [comment]
It's documentation for `babel@6`, I don't think here should be notes about `babel@5` and it looks enough clear for me.

**Comment by zodiac** [comment]
> it looks enough clear for me.

I disagree - when I visit that page and see the line "babel-browser has been removed", I don't know what babel-browser is.

**Comment by hzoo** [comment]
Ok we can add a note that babel-browser (from babel 5) was removed

**Comment by thejameskyle** [comment]
`babel-browser` was never in Babel 5, it was just `babel-core/browser.js` and then it was pulled into a package and then deprecated.

**Comment by zodiac** [comment]
@thejameskyle 

see, a new user doesn't have all that context so the "babel-browser has been removed" is useless to them

I would prefer the page to say something like "Babel used to provide an in-browser transform but no longer does so. We only support the cli. If you really want in-browser transform, here is a third-party tool that can do that"

**Comment by hzoo** [comment]
If you want to make a PR, it would be appreciated
