### ISSUE TITLE
Use babel series manually.

### ISSUE THREAD

**Issue by yesvods** [babel/babel.github.io#809]
Inspired by the [babylon handbook](https://github.com/thejameskyle/babel-handbook)
* I want to parse code, traverse code and generate code step by step.
* Or just want to transform the "arrow-functions" in browser runtime.

Babylon and babel-generator are simple to use.But babel-traverse is somehow confused to me.
How can I do that?

**Comment by jmm** [comment]
Hello @yesvods FYI this issue tracker isn't used for how-to questions. Are you requesting some kind of update to the documentation?

**Comment by yesvods** [comment]
Sorry, I will close this issues.
