### ISSUE TITLE
'only' and 'ignore' do not work as expected

### ISSUE THREAD

**Issue by wotsyula** [babel/babel.github.io#814]
Documentatio at: http://babeljs.io/docs/usage/options/ is misleading. Looking at the code from

https://github.com/babel/babel/blob/master/packages/babel-core/src/util.js#L114

If `only` setting is set then `ignore` is completely ignored. Documentation should reflect this to prevent anyone from accidentally attempting to use both settings which would lead to a hard to identify error.

Also I don't want to open a phabricator account so could someone bring this up on the chat / buglist / feature list for me.

Thanks.

**Comment by jmm** [comment]
It pretty much stands to reason that you wouldn't whitelist something only to blacklist it and that whitelisting is more explicit than blacklisting, but I don't see a problem with being specific. We can just say that `ignore` is disregarded if `only` is specified.

> Also I don't want to open a phabricator account so could someone bring this up on the chat / buglist / feature list for me.

I don't blame you, but:

1. I think you can sign in to the Phabricator with your GitHub account.
1. This is the buglist for the documentation, so this is actually the correct place. If you thought there was a bug in the behavior of the options the Phabricator tracker would be the right place.

**Comment by wotsyula** [comment]
@jmm Yes a small footnote would help. We don't want people wondering why its not working now do we. Any Idea when the change will make it into the documentation so I can close this?

**Comment by niftylettuce** [comment]
👎
