### ISSUE TITLE
Usage rendering issue in `React constant elements transformer`

### ISSUE THREAD

**Issue by Bartozzz** [babel/babel.github.io#818]
<img width="393" alt="zrzut ekranu 2016-05-05 o 13 00 38" src="https://cloud.githubusercontent.com/assets/6741707/15042101/76018682-12c1-11e6-8263-051b4b5fdd2d.png">

Link: http://babeljs.io/docs/plugins/transform-react-constant-elements/
Issue: Missing ` at the end - the JSON code doesn't render properly.

**Comment by hzoo** [comment]
Thanks, fixed - next time feel free to submit a PR!
