### ISSUE TITLE
Learn ES2015 docs - Incorrect value for example "Default + Rest + Spread"

### ISSUE THREAD

**Issue by xvash** [babel/babel.github.io#823]
```
function f(x, ...y) {
  // y is an Array
  return x * y.length;
}
f(3, "hello", true) == 6
```

This should be:
`f(3, "hello", true) == 5`

Since spread applies to the last two arguments.

**Comment by hzoo** [comment]
It should be correct

![screen shot 2016-05-17 at 2 43 55 pm](https://cloud.githubusercontent.com/assets/588473/15334843/d460f002-1c3d-11e6-9e90-ca9c5c699d8e.png)

**Comment by xvash** [comment]
@hzoo go to "try it out", it compiles to the following ES5:
function fun(x) {
  return x + (arguments.length - 1);
}

fun(3, true, 'blah') === 5;

**Comment by hzoo** [comment]
![screen shot 2016-05-17 at 2 48 00 pm](https://cloud.githubusercontent.com/assets/588473/15334975/6161b20c-1c3e-11e6-9e6c-bd382298be54.png)

it compiles to `x * (arguments.length - 1)` which is 3 * (3-1) = 3 * 2 = 6

**Comment by xvash** [comment]
you're right, I overlooked.  will close.

**Comment by hzoo** [comment]
Thanks for checking
