### ISSUE TITLE
Temporal Dead Zone

### ISSUE THREAD

**Issue by anirudh-modi** [babel/babel.github.io#826]
In ES6 it was mentioned, that if we try to access a variable declared using `let` or `const` before it is declared it will throw Reference error, however when I try to do so,  dont get any error

https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015&code=%0A%20%20console.log(a)%3B%0A%20%20%0A%20%20const%20a%3D1%3B

In the above output it is visible that no error are thrown and it silently console prints undefined. Should not it throw some error?

**Comment by Runju** [comment]
i run flowing code in chrome,it throw a ReferenceError
```javascript
if(true) {
  tmp = 'abc';
  console.log(tmp);

  let tmp;
  console.log(tmp);

  tmp = 123;
  console.log(tmp);
}
```
but it babel,it show me a result
```javascirpt
abc
undefined
123
```

**Comment by infinnie** [comment]
```javascript
{typeof a; let a}
```

An error should be thrown in an ES6 environment, but not here in Babel-transpiled JavaScript.
Throw either a compile-time error or a runtime one please.

**Comment by hzoo** [comment]
So the repl doesn't turn on the tdz option so you have that error.

With
```
{
  "plugins": [
    ["transform-es2015-block-scoping", {"tdz": true}]
  ]
}
```

you will get 

```
console.log(function () {
  throw new ReferenceError("a is not defined - temporal dead zone");
}());
var a = 1;
```

instead of

```
console.log(a);
var a = 1;
```

Will make a docs change for that plugin
