### ISSUE TITLE
Link to CLI is broken

### ISSUE THREAD

**Issue by dlahyani** [babel/babel.github.io#829]

**Comment by jmm** [comment]
Hi, where is the link?

**Comment by hzoo** [comment]
More information would be helpful (either for us to fix this or if you want to give it a shot).

Thanks for the issue; If you'd like we would appreciate a pull request!

<img width="562" alt="screen shot 2016-05-27 at 9 52 47 pm" src="https://cloud.githubusercontent.com/assets/588473/15624417/756a59ce-2455-11e6-822f-0494dac3223b.png">

Most pages have a `Edit this page` link under the subtitle that should link you directly to the correct page.

<img width="1112" alt="screen shot 2016-05-27 at 9 53 44 pm" src="https://cloud.githubusercontent.com/assets/588473/15624419/8559c2fc-2455-11e6-8830-fc7dbd9ba2bf.png">

Then you can click the pen icon to `edit the page` if you have a github account. It will bring you to a page with an inline editor where you can make a change and a commit message and eventually create a pull request

<img width="751" alt="screen shot 2016-05-27 at 9 54 59 pm" src="https://cloud.githubusercontent.com/assets/588473/15624430/c5241dc4-2455-11e6-87e2-1f126e382421.png">

If you need help or can't at the moment, just let us know.

**Comment by hzoo** [comment]
Closing for now
