### ISSUE TITLE
Curated Plugin List

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#831]
Maybe we want to do this instead a super small line I added to search for npm

`Many other community maintained presets are available on npm!` http://babeljs.io/docs/plugins/

**Comment by thejameskyle** [comment]
That would be good 👍

**Comment by hzoo** [comment]
Mostly through searching [github](https://github.com/search?l=JavaScript&o=desc&q=babel-plugin-&s=stars&type=Repositories&utf8=%E2%9C%93) and [npm](https://www.npmjs.com/search?q=babel-plugin-)

Should probably be part of our babel/maintained
- https://github.com/59naga/babel-plugin-add-module-exports
- https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy

Specific to a library
- https://github.com/gaearon/babel-plugin-react-transform of course (348k/m)
- https://github.com/lodash/babel-plugin-lodash
- https://github.com/istarkov/babel-plugin-webpack-loaders
- https://github.com/nkt/babel-plugin-react-remove-prop-types
- https://github.com/jridgewell/babel-plugin-incremental-dom

Interesting stuff like
- https://github.com/yahoo/babel-plugin-react-intl
- https://github.com/dtinth/babel-plugin-__coverage__
- https://github.com/speedskater/babel-plugin-rewire
- https://github.com/codemix/babel-plugin-typecheck
- https://github.com/marten-de-vries/kneden (aka babel-plugin-async-to-promises

**Comment by mathiasbynens** [comment]
https://github.com/mathiasbynens/babel-plugin-transform-unicode-property-regex compiles [Unicode property escapes](https://github.com/mathiasbynens/regexpu-core/blob/master/property-escapes.md) (`\p{}` and `\P{…}`) in Unicode regular expressions to ES5 or ES6 (!) that works in today’s environments.

**Comment by ctrlplusb** [comment]
https://github.com/gcanti/babel-plugin-tcomb
Babel plugin for runtime type checking using tcomb

**Comment by 03eltond** [comment]
https://bitbucket.org/amctheatres/babel-transform-imports
For libraries which support pulling in modular components, such as react-bootstrap and lodash:

```javascript
import Grid from 'react-bootstrap/lib/Grid';
```

But you'd have to write a line for each item you want to pull in, where it is more convenient to write:

```javascript
import { Grid, Button, Row, Col } from 'react-bootstrap';
```

But this causes the entire library to then be pulled in during transpile.  This plugin allows you to write the latter syntax, without causing an import of the entire library (useful for minimizing webpack bundle sizes)

**Comment by ctrlplusb** [comment]
FYI the `babel-plugin-tcomb` I posted earlier is soon to support flow syntax properly so that you can have both static and runtime type checking.

**Comment by xtuc** [comment]
There is an [awesome-babel](https://github.com/dustinspecker/awesome-babel) but he has just a few links in it.

Could be a community driven dedicated website page ?

**Comment by hzoo** [comment]
The website docs are feel to be PR'd - we can have a page for it
