### ISSUE TITLE
Version 6.9.1 of babel-runtime is broken

### ISSUE THREAD

**Issue by pavel-dohnal-momentumft** [babel/babel.github.io#833]
After update from version 6.9.0 to version 6.9.1 my code started failing.

The line in transpiled code is: 
```
return _regeneratorRuntime.async(function waitForService$(context$2$0) {
```

The line in original code is:
```
async waitForService(service, privatePort) {
```

And the error is:
```
TypeError: Cannot read property 'async' of undefined
```

**Comment by hzoo** [comment]
Check 6.9.2, 6.9.1 isn't the latest.

Thanks for reporting! However repo is for reporting issues/suggestions on our website, http://babeljs.io/, not for bugs in babel or support.

If you have an an actual bug/suggestion for babel itself - free feel to make an issue on our [phabricator](https://phabricator.babeljs.io/). If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).
