### ISSUE TITLE
transform-inline-environment-variables fails for react-native

### ISSUE THREAD

**Issue by alexprice91** [babel/babel.github.io#847]
Using `transform-inline-environment-variables` on react-native fails when bundling with `dev=false`.

This is because [this](https://github.com/facebook/react-native/blob/master/local-cli/bundle/buildBundle.js#L28) uses `process.env.NODE_ENV = args.dev ? 'development' : 'production';` which throws the error:

```
TypeError: react-native/node_modules/react-native/local-cli/bundle/buildBundle.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "StringLiteral"
```

The only way I was able to get this error to go away was to remove the process.env.NODE_ENV assignment. Any help?

**Comment by hzoo** [comment]
This is the babel website repo, you can report an issue on https://github.com/babel/babel/issues/
