### ISSUE TITLE
Learn ES2015 __proto__ error

### ISSUE THREAD

**Issue by jmm** [babel/babel.github.io#854]
I think the docs on `__proto__` [here](https://github.com/babel/babel.github.io/blob/020385d2624bf838a0265f622c5ef88446608293/docs/learn-es6.md#enhanced-object-literals) have a mistake. It has this:

```js
var obj = {
    // __proto__
    __proto__: theProtoObj,
    // Does not set internal prototype
    '__proto__': somethingElse,
```

I don't think that's correct about *Does not set internal prototype* and in fact I think the example is a syntax error. I believe it means to have this:

```js
    // Does not set internal prototype
    ['__proto__']: somethingElse,
```

**Comment by loganfsmyth** [comment]
Are you saying "I think the example is a syntax error" because it's a duplicate key?

I think I agree with your interpretation of http://www.ecma-international.org/ecma-262/6.0/#sec-__proto__-property-names-in-object-initializers though, since the string-based key is still a non-computed string value.

**Comment by jmm** [comment]
@loganfsmyth Thanks for taking a look.

> Are you saying "I think the example is a syntax error" because it's a duplicate key?

Yeah, not because it's a duplicate key in general, but because of the early error rule:

> It is a Syntax Error if `PropertyNameList` of `PropertyDefinitionList` contains any duplicate entries for `"__proto__"` and at least two of those entries were obtained from productions of the form `PropertyDefinition : PropertyName : AssignmentExpression` .

**Comment by loganfsmyth** [comment]
Cool, agreed.

**Comment by jmm** [comment]
:+1: thanks, I'll update it soon.
