### ISSUE TITLE
Docs: Using Modules

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel.github.io#86]
Details about bundling modules with browserify/webpack/etc. ie. `modules: system` only transpiles to the system.js syntax but doesn't bundle them with system.js

**Comment by benvds** [comment]
As commented in https://github.com/babel/babel/issues/843:

> I've been busy for over an hour reading the docs and now the issues finding out why I can't compile modules but still can't find the answer.
> 
> What I personally gather from the documentation is that I shouldn't need browserify anymore to gather the dependencies. I'm just trying to get the simplest build possible working through the CLI but the only result I see is some formatting.
> 
> I'd really like to see the FAQ beefed up and see this thing answered. Also I'd like to see some extremely simple working examples without the use of build systems.

**Comment by sebmck** [comment]
No you still need to use browserify. What gave you the assumption that you didn't? Babel turns ES6 module syntax into the format of another module loader. It can't just make it work, how are you expecting it to?

**Comment by benvds** [comment]
Reading the module docs it says:

> babel has the ability to transpile ES6 modules to the module system of your choice

"the ability" which means to me it's optional. Because modules are part of es6 i'd expected to be solved through a polyfill which should be automatically loaded for `babel-node`.

**Comment by sebmck** [comment]
@benvds By default it'll transpile ES6 modules into CommonJS which will work just fine in node, browserify and webpack so there's no polyfill required.
