### ISSUE TITLE
Error on extending promise.

### ISSUE THREAD

**Issue by hemanth** [babel/babel.github.io#867]
```js
class Meow extends Promise {
    constructor(cat) {
        super((resolve, reject) => {
            return cat;
        });
    }
}

let m1 = new Meow('cat');
```

Says: `#<Meow> is not a promise` on `chrome` and `opera` 

Ref: https://is.gd/eJ8AAG

**Comment by zloirock** [comment]
[`babel` does not support extending built-in constructors by default.](https://babeljs.io/docs/usage/caveats/#classes) Also, it's an incorrect place for `babel` or `core-js` issues.

**Comment by hemanth** [comment]
@zloirock I didn't find the issues tab in `babel/babel`

**Comment by zloirock** [comment]
@hemanth https://phabricator.babeljs.io/
