### ISSUE TITLE
babel-plugin-transform-runtime conflicts with babel-plugin-transform-proto-to-assign

### ISSUE THREAD

**Issue by Rendalf** [babel/babel.github.io#868]
When I use two plugins together `proto-to-assign` does not work.
I think because `proto-to-assign` can't convert code from `babel-runtime`.
Code compiled with these two plugins does not work in IE10

**Comment by hzoo** [comment]
This is the babel website repo - I would report this in https://github.com/babel/babel/issues/ (and search if there's already one made. thanks!
