### ISSUE TITLE
Docs: React preset docs have links that result in 404

### ISSUE THREAD

**Issue by snoda** [babel/babel.github.io#872]
On http://babeljs.io/docs/plugins/preset-react/, there are links to the cli and usage docs, which point to http://babeljs.io/docs/plugins/preset-react/docs/setup and http://babeljs.io/docs/plugins/preset-react/docs/usage/cli/, respectively. Both of these result in a 404 Page Not Found.

**Comment by hzoo** [comment]
Thanks!
