### ISSUE TITLE
Markdown bug in plugins/transform-es2015-modules-commonjs

### ISSUE THREAD

**Issue by jmm** [babel/babel.github.io#874]
There's a problem with the markdown in the Babel 6 Changes section at the top. It's rendering:

```
use [babel-plugin-add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports)
```

http://babeljs.io/docs/plugins/transform-es2015-modules-commonjs/

More importantly, I don't think we should point people to that plugin without warning them that:

1. It may not match how Node eventually implements ES modules natively. The way the [current proposal](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#55-commonjs-consuming-es) is shaping up, my understanding is that it would not match.

1. It will break as soon as any non-default export is added.

**Comment by hzoo** [comment]
Good idea

**Comment by jmm** [comment]
@hzoo Yeah, that's what I mean in # 2 -- if you start out with just a single, default export it'll work as expected. If you later add any other export all of the consumers will break. I don't know if users are really going to notice that and I think it's a good idea to warn them. It is presented as a solution for upgrading to v6, but I expect people to do it in general if not warned off.

Also, it doesn't match the currently proposed behavior for consuming ES modules from CJS in Node, even when there is only a single, default export.

**Comment by hzoo** [comment]
Merged https://github.com/babel/babel.github.io/issues/882 - feel free to make another pr to edit it
