### ISSUE TITLE
Question about your words: "ES2015 is the latest standard of ECMAScript"

### ISSUE THREAD

**Issue by crenkore** [babel/babel.github.io#876]
Hi, in your doc you said the ES2015 is the latest, hasn't the latest ES7 passed and standared?? according to Brian Terlson and the http://www.ecma-international.org/ecma-262/7.0/index.html.

And I found that you have finished the babel-preset-es2016, isn't it??

So why don't put the link of babel-preset-es2016 to the home page so that visitor could use es 2016 conveniently??

**Comment by hzoo** [comment]
Yeah its just not updated that's all. Also the es2016 preset only includes es2016 specific transforms. I merged https://github.com/babel/babel.github.io/pull/878 which should help
