### ISSUE TITLE
[...set] compiled in [].concat(set)

### ISSUE THREAD

**Issue by caub** [babel/babel.github.io#879]
`[].concat(set)` doesn't do anything useful and is not equivalent to `[...set]`

`Array.from(set)` works though

**Comment by hzoo** [comment]
You're using loose mode? http://babeljs.io/repl/#?evaluate=true&lineWrap=true&presets=es2015&experimental=false&loose=false&spec=false&code=%5B...a%5D%3B&playground=true works as you say ^ without it though

Thanks for reporting! However repo is for reporting issues/suggestions on our website, http://babeljs.io/, not for bugs in babel or support.

If you have an an actual bug/suggestion for babel itself - free feel to make an issue on our [phabricator](https://phabricator.babeljs.io/). If you just have an usage issue or want help, I would recommend checking out our [slack community](https://slack.babeljs.io/) or [StackOverflow](http://stackoverflow.com/questions/tagged/babeljs).

**Comment by caub** [comment]
ah indeed, thanks
