### ISSUE TITLE
RPEL: Failed to load babel stand alone resource from npmcdn.com

### ISSUE THREAD

**Issue by tnga** [babel/babel.github.io#881]
here are log error in console:
```
Failed to load resource: the server responded with a status of 403 (OK)
https://npmcdn.com/babel-polyfill@6/dist/polyfill.min.js Failed to load resource: the server responded with a status of 403 (OK)
repl.js:352 Uncaught ReferenceError: Babel is not defined
```

**Comment by hzoo** [comment]
That's the error from loading the repl? http://babeljs.io/repl/? Can you clear cache and try again? It loads for me fine and don't see any errors and the cdn link works as well

**Comment by tnga** [comment]
it's okay now, the problem was due to my FAI, which because of how it configure internet access, customer recurrently have to validate a **google captcha** before view a web site. That sometime affect download link, event for a simple asset in a html page (because of redirection to captcha).

**Comment by thejameskyle** [comment]
Something I'd find upsetting is happening here...

**Comment by tnga** [comment]
Yeah, other asset internal to the website or from* cdn* different to *npmcdn* aren't affected by this behavior. :confused:
