### ISSUE TITLE
Make sure all links have a trailing slash

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#905]
Ref https://github.com/babel/babel.github.io/pull/904#discussion_r76585865 @mathiasbynens 

> These links should all have a trailing slash to prevent useless HTTP redirects.

``` sh
$ curl -sI 'https://babeljs.io/docs/plugins/transform-export-extensions'
HTTP/1.1 301 Moved Permanently
[…]
Location: http://babeljs.io/docs/plugins/transform-export-extensions/
[…]
```

Checked with `\[(\w|\/|-)+\]\(\/(\w|\/|-)+[^/]\)$` regex

**Comment by mathiasbynens** [comment]
To clarify: not _every link ever_, of course, but any internal ones.

**Comment by hzoo** [comment]
https://github.com/babel/babel.github.io/pull/974 used a regex
