### ISSUE TITLE
Please implement support for Async/Await

### ISSUE THREAD

**Issue by eudisd** [babel/babel.github.io#906]
Please implement support for Async/Await in your "Try it out" page (https://babeljs.io/repl/)

Currently even with all the stage-* options enabled, as well as "latest" and es2017, non of these options enable support for async/await. Would be really good for try out examples involving this.

**Comment by hzoo** [comment]
@eudisd it should already work? It was a stage-3 option before and just got moved to be enabled for es2017.

http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=latest&experimental=false&loose=false&spec=false&code=async%20function%20a()%20%7B%0A%20%20return%20Promise.resolve(1)%3B%20%0A%7D%0A%0Aconsole.log('async')%3B%0Aa().then(a%20%3D%3E%20console.log(a))%3B&playground=true

**Comment by eudisd** [comment]
Sorry @hzoo my mistake, this actually works as expected.  Closing this issue.
