### ISSUE TITLE
inherits class with transform-class-properties

### ISSUE THREAD

**Issue by Zerstoren** [babel/babel.github.io#907]
Simply code

```javascript
class MyClass {
  myProp = 42;

  constructor() {
    console.log(this.myProp);  // Prints '42'
  }
}

class NewClass extends MyClass {
  myProp = 52;
  
  constructor() {
    super();
    console.log(this.myProp); // Prints '52'
  }
  
}

new NewClass();
```

This is wrong. In all exists languages in constructor call this.myProp will be equal 52, not 42.

**Comment by loganfsmyth** [comment]
Babel implements this slightly wrong, but not in the way you want it to. In a fully conforming implementation, this would throw an exception because you've defined the property twice.

Also FYI, this repo is for our Website, it is not for filing bugs against Babel itself.

**Comment by Zerstoren** [comment]
Sorry for posting in wrong "thread", but in babel github repository issues disabled. 

It\s not "way you want it to", it's way like 99% languages create this feature, from Java to php.
I am not define property twice, I define property in parent class and want redefine it in inherit class.

Close this issue, we don't need to continue current disqus about languages implements.

**Comment by hzoo** [comment]
We are using https://phabricator.babeljs.io for issues (although we are working on moving back to github issues atm). From the readme: https://github.com/babel/babel#want-to-report-a-bug-or-request-a-feature

**Comment by hzoo** [comment]
we have issues again but you can search if it's already reported https://github.com/babel/babel/issues
