### ISSUE TITLE
babeli doesn't work as intended

### ISSUE THREAD

**Issue by tomByrer** [babel/babel.github.io#917]
[example preset](http://babeljs.io/repl/#?babili=true&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=%2F%2F%20Example%20ES2015%20Code%0Aclass%20Mangler%20%7B%0A%20%20constructor(program)%20%7B%0A%20%20%20%20this.program%20%3D%20program%3B%0A%20%20%7D%0A%7D%0Anew%20Mangler()%3B%20%2F%2F
%20without%20this%20it%20would%20just%20output%20nothing)
Output:
`"use strict";function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor))throw new TypeError("Cannot call a class as a function")}// Example ES2015 Code
var a=function a(b){_classCallCheck(this,a),this.program=b};new a;`

Expected; from doc's [output](https://github.com/babel/babili#why):
`class a{constructor(b){this.program=b}}new a;`

**Comment by hzoo** [comment]
It works, you are using the es2015 preset. If you turn that off it works as expected.

**Comment by tomByrer** [comment]
Ah, thanks @hzoo.
But still is a source of confusion, don't you think?

**Comment by hzoo** [comment]
It can be confusing if it's not the correct options but that comment is explaining what that means? The repl saves the options from previous runs so you just need to change it to not compile es2015.

It's unrelated to babili itself.
