### ISSUE TITLE
Add note about `sourceMaps` option not emitting files

### ISSUE THREAD

**Issue by jeffijoe** [babel/babel.github.io#918]
I spent quite a bit of time pondering why when I had `sourceMaps: "both"` in my .babelrc, that babel CLI did not emit source files. Some googling led me to [this issue](https://phabricator.babeljs.io/T2484) explaining the reasoning (which does make sense).

I suggest adding a bolded note to the sourcemaps documentation about the sourcemap files not being emitted unless passing `-s` to the CLI.

**Comment by hzoo** [comment]
Is this still an issue? I think we fixed some issues with options/cli recently

**Comment by jeffijoe** [comment]
What has changed? Will the sourceMaps option in .babelrc emit sourcemap files now?
