### ISSUE TITLE
REPL: Add support for all Babel options

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel.github.io#92]
It'd be nice to have a dropdown or something that allowed you to toggle all the options for 6to5. It'd be _even nicer_ if it was auto generated from the latest 6to5.

**Comment by thejameskyle** [comment]
It would help to quickly diagnose issues like this: https://github.com/6to5/6to5/issues/580

**Comment by sparty02** [comment]
Dynamically understanding the current option set will be tricky.  The following options (from ```6to5/lib/6to5/file.js``` may not necessarily be relevant to the REPL.  Unless the core exposes the kinds of options the REPL is interested in via an isolated list, it may not be practical to do this in an automated way.

* filename
* filenameRelative
* modules
* sourceMap
* sourceMapName
* sourceFileName
* sourceRoot
* moduleRoot
* moduleIds
* comments
* keepModuleIdExtensions
* code
* ast
* format
