### ISSUE TITLE
Remove Courier New from font-family of REPL editor

### ISSUE THREAD

**Issue by vramana** [babel/babel.github.io#923]
I work on Ubuntu on Laptop with 1920x1080. It doesn't come with Monaco or Menlo or Consolas. So Courier New ends up being the font for ace-editor. And it looks like this. 

 ![image](https://cloud.githubusercontent.com/assets/3112509/18628671/f0cc8bcc-7e7e-11e6-9551-e564a6b4e7f2.png)

It really hard to read and understand anything.

**Comment by danez** [comment]
Do you know what is the preferred monospace code font that comes preinstalled on ubuntu?

**Comment by vramana** [comment]
Ubuntu Mono. It looks nice too. Also the font size can be a bit better.

**Comment by hzoo** [comment]
Made https://github.com/babel/babel.github.io/issues/970
