### ISSUE TITLE
Document that you can use the shorthand notation with an org preset

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#926]
Referencing https://github.com/babel/babel/pull/4542/files

Changing this section https://babeljs.io/docs/plugins/#pluginpreset-paths to explain that `"@babel/es2015"` works in substitute for `"@babel/babel-preset-es2015"`

By editing https://github.com/babel/babel.github.io/blob/master/docs/plugins.md

**Comment by kopijunkie** [comment]
will take a stab at this

**Comment by hzoo** [comment]
Sorry, I totally forgot I made an issue for this one.. 😂

**Comment by hzoo** [comment]
If you want to take on https://github.com/babel/babel.github.io/issues/932 go ahead! - basically moving around the plugin for `object-rest-spread` from stage-2 docs to stage-3

**Comment by kopijunkie** [comment]
yeap, sure. will go with that one then. :)
