### ISSUE TITLE
Add missing docs from 6.16

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#928]
From https://github.com/babel/babel/releases/tag/v6.16.0 (anything on the changelog that is spec compilancy/new feature)

new pages
- [x] for new plugins for async generators (make new plugin page, update stage-2)
- [x] move object-rest-spread to stage 3 https://github.com/babel/babel.github.io/issues/932

update pages
- [x] add parserOpts + generatorOpts to babel options

**Comment by hzoo** [comment]
Is there anything we need to do to get babel-standalone updated for the repl @Daniel15? I can add you do this repo too (or add me to standalone/move it to babel repo?).

**Comment by Daniel15** [comment]
> Is there anything we need to do to get babel-standalone updated for the repl @Daniel15?

Oh yeah, sorry, Babel-standalone is supposed to auto-update whenever a new Babel release is pushed to npm, but I still haven't set up the cronjob that runs the auto-update script. I'll run it now, new release should be up soon.

> or add me to standalone/move it to babel repo?

This sounds like a good idea! It probably makes sense for babel-standalone to live in the Babel GitHub organisation.

**Comment by Daniel15** [comment]
Pushed an update to babel-standalone:
https://github.com/Daniel15/babel-standalone/commit/2d01ab331fb327cb2792018360dfec8dd90fe480
https://unpkg.com/babel-standalone@6/babel.min.js &rarr; https://unpkg.com/babel-standalone@6.17.0/babel.min.js

I'll definitely automate this, I just need to add `npm publish` + Github release creation to my update script.

**Comment by hzoo** [comment]
Awesome - we also added `babel-plugin-transform-async-generator-functions` and `babel-plugin-syntax-async-generator-functions` (now stage-3, so it's included)

**Comment by hzoo** [comment]
Yeah later it would be great if we can update the repl code to support choosing individual plugins, presets, and options

**Comment by hzoo** [comment]
https://github.com/babel/babel.github.io/commit/d318a6eaaede11149ce5f340a2dfbacc392c8c54
