### ISSUE TITLE
Reorganize headings

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#930]
![screen shot 2016-09-30 at 10 55 01 am](https://cloud.githubusercontent.com/assets/588473/18995932/6c5d4954-86fc-11e6-9b75-a3b7ee03e918.png)
- If we want to add a "syntax highlighting" guide/section where can it go?

Maybe we can move `Learn ES2015` since it's on the page in a few other places

**Comment by mareksuscak** [comment]
IMO we could replace "Learn ES2015" with "Docs", "Guides" or "Recipes" or something similar. Possibly also moving some of the top level section under that new entry.

**Comment by hzoo** [comment]
Ok maybe make it `Docs | Setup | Try it Out | FAQ`?

**Comment by mareksuscak** [comment]
@hzoo Yeah that would make a lot of sense. Where to put Learn ES2015, Plugins and Usage tho? The first two could become subsections of the Docs but Usage contains subsections. How to deal with that? 2nd level subsections?

**Comment by hzoo** [comment]
We could just move everything in Usage under Docs and only have 1 subsection

**Comment by hzoo** [comment]
It hasn't been updated in a while so definetely can try some different stuff out

**Comment by danharper** [comment]
I think the docs need a sidebar, like the [React docs](https://facebook.github.io/react/docs/hello-world.html).

How about this for a re-structured top nav:

```
Primary Nav (left):

* Docs
* Try it out
* Community
* Blog

Secondary Nav (right):

* Twitter
* GitHub
```

Then on the Docs page, the following sidebar:

```
# Quick Start

* Browser
* Node
* Plugins
* Polyfills
* Caveats (or.. Browser Support)
* Editors
* Linting
* Babili (Minification)

# Advanced Configuration

* Options
* CLI
* babel-node
* In-Browser Compilation
* Babel API
```

I'm unsure where a "Learn ESXXX" would go, but wherever it goes perhaps just give "highlights" and link off-site for the details. Plenty of community resources for that.

**Comment by hzoo** [comment]
So the docs used to have a sidebar for headings but there was some bug when moving from redcarpet to kramdown that i didn't figure out

**Comment by mareksuscak** [comment]
You mean this sidebar?

![screen shot 2016-11-24 at 15 27 36](https://cloud.githubusercontent.com/assets/613647/20601786/9e07ff9c-b25a-11e6-8728-4538688b0c3a.png)

Has it been fixed recently or you meant another one? I'd love to help move this guy forward so what's the final decision? Do we want to add yet another sidebar on the left or just keep it as simple as it is now and have one huge page containing all the sections?

**Comment by hzoo** [comment]
Yeah the sidebar you have there is the one that got fixed (the script was loading).

I was meaning the header at the top - we should simplify that somehow

<img width="1265" alt="screen shot 2016-11-24 at 9 34 50 am" src="https://cloud.githubusercontent.com/assets/588473/20601959/45bcfc24-b229-11e6-9233-94543be2a473.png">

<img width="1259" alt="screen shot 2016-11-24 at 9 35 06 am" src="https://cloud.githubusercontent.com/assets/588473/20601966/4e898d0e-b229-11e6-935b-c41e1733fe34.png">

<img width="1235" alt="screen shot 2016-11-24 at 9 35 36 am" src="https://cloud.githubusercontent.com/assets/588473/20601986/62757530-b229-11e6-9035-c4b963fe56fa.png">

Maybe just `Docs | Setup | Try it Out` on the left, or even just `Docs | Try It Out` and then create a docs page that links to everything else
