### ISSUE TITLE
stage-2 incorrectly lists object-rest-spread

### ISSUE THREAD

**Issue by olalonde** [babel/babel.github.io#932]
See https://github.com/babel/babel/issues/4645

**Comment by hzoo** [comment]
Yeah I made https://github.com/babel/babel.github.io/issues/928 - do you want to make a PR @olalonde? I can guide you through it

**Comment by olalonde** [comment]
Thanks for offering but no time ;(

**Comment by hzoo** [comment]
Looks like https://github.com/babel/babel.github.io/commit/dfc2aa090dcf2606a2d87480b49544e779d4dc60

**Comment by hzoo** [comment]
https://github.com/babel/babel.github.io/pull/934
