### ISSUE TITLE
Mention that Object Rest sometimes also need transform-es2015-parameters

### ISSUE THREAD

**Issue by daltones** [babel/babel.github.io#942]
When [this page](http://babeljs.io/docs/plugins/transform-object-rest-spread/) says:

> Even if you are using Node 6 or a platform that supports destructuring, transform-es2015-destructuring will currently need to be enabled if using object rest properties.

This is true if you use object rest only with normal variables. But if you try directly with function parameters, it will not transform.

``` js
// Will work with transform-es2015-destructuring
let { x, y, ...z } = { x: 1, y: 2, a: 3, b: 4 };

// Won't transform! Needs transform-es2015-parameters + transform-es2015-destructuring.
function foo({ x, y, ...z }) {}
```

I guess it's a good idea document that case.

Sorry I'm not sending a straight PR… I still have doubts about my English. 😿

**Comment by danharper** [comment]
If you want to send a PR mentioning `transform-es2015-parameters`, that'd be great :) Your English is great 👍

**Comment by hzoo** [comment]
Added in https://github.com/babel/babel.github.io/commit/27a010a0efd0be1977e0e2ebe7d3d93e139cc5b0
