### ISSUE TITLE
npmjs.com page for babel-preset-es2017 not up to date

### ISSUE THREAD

**Issue by jsyrjala** [babel/babel.github.io#946]
https://www.npmjs.com/package/babel-preset-es2017 contains instruction to use this line in entry point:
```
import 'babel-preset-es2017/polyfill';
```

however, this will not work because atleast babel-preset-es2017 v6.16.0 doesn't contain that file.

See https://github.com/babel/babel/issues/4476 and http://stackoverflow.com/questions/39395497/cannot-resolve-module-babel-preset-es2017-polyfill for discussion.

**Comment by hzoo** [comment]
https://github.com/bettiolo/babel-preset-es2017 was the original package. The actual readme is https://github.com/babel/babel/tree/master/packages/babel-preset-es2017 - there is no polyfill now

**Comment by kristianmandrup** [comment]
What is the best way to make it work with webpack 2.x??

http://stackoverflow.com/questions/39395497/cannot-resolve-module-babel-preset-es2017-polyfill

Can we make webpack detect and use `.babelrc` file or do we need custom webpack settings for babel loader!? So much confusion, these configurations are changing all the time...

https://github.com/babel/babel-loader

`loader: 'babel?presets[]=es2015'`

```js
      query: {
        presets: ['es2015']
      }
```

or ??


`cacheIdentifier`: Default is a string composed by the babel-core's version, the babel-loader's version, the contents of `.babelrc` file if it exists and the value of the environment variable `BABEL_ENV` with a fallback to the `NODE_ENV` environment variable. This can be set to a custom value to force cache busting if the identifier changes.

Please add best practice webpack config to your Readme :)
