### ISSUE TITLE
Guide for using Babel with Webpack implies a few setup steps

### ISSUE THREAD

**Issue by ericandrewlewis** [babel/babel.github.io#948]
I'm setting up Babel with Webpack in a new project.

I came across [this Babel setup page](https://babeljs.io/docs/setup/#webpack), which left me a bit confused as it includes some steps to setup (installing the `babel-loader` and the `babel-core` packages and a section of the webpack JS config object) and implies some other steps (installing `webpack` and understanding how to structure the rest of the `webpack.config.js` file).

After leaving this Babel doc page I found this [blog post](https://www.twilio.com/blog/2015/08/setting-up-react-for-es6-with-webpack-and-babel-2.html) which includes all these steps and successfully setup my project.

**Comment by hzoo** [comment]
We link to the babel-loader repo (https://github.com/babel/babel-loader) which has more info. I think it's because the guide is for setting up babel if you have webpack setup already. we could link to other guides as well
