### ISSUE TITLE
Repl is crashing with x.default.existsSync is not a function

### ISSUE THREAD

**Issue by arjunu** [babel/babel.github.io#956]
I go to https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=&experimental=false&loose=false&spec=false&code=

and I get

```javascript
repl.js?t=2016-10-24T22:58:50+00:00:423 Uncaught TypeError: x.default.existsSync is not a function
```
<img width="1438" alt="screen shot 2016-10-25 at 3 13 49 pm" src="https://cloud.githubusercontent.com/assets/4038217/19681167/1092560e-9ac6-11e6-8590-54ffe4ddf5fe.png">

**Comment by danez** [comment]
Fixed with 73f3e09
