### ISSUE TITLE
Write a post on codemods and how to make one with Babel

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#972]
jscodeshift, astexplorer, etc

**Comment by thejameskyle** [comment]
idk if I agree you should write codemods with Babel's transform api. It's designed for creating transforms that run alongside dozens of other transform every single time you build. jscodeshift is better designed for this purpose in my opinion.

**Comment by hzoo** [comment]
I think it's another option - can talk about both and maybe do an example using both ways?

**Comment by brigand** [comment]
Wouldn't this have the problem of changing the formatting of your code?

**Comment by thejameskyle** [comment]
Not with recast support

**Comment by hzoo** [comment]
@brigand yeah babel can now use recast as the parser/generator + babylon https://babeljs.io/blog/2016/09/28/6.16.0#new-feature, ex: https://github.com/fkling/astexplorer/pull/161

**Comment by eventualbuddha** [comment]
As someone writing transforms, why would I choose jscodeshift over babel+recast or vise-versa? Should we try to standardize on one or the other?
