### ISSUE TITLE
Add to clipboard button for cli commands/code?

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#987]
Maybe https://clipboardjs.com/? just did a simple search

![image](https://cloud.githubusercontent.com/assets/588473/20458732/8e19d80a-ae7a-11e6-8d84-7dc6e8e1be6d.png)

**Comment by xtuc** [comment]
Can we close this ? Since the PR was merged.

**Comment by hzoo** [comment]
Yeah!
