### ISSUE TITLE
Move main plugin/package docs from here to babel/babel

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#997]
> If you have issues please comment here, join our slack (signup: slack.babeljs.io, url: babeljs.slack.com), ping @babeljs on twitter

## #528

> eg
http://babeljs.io/docs/plugins/transform-es2015-modules-systemjs/
vs
https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-modules-systemjs
The "via CLI" & "via Node API" are missing. IMHO README should be the source for the webpage automated builder.
Added preferred bonus: the web page links to README ("Edit doc contents in README").

https://github.com/babel/babel.github.io/issues/528 was implemented via https://github.com/babel/babel.github.io/pull/990 (git submodule and rendering the markdown from the README)

Now this website repo can pull in information from the actual readme.md file used for npm in the babel repo.

## Issue

What we need to do now is to move the docs in [`docs/`](/docs) to link to the README's in [babel/babel/packages](https://github.com/babel/babel/tree/master/packages)

Basically for those docs we want to take the contents there and replace them.

Example: https://github.com/babel/babel.github.io/pull/990/files#diff-b11e0ae0e12e1f69b9e7bd1a63ac06d2R20

<img width="994" alt="screen shot 2016-11-22 at 3 35 33 pm" src="https://cloud.githubusercontent.com/assets/588473/20540995/573a1830-b0c9-11e6-8d43-ccee9a71e17f.png">

## Instructions

For each docs page that needs to be changed:

- [ ] Find the correct page on the babel website docs under [`docs/`](/docs) to edit: Example is [`docs/plugins/preset-stage-0.md`](/docs/plugins/preset-stage-0.md)

<img width="1003" alt="screen shot 2016-11-22 at 3 36 18 pm" src="https://cloud.githubusercontent.com/assets/588473/20541022/71528a68-b0c9-11e6-80df-07495aa63782.png">

- [ ] Find the corresponding page on [`babel/babel`](https://github.com/babel/babel): Example is [`babel-preset-stage-0/README.md`]

<img width="992" alt="screen shot 2016-11-22 at 3 37 00 pm" src="https://cloud.githubusercontent.com/assets/588473/20541043/8b45647c-b0c9-11e6-867a-d8e7aed5e0eb.png">

(https://github.com/babel/babel/blob/master/packages/babel-preset-stage-0/README.md)
- [ ] Copy over any missing information from the website page (this repo) to the main babel repo README (it's not as updated usually).

> This might be extra links, examples, etc:

<img width="897" alt="screen shot 2016-11-22 at 3 38 26 pm" src="https://cloud.githubusercontent.com/assets/588473/20541101/bf940e68-b0c9-11e6-8eab-432120a326a8.png">

- [ ] Replace the old contents with ` {% include package_readme.html %}`

<img width="994" alt="screen shot 2016-11-22 at 3 35 33 pm" src="https://cloud.githubusercontent.com/assets/588473/20541107/c49b30c6-b0c9-11e6-856b-d8808f3a9aae.png">

> This may mean a PR to the main babel repo as well as this repo.

### Another Example

Check both https://github.com/babel/babel/pull/4884 and https://github.com/babel/babel.github.io/commit/241be67ed65a4162876972fff839dd5c318595c2

### Misc

It's fine to do this one pr at a time, you don't have to change everything or all of the docs! (makes it easier to review too)

**Comment by hzoo** [comment]
Example:

Website repo: https://github.com/babel/babel.github.io/blob/master/docs/plugins/check-es2015-constants.md

Babel repo: https://github.com/babel/babel/blob/master/packages/babel-plugin-check-es2015-constants/README.md

**Comment by lukyth** [comment]
I will help this out!

**Comment by tomByrer** [comment]
I appreciate all your work @hzoo

**Comment by existentialism** [comment]
Remaining (feel free to call dibs!) READMEs to move:

- [ ] babel-plugin-external-helpers
- [ ] babel-plugin-transform-class-constructor-call
- [ ] babel-plugin-transform-class-properties
- [ ] babel-plugin-transform-decorators
- [ ] babel-plugin-transform-do-expressions
- [ ] babel-plugin-transform-es3-member-expression-literals
- [ ] babel-plugin-transform-es3-property-literals
- [ ] babel-plugin-transform-es5-property-mutators
- [ ] babel-plugin-transform-eval
- [ ] babel-plugin-transform-exponentiation-operator
- [ ] babel-plugin-transform-export-extensions
- [ ] babel-plugin-transform-flow-comments
- [ ] babel-plugin-transform-flow-strip-types
- [ ] babel-plugin-transform-function-bind
- [ ] babel-plugin-transform-jscript
- [ ] babel-plugin-transform-object-assign
- [ ] babel-plugin-transform-object-rest-spread
- [ ] babel-plugin-transform-object-set-prototype-of-to-assign
- [ ] babel-plugin-transform-proto-to-assign
- [ ] babel-plugin-transform-runtime
- [ ] babel-plugin-transform-strict-mode
- [ ] babel-plugin-undeclared-variables-check

**Comment by hzoo** [comment]
Kinda wish we could automatically do it now (not necessary) - for each package in `babel/babel` generate the file haha. I guess then we would need a build step and it would get complicated

**Comment by hzoo** [comment]
Amazing work everyone!! @lukyth, @raspo, @existentialism
