### ISSUE TITLE
Create docs for https://github.com/babel/babili

### ISSUE THREAD

**Issue by hzoo** [babel/babel.github.io#999]
Given https://github.com/babel/babel.github.io/pull/995 (curated plugin list) and https://github.com/babel/babel.github.io/pull/990 (readme from repos), we should render the readme's for babel-minify on the website!

cc @kangax @boopathi

**Comment by hzoo** [comment]
https://github.com/babel/babel.github.io/pull/1004 is merged

If you want to include the readme from the monorepo you can do `{% include package_readme.html from="babili" %}`

Now we'll want to create a separate main page for babili

**Comment by hzoo** [comment]
Moving over the already created plugin pages to use the README from babili

by adding

```
{% include package_readme.html from="babili" %}
```

- [ ] babel-plugin-transform-inline-environment-variables
- [ ] babel-plugin-transform-member-expression-literals
- [ ] babel-plugin-transform-merge-sibling-variables
- [x] babel-plugin-transform-minify-booleans
- [ ] babel-plugin-transform-node-env-inline
- [ ] babel-plugin-transform-property-literals
- [ ] babel-plugin-transform-remove-console
- [ ] babel-plugin-transform-remove-debugger
- [ ] babel-plugin-transform-simplify-comparison-operators
- [ ] babel-plugin-transform-undefined-to-void

Will also want to add the new plugins not listed ^

**Comment by hzoo** [comment]
This is all done in https://github.com/babel/babel.github.io/pull/1029? @geordidearns 

You can add a `Fixes #999` in your commit or description of the PR to make this close when your PR is merged

**Comment by existentialism** [comment]
Yep, I believe this is finished!
